import type {
  CapstoneCheck,
  CapstoneLine,
  CapstoneStory,
} from '../lib/content/types';

export const capstoneLines: CapstoneLine[] = [
  {
    id: 'capstone-line-ch01-01',
    japanese: 'わたしはたなかです。',
    reading: 'わたしはたなかです。',
    english: 'I am Tanaka.',
    grammarTags: ['topic', 'copula', 'self-introduction'],
    vocabTags: ['self', 'name'],
    sourceExampleIds: ['ex-colin-desu'],
  },
  {
    id: 'capstone-line-ch01-02',
    japanese: 'わたしはがくせいです。',
    reading: 'わたしはがくせいです。',
    english: 'I am a student.',
    grammarTags: ['topic', 'copula', 'identity'],
    vocabTags: ['self', 'school'],
    sourceExampleIds: ['ex-student-desu'],
  },
  {
    id: 'capstone-line-ch01-03',
    japanese: 'これはほんです。',
    reading: 'これはほんです。',
    english: 'This is a book.',
    grammarTags: ['demonstrative', 'copula', 'identity'],
    vocabTags: ['classroom', 'book'],
    sourceExampleIds: ['ex-kore-hon'],
  },
  {
    id: 'capstone-line-ch01-04',
    japanese: 'これはなんですか。',
    reading: 'これはなんですか。',
    english: 'What is this?',
    grammarTags: ['demonstrative', 'question', 'copula'],
    vocabTags: ['classroom', 'question'],
    sourceExampleIds: ['ex-kore-nan'],
  },
  {
    id: 'capstone-line-ch01-05',
    japanese: 'きょうしつでべんきょうします。',
    reading: 'きょうしつでべんきょうします。',
    english: 'I study in the classroom.',
    grammarTags: ['location', 'daily-routine'],
    vocabTags: ['school', 'study'],
    sourceExampleIds: ['ex-classroom-study'],
  },
  {
    id: 'capstone-line-ch01-06',
    japanese: 'まいにちがっこうにいきます。',
    reading: 'まいにちがっこうにいきます。',
    english: 'I go to school every day.',
    grammarTags: ['destination', 'movement', 'daily-routine'],
    vocabTags: ['school', 'time', 'daily-routine'],
    sourceExampleIds: ['ex-mainichi-gakkou'],
  },
  {
    id: 'capstone-line-ch01-07',
    japanese: 'せんせいはきょうしつにいます。',
    reading: 'せんせいはきょうしつにいます。',
    english: 'The teacher is in the classroom.',
    grammarTags: ['existence', 'location', 'animate'],
    vocabTags: ['school', 'role', 'classroom'],
    sourceExampleIds: ['ex-sensei-kyoushitsu-imasu'],
  },
  {
    id: 'capstone-line-ch01-08',
    japanese: 'ほんはつくえのうえにあります。',
    reading: 'ほんはつくえのうえにあります。',
    english: 'The book is on the desk.',
    grammarTags: ['existence', 'position', 'location'],
    vocabTags: ['book', 'desk'],
    sourceExampleIds: ['ex-hon-tsukue-ue'],
  },
  {
    id: 'capstone-line-ch01-09',
    japanese: 'アニメがすきです。',
    reading: 'アニメがすきです。',
    english: 'I like anime.',
    grammarTags: ['preference', 'particle-ga', 'daily-conversation'],
    vocabTags: ['hobby', 'preference'],
    sourceExampleIds: ['ex-anime-suki'],
  },
  {
    id: 'capstone-line-ch01-10',
    japanese: 'トイレはどこですか。',
    reading: 'トイレはどこですか。',
    english: 'Where is the bathroom?',
    grammarTags: ['question', 'location', 'topic'],
    vocabTags: ['place', 'question'],
    sourceExampleIds: ['ex-toire-doko'],
  },
  {
    id: 'capstone-line-ch01-11',
    japanese: 'トイレはあそこです。',
    reading: 'トイレはあそこです。',
    english: 'The bathroom is over there.',
    grammarTags: ['location', 'answer-patterns', 'topic'],
    vocabTags: ['place', 'location'],
    sourceExampleIds: ['ex-toire-asoko'],
  },
];

export const capstoneChecks: CapstoneCheck[] = [
  {
    id: 'capstone-check-ch01-identity',
    lineId: 'capstone-line-ch01-01',
    prompt: 'Who is speaking?',
    choices: ['Tanaka', 'The teacher', 'A friend'],
    answer: 'Tanaka',
    support: 'わたしはたなかです means "I am Tanaka."',
  },
  {
    id: 'capstone-check-ch01-place',
    lineId: 'capstone-line-ch01-05',
    prompt: 'Where does the studying happen?',
    choices: ['In the classroom', 'At the library', 'At the cafe'],
    answer: 'In the classroom',
    support: 'きょうしつで marks the classroom as the place of action.',
  },
  {
    id: 'capstone-check-ch01-object',
    lineId: 'capstone-line-ch01-03',
    prompt: 'What is this?',
    choices: ['A book', 'A notebook', 'Homework'],
    answer: 'A book',
    support: 'これはほんです means "This is a book."',
  },
  {
    id: 'capstone-check-ch01-bathroom',
    lineId: 'capstone-line-ch01-11',
    prompt: 'Where is the bathroom?',
    choices: ['Over there', 'Here', 'In the classroom'],
    answer: 'Over there',
    support: 'あそこ points to a place over there.',
  },
];

export const capstoneStories: CapstoneStory[] = [
  {
    id: 'capstone-story-ch01-first-day',
    chapterId: 'chapter-core-01',
    title: 'First day basics',
    summary:
      'A chapter closeout for first-day identity, classroom objects, simple movement, existence, preferences, and location answers.',
    estimatedMinutes: 5,
    sourcePackIds: [1, 2, 3, 4, 5],
    lineIds: [
      'capstone-line-ch01-01',
      'capstone-line-ch01-02',
      'capstone-line-ch01-03',
      'capstone-line-ch01-04',
      'capstone-line-ch01-05',
      'capstone-line-ch01-06',
      'capstone-line-ch01-07',
      'capstone-line-ch01-08',
      'capstone-line-ch01-09',
      'capstone-line-ch01-10',
      'capstone-line-ch01-11',
    ],
    checkIds: [
      'capstone-check-ch01-identity',
      'capstone-check-ch01-object',
      'capstone-check-ch01-place',
      'capstone-check-ch01-bathroom',
    ],
  },
];
