import type {
  CapstoneCheck,
  CapstoneLine,
  CapstoneStory,
} from '../lib/content/types';

export const capstoneLines: CapstoneLine[] = [
  {
    id: 'capstone-line-ch01-01',
    japanese: 'わたしはたなかです。',
    reading: 'わたしはたなかです。',
    english: 'I am Tanaka.',
    grammarTags: ['topic', 'copula', 'self-introduction'],
    vocabTags: ['self', 'name'],
    sourceExampleIds: ['ex-colin-desu'],
  },
  {
    id: 'capstone-line-ch01-02',
    japanese: 'わたしはがくせいです。',
    reading: 'わたしはがくせいです。',
    english: 'I am a student.',
    grammarTags: ['topic', 'copula', 'identity'],
    vocabTags: ['self', 'school'],
    sourceExampleIds: ['ex-student-desu'],
  },
  {
    id: 'capstone-line-ch01-03',
    japanese: 'これはほんです。',
    reading: 'これはほんです。',
    english: 'This is a book.',
    grammarTags: ['demonstrative', 'copula', 'identity'],
    vocabTags: ['classroom', 'book'],
    sourceExampleIds: ['ex-kore-hon'],
  },
  {
    id: 'capstone-line-ch01-04',
    japanese: 'これはなんですか。',
    reading: 'これはなんですか。',
    english: 'What is this?',
    grammarTags: ['demonstrative', 'question', 'copula'],
    vocabTags: ['classroom', 'question'],
    sourceExampleIds: ['ex-kore-nan'],
  },
  {
    id: 'capstone-line-ch01-05',
    japanese: 'きょうしつでべんきょうします。',
    reading: 'きょうしつでべんきょうします。',
    english: 'I study in the classroom.',
    grammarTags: ['location', 'daily-routine'],
    vocabTags: ['school', 'study'],
    sourceExampleIds: ['ex-classroom-study'],
  },
  {
    id: 'capstone-line-ch01-06',
    japanese: 'まいにちがっこうにいきます。',
    reading: 'まいにちがっこうにいきます。',
    english: 'I go to school every day.',
    grammarTags: ['destination', 'movement', 'daily-routine'],
    vocabTags: ['school', 'time', 'daily-routine'],
    sourceExampleIds: ['ex-mainichi-gakkou'],
  },
  {
    id: 'capstone-line-ch01-07',
    japanese: 'せんせいはきょうしつにいます。',
    reading: 'せんせいはきょうしつにいます。',
    english: 'The teacher is in the classroom.',
    grammarTags: ['existence', 'location', 'animate'],
    vocabTags: ['school', 'role', 'classroom'],
    sourceExampleIds: ['ex-sensei-kyoushitsu-imasu'],
  },
  {
    id: 'capstone-line-ch01-08',
    japanese: 'ほんはつくえのうえにあります。',
    reading: 'ほんはつくえのうえにあります。',
    english: 'The book is on the desk.',
    grammarTags: ['existence', 'position', 'location'],
    vocabTags: ['book', 'desk'],
    sourceExampleIds: ['ex-hon-tsukue-ue'],
  },
  {
    id: 'capstone-line-ch01-09',
    japanese: 'アニメがすきです。',
    reading: 'アニメがすきです。',
    english: 'I like anime.',
    grammarTags: ['preference', 'particle-ga', 'daily-conversation'],
    vocabTags: ['hobby', 'preference'],
    sourceExampleIds: ['ex-anime-suki'],
  },
  {
    id: 'capstone-line-ch01-10',
    japanese: 'トイレはどこですか。',
    reading: 'トイレはどこですか。',
    english: 'Where is the bathroom?',
    grammarTags: ['question', 'location', 'topic'],
    vocabTags: ['place', 'question'],
    sourceExampleIds: ['ex-toire-doko'],
  },
  {
    id: 'capstone-line-ch01-11',
    japanese: 'トイレはあそこです。',
    reading: 'トイレはあそこです。',
    english: 'The bathroom is over there.',
    grammarTags: ['location', 'answer-patterns', 'topic'],
    vocabTags: ['place', 'location'],
    sourceExampleIds: ['ex-toire-asoko'],
  },
  {
    id: 'capstone-line-ch02-01',
    japanese: 'これはわたしのほんです。',
    reading: 'これはわたしのほんです。',
    english: 'This is my book.',
    grammarTags: ['noun-linking-no', 'possession', 'copula'],
    vocabTags: ['book', 'self', 'personal-objects'],
    sourceExampleIds: ['ex-kore-watashi-no-hon'],
  },
  {
    id: 'capstone-line-ch02-02',
    japanese: 'ほんはおもしろいです。',
    reading: 'ほんはおもしろいです。',
    english: 'The book is interesting.',
    grammarTags: ['adjective-predicate', 'topic', 'copula'],
    vocabTags: ['book', 'description'],
    sourceExampleIds: ['ex-hon-omoshiroi'],
  },
  {
    id: 'capstone-line-ch02-03',
    japanese: 'よるほんをよみます。',
    reading: 'よるほんをよみます。',
    english: 'I read a book at night.',
    grammarTags: ['masu', 'object', 'daily-routine'],
    vocabTags: ['book', 'night', 'reading'],
    sourceExampleIds: ['ex-yoru-hon-yomimasu'],
  },
  {
    id: 'capstone-line-ch02-04',
    japanese: 'きのうほんをよみました。',
    reading: 'きのうほんをよみました。',
    english: 'I read a book yesterday.',
    grammarTags: ['mashita', 'object', 'past-action'],
    vocabTags: ['book', 'yesterday', 'reading'],
    sourceExampleIds: ['ex-kinou-hon-yomimashita'],
  },
  {
    id: 'capstone-line-ch02-05',
    japanese: 'きのううちでにほんごをべんきょうしました。',
    reading: 'きのううちでにほんごをべんきょうしました。',
    english: 'I studied Japanese at home yesterday.',
    grammarTags: ['mashita', 'place-of-action-de', 'object'],
    vocabTags: ['home', 'study', 'japanese'],
    sourceExampleIds: ['ex-kinou-uchi-nihongo-benkyoushimashita'],
  },
  {
    id: 'capstone-line-ch02-06',
    japanese: 'へやはしずかです。',
    reading: 'へやはしずかです。',
    english: 'The room is quiet.',
    grammarTags: ['adjective-predicate', 'topic', 'copula'],
    vocabTags: ['room', 'description'],
    sourceExampleIds: ['ex-heya-shizuka'],
  },
  {
    id: 'capstone-line-ch02-07',
    japanese: 'きょうコーヒーをのみません。',
    reading: 'きょうコーヒーをのみません。',
    english: 'I do not drink coffee today.',
    grammarTags: ['masen', 'object', 'daily-routine'],
    vocabTags: ['coffee', 'today'],
    sourceExampleIds: ['ex-kyou-koohii-nomimasen'],
  },
  {
    id: 'capstone-line-ch02-08',
    japanese: 'みずをのんでもいいですか。',
    reading: 'みずをのんでもいいですか。',
    english: 'May I drink water?',
    grammarTags: ['temo-ii-desu-ka', 'object', 'permission'],
    vocabTags: ['water', 'request'],
    sourceExampleIds: ['ex-mizu-nonde-mo-ii'],
  },
  {
    id: 'capstone-line-ch02-09',
    japanese: 'ちょっとまってください。',
    reading: 'ちょっとまってください。',
    english: 'Please wait a moment.',
    grammarTags: ['te-kudasai', 'request'],
    vocabTags: ['classroom', 'request'],
    sourceExampleIds: ['ex-chotto-matte-kudasai'],
  },
  {
    id: 'capstone-line-ch02-10',
    japanese: 'ゆっくりよんでください。',
    reading: 'ゆっくりよんでください。',
    english: 'Please read slowly.',
    grammarTags: ['te-kudasai', 'request'],
    vocabTags: ['reading', 'request'],
    sourceExampleIds: ['ex-yukkuri-yonde-kudasai'],
  },
  {
    id: 'capstone-line-ch03-01',
    japanese: 'なんじですか。',
    reading: 'なんじですか。',
    english: 'What time is it?',
    grammarTags: ['nanji-desu-ka', 'question', 'copula'],
    vocabTags: ['time', 'question'],
    sourceExampleIds: ['ex-nanji-desu-ka'],
  },
  {
    id: 'capstone-line-ch03-02',
    japanese: 'ごぜんはちじです。',
    reading: 'ごぜんはちじです。',
    english: 'It is 8 AM.',
    grammarTags: ['time-expression', 'copula'],
    vocabTags: ['time', 'morning'],
    sourceExampleIds: ['ex-gozen-hachiji-desu'],
  },
  {
    id: 'capstone-line-ch03-03',
    japanese: 'かようびにかいものをします。',
    reading: 'かようびにかいものをします。',
    english: 'I do some shopping on Tuesday.',
    grammarTags: ['weekday-ni', 'object', 'masu'],
    vocabTags: ['weekday', 'shopping'],
    sourceExampleIds: ['ex-kayoubi-ni-kaimono-o-shimasu'],
  },
  {
    id: 'capstone-line-ch03-04',
    japanese: 'コンビニでおかしをかいます。',
    reading: 'コンビニでおかしをかいます。',
    english: 'I buy snacks at the convenience store.',
    grammarTags: ['kaimasu-shopping', 'place-of-action-de', 'object'],
    vocabTags: ['convenience-store', 'snacks', 'shopping'],
    sourceExampleIds: ['ex-konbini-de-okashi-o-kaimasu'],
  },
  {
    id: 'capstone-line-ch03-05',
    japanese: 'おにぎりをください。',
    reading: 'おにぎりをください。',
    english: 'Please give me a rice ball.',
    grammarTags: ['o-kudasai', 'request', 'object'],
    vocabTags: ['food', 'shopping'],
    sourceExampleIds: ['ex-onigiri-o-kudasai'],
  },
  {
    id: 'capstone-line-ch03-06',
    japanese: 'えきはどこですか。',
    reading: 'えきはどこですか。',
    english: 'Where is the station?',
    grammarTags: ['where-questions', 'topic', 'copula'],
    vocabTags: ['station', 'question'],
    sourceExampleIds: ['ex-eki-wa-doko-desu-ka'],
  },
  {
    id: 'capstone-line-ch03-07',
    japanese: 'えきはあそこです。',
    reading: 'えきはあそこです。',
    english: 'The station is over there.',
    grammarTags: ['place-answers', 'topic', 'copula'],
    vocabTags: ['station', 'location'],
    sourceExampleIds: ['ex-eki-wa-asoko-desu'],
  },
  {
    id: 'capstone-line-ch03-08',
    japanese: 'スーパーまであるきます。',
    reading: 'スーパーまであるきます。',
    english: 'I walk to the supermarket.',
    grammarTags: ['made-questions', 'movement', 'masu'],
    vocabTags: ['supermarket', 'walking'],
    sourceExampleIds: ['ex-supaa-made-arukimasu'],
  },
  {
    id: 'capstone-line-ch03-09',
    japanese: 'バスでゆうびんきょくにいきます。',
    reading: 'バスでゆうびんきょくにいきます。',
    english: 'I go to the post office by bus.',
    grammarTags: ['transport-de', 'destination-ni', 'movement'],
    vocabTags: ['bus', 'post-office'],
    sourceExampleIds: ['ex-basu-de-yuubinkyoku-ni-ikimasu'],
  },
  {
    id: 'capstone-line-ch03-10',
    japanese: 'こうさてんでまっすぐいきます。',
    reading: 'こうさてんでまっすぐいきます。',
    english: 'Go straight at the intersection.',
    grammarTags: ['navigation-turns', 'place-of-action-de', 'movement'],
    vocabTags: ['directions', 'intersection'],
    sourceExampleIds: ['ex-kousaten-o-massugu-ikimasu'],
  },
  {
    id: 'capstone-line-ch03-11',
    japanese: 'コンビニはえきのとなりです。',
    reading: 'コンビニはえきのとなりです。',
    english: 'The convenience store is next to the station.',
    grammarTags: ['navigation-place-answers', 'noun-linking-no', 'topic'],
    vocabTags: ['convenience-store', 'station', 'location'],
    sourceExampleIds: ['ex-konbini-wa-eki-no-tonari-desu'],
  },
  {
    id: 'capstone-line-ch04-01',
    japanese: 'いっしょにえいがかんにいきますか。',
    reading: 'いっしょにえいがかんにいきますか。',
    english: 'Will you go to the movie theater together?',
    grammarTags: ['invitation-questions', 'destination-ni', 'question'],
    vocabTags: ['movie-theater', 'invitation'],
    sourceExampleIds: ['ex-issho-ni-eigakan-ni-ikimasu-ka'],
  },
  {
    id: 'capstone-line-ch04-02',
    japanese: 'はい、いきます。',
    reading: 'はい、いきます。',
    english: 'Yes, I will go.',
    grammarTags: ['plan-responses', 'masu'],
    vocabTags: ['response', 'movement'],
    sourceExampleIds: ['ex-hai-ikimasu'],
  },
  {
    id: 'capstone-line-ch04-03',
    japanese: 'なんじにあいますか。',
    reading: 'なんじにあいますか。',
    english: 'What time shall we meet?',
    grammarTags: ['invitation-questions', 'time-ni', 'question'],
    vocabTags: ['time', 'meeting'],
    sourceExampleIds: ['ex-nanji-ni-aimasu-ka'],
  },
  {
    id: 'capstone-line-ch04-04',
    japanese: 'ろくじにあいましょう。',
    reading: 'ろくじにあいましょう。',
    english: 'Let’s meet at six.',
    grammarTags: ['mashou-proposals', 'time-ni', 'meeting'],
    vocabTags: ['time', 'meeting'],
    sourceExampleIds: ['ex-rokuji-ni-aimashou'],
  },
  {
    id: 'capstone-line-ch04-05',
    japanese: 'どこであいますか。',
    reading: 'どこであいますか。',
    english: 'Where shall we meet?',
    grammarTags: ['meeting-place-de', 'question'],
    vocabTags: ['meeting', 'place'],
    sourceExampleIds: ['ex-doko-de-aimasu-ka'],
  },
  {
    id: 'capstone-line-ch04-06',
    japanese: 'えきであいます。',
    reading: 'えきであいます。',
    english: 'We will meet at the station.',
    grammarTags: ['meeting-place-de', 'masu'],
    vocabTags: ['station', 'meeting'],
    sourceExampleIds: ['ex-eki-de-aimasu'],
  },
  {
    id: 'capstone-line-ch04-07',
    japanese: 'もうつきました。',
    reading: 'もうつきました。',
    english: 'I already arrived.',
    grammarTags: ['arrival-status-updates', 'mashita'],
    vocabTags: ['arrival', 'status'],
    sourceExampleIds: ['ex-mou-tsukimashita'],
  },
  {
    id: 'capstone-line-ch04-08',
    japanese: 'いまえきです。',
    reading: 'いまえきです。',
    english: 'I am at the station now.',
    grammarTags: ['arrival-status-updates', 'copula', 'location'],
    vocabTags: ['station', 'now'],
    sourceExampleIds: ['ex-ima-eki-desu'],
  },
  {
    id: 'capstone-line-ch04-09',
    japanese: 'えきでまっています。',
    reading: 'えきでまっています。',
    english: 'I am waiting at the station.',
    grammarTags: ['waiting-status-lines', 'place-of-action-de', 'progressive'],
    vocabTags: ['station', 'waiting'],
    sourceExampleIds: ['ex-eki-de-matteimasu'],
  },
  {
    id: 'capstone-line-ch04-10',
    japanese: 'コーヒーをのみませんか。',
    reading: 'コーヒーをのみませんか。',
    english: 'Won’t you drink coffee?',
    grammarTags: ['masenka-suggestions', 'object', 'question'],
    vocabTags: ['coffee', 'suggestion'],
    sourceExampleIds: ['ex-koohii-o-nomimasen-ka'],
  },
  {
    id: 'capstone-line-ch04-11',
    japanese: 'カフェでコーヒーをのみましょう。',
    reading: 'カフェでコーヒーをのみましょう。',
    english: 'Let’s drink coffee at the cafe.',
    grammarTags: ['mashou-proposals', 'place-of-action-de', 'object'],
    vocabTags: ['cafe', 'coffee', 'proposal'],
    sourceExampleIds: ['ex-kafe-de-koohii-o-nomimashou'],
  },
  {
    id: 'capstone-line-ch05-01',
    japanese: 'いつあいましょうか。',
    reading: 'いつあいましょうか。',
    english: 'When shall we meet?',
    grammarTags: ['calendar-plan-recombination', 'question', 'meeting'],
    vocabTags: ['calendar', 'meeting'],
    sourceExampleIds: ['ex-itsu-aimashou-ka'],
  },
  {
    id: 'capstone-line-ch05-02',
    japanese: 'しがつみっかのろくじにあいましょう。',
    reading: 'しがつみっかのろくじにあいましょう。',
    english: 'Let’s meet at six on April third.',
    grammarTags: ['calendar-appointment-lines', 'mashou-proposals', 'time-ni'],
    vocabTags: ['calendar', 'meeting', 'time'],
    sourceExampleIds: ['ex-shigatsu-mikka-no-rokuji-ni-aimashou'],
  },
  {
    id: 'capstone-line-ch05-03',
    japanese: 'なんじからなんじまでですか。',
    reading: 'なんじからなんじまでですか。',
    english: 'From what time until what time is it?',
    grammarTags: ['kara-made-time-ranges', 'time-window-questions', 'question'],
    vocabTags: ['time', 'schedule'],
    sourceExampleIds: ['ex-nanji-kara-nanji-made-desu-ka'],
  },
  {
    id: 'capstone-line-ch05-04',
    japanese: 'くじからごじまでです。',
    reading: 'くじからごじまでです。',
    english: 'It is from nine to five.',
    grammarTags: ['kara-made-time-ranges', 'copula'],
    vocabTags: ['time', 'schedule'],
    sourceExampleIds: ['ex-kuji-kara-goji-made-desu'],
  },
  {
    id: 'capstone-line-ch05-05',
    japanese: 'ごがつようかにとしょかんにいきましょうか。',
    reading: 'ごがつようかにとしょかんにいきましょうか。',
    english: 'Shall we go to the library on May eighth?',
    grammarTags: ['calendar-plan-recombination', 'mashou-plan-questions', 'destination-ni'],
    vocabTags: ['calendar', 'library', 'plan'],
    sourceExampleIds: ['ex-gogatsu-youka-ni-toshokan-ni-ikimashou-ka'],
  },
  {
    id: 'capstone-line-ch05-06',
    japanese: 'りんごをいくつかいますか。',
    reading: 'りんごをいくつかいますか。',
    english: 'How many apples will you buy?',
    grammarTags: ['quantity-questions', 'kaimasu-shopping', 'object'],
    vocabTags: ['shopping', 'apples', 'quantity'],
    sourceExampleIds: ['ex-ringo-o-ikutsu-kaimasu-ka'],
  },
  {
    id: 'capstone-line-ch05-07',
    japanese: 'りんごをふたつかいます。',
    reading: 'りんごをふたつかいます。',
    english: 'I will buy two apples.',
    grammarTags: ['quantity-request-lines', 'kaimasu-shopping', 'object'],
    vocabTags: ['shopping', 'apples', 'quantity'],
    sourceExampleIds: ['ex-ringo-o-futatsu-kaimasu'],
  },
  {
    id: 'capstone-line-ch05-08',
    japanese: 'これはいくらですか。',
    reading: 'これはいくらですか。',
    english: 'How much is this?',
    grammarTags: ['price-questions', 'demonstrative', 'question'],
    vocabTags: ['price', 'shopping'],
    sourceExampleIds: ['ex-kore-wa-ikura-desu-ka'],
  },
  {
    id: 'capstone-line-ch05-09',
    japanese: 'りんごはさんびゃくえんです。',
    reading: 'りんごはさんびゃくえんです。',
    english: 'The apples are 300 yen.',
    grammarTags: ['yen-price-lines', 'topic', 'copula'],
    vocabTags: ['price', 'apples', 'yen'],
    sourceExampleIds: ['ex-ringo-wa-sanbyaku-en-desu'],
  },
  {
    id: 'capstone-line-ch05-10',
    japanese: 'パンをみっつください。',
    reading: 'パンをみっつください。',
    english: 'Three breads, please.',
    grammarTags: ['quantity-request-lines', 'request', 'object'],
    vocabTags: ['bread', 'quantity', 'shopping'],
    sourceExampleIds: ['ex-pan-o-mittsu-kudasai'],
  },
  {
    id: 'capstone-line-ch06-01',
    japanese: 'みずはありますか。',
    reading: 'みずはありますか。',
    english: 'Do you have water?',
    grammarTags: ['availability-questions', 'existence-arimasu-imasu', 'question'],
    vocabTags: ['water', 'store'],
    sourceExampleIds: ['ex-mizu-wa-arimasu-ka'],
  },
  {
    id: 'capstone-line-ch06-02',
    japanese: 'はい、あります。',
    reading: 'はい、あります。',
    english: 'Yes, we do.',
    grammarTags: ['availability-questions', 'existence-arimasu-imasu'],
    vocabTags: ['store', 'response'],
    sourceExampleIds: ['ex-hai-arimasu'],
  },
  {
    id: 'capstone-line-ch06-03',
    japanese: 'それをください。',
    reading: 'それをください。',
    english: 'That one, please.',
    grammarTags: ['selection-confirmation-lines', 'request', 'object'],
    vocabTags: ['store', 'request'],
    sourceExampleIds: ['ex-sore-o-kudasai'],
  },
  {
    id: 'capstone-line-ch06-04',
    japanese: 'これでいいです。',
    reading: 'これでいいです。',
    english: 'This is fine.',
    grammarTags: ['selection-confirmation-lines', 'copula'],
    vocabTags: ['store', 'choice'],
    sourceExampleIds: ['ex-korede-ii-desu'],
  },
  {
    id: 'capstone-line-ch06-05',
    japanese: 'これをかってください。',
    reading: 'これをかってください。',
    english: 'Please buy this.',
    grammarTags: ['te-form-core', 'te-kudasai', 'object'],
    vocabTags: ['shopping', 'request'],
    sourceExampleIds: ['ex-kore-o-katte-kudasai'],
  },
  {
    id: 'capstone-line-ch06-06',
    japanese: 'ここでまってください。',
    reading: 'ここでまってください。',
    english: 'Please wait here.',
    grammarTags: ['te-form-core', 'te-kudasai', 'place-of-action-de'],
    vocabTags: ['waiting', 'request'],
    sourceExampleIds: ['ex-koko-de-matte-kudasai'],
  },
  {
    id: 'capstone-line-ch06-07',
    japanese: 'りんごをかって、それからうちにいきます。',
    reading: 'りんごをかって、それからうちにいきます。',
    english: 'I buy apples, and then go home.',
    grammarTags: ['action-sequence-te', 'destination-ni', 'object'],
    vocabTags: ['apples', 'home', 'sequence'],
    sourceExampleIds: ['ex-ringo-o-katte-sorekara-uchi-ni-ikimasu'],
  },
  {
    id: 'capstone-line-ch06-08',
    japanese: 'いまパンをかっています。',
    reading: 'いまパンをかっています。',
    english: 'I am buying bread now.',
    grammarTags: ['progressive-actions', 'object'],
    vocabTags: ['bread', 'shopping', 'now'],
    sourceExampleIds: ['ex-ima-pan-o-katteimasu'],
  },
  {
    id: 'capstone-line-ch06-09',
    japanese: 'いまカフェでコーヒーをのんでいます。',
    reading: 'いまカフェでコーヒーをのんでいます。',
    english: 'I am drinking coffee at a cafe now.',
    grammarTags: ['progressive-actions', 'place-of-action-de', 'object'],
    vocabTags: ['cafe', 'coffee', 'now'],
    sourceExampleIds: ['ex-ima-kafe-de-koohii-o-nondeimasu'],
  },
  {
    id: 'capstone-line-ch06-10',
    japanese: 'このパンはおいしくないです。',
    reading: 'このパンはおいしくないです。',
    english: 'This bread is not tasty.',
    grammarTags: ['adjective-negative-i', 'topic', 'copula'],
    vocabTags: ['bread', 'description'],
    sourceExampleIds: ['ex-kono-pan-oishikunai-desu'],
  },
  {
    id: 'capstone-line-ch06-11',
    japanese: 'このカフェはきれいじゃないです。',
    reading: 'このカフェはきれいじゃないです。',
    english: 'This cafe is not very clean.',
    grammarTags: ['adjective-negative-na', 'topic', 'copula'],
    vocabTags: ['cafe', 'description'],
    sourceExampleIds: ['ex-kono-kafe-kirei-janai-desu'],
  },
  {
    id: 'capstone-line-ch07-01',
    japanese: 'りょこうはたのしかったです。',
    reading: 'りょこうはたのしかったです。',
    english: 'The trip was fun.',
    grammarTags: ['adjective-past-i', 'topic', 'copula'],
    vocabTags: ['travel', 'description'],
    sourceExampleIds: ['ex-ryokou-wa-tanoshikatta-desu'],
  },
  {
    id: 'capstone-line-ch07-02',
    japanese: 'としょかんはしずかでした。',
    reading: 'としょかんはしずかでした。',
    english: 'The library was quiet.',
    grammarTags: ['adjective-past-na', 'topic', 'copula'],
    vocabTags: ['library', 'description'],
    sourceExampleIds: ['ex-toshokan-shizuka-deshita'],
  },
  {
    id: 'capstone-line-ch07-03',
    japanese: 'レストランよりカフェのほうがやすいです。',
    reading: 'レストランよりカフェのほうがやすいです。',
    english: 'The cafe is cheaper than the restaurant.',
    grammarTags: ['comparison-yori-houga-adjectives', 'description'],
    vocabTags: ['cafe', 'restaurant', 'comparison'],
    sourceExampleIds: ['ex-resutoran-yori-kafe-no-hou-ga-yasui-desu'],
  },
  {
    id: 'capstone-line-ch07-04',
    japanese: 'バスよりでんしゃのほうがはやいです。',
    reading: 'バスよりでんしゃのほうがはやいです。',
    english: 'The train is faster than the bus.',
    grammarTags: ['comparison-yori-houga-adjectives', 'transport'],
    vocabTags: ['bus', 'train', 'comparison'],
    sourceExampleIds: ['ex-basu-yori-densha-no-hou-ga-hayai-desu'],
  },
  {
    id: 'capstone-line-ch07-05',
    japanese: 'としょかんがいちばんしずかです。',
    reading: 'としょかんがいちばんしずかです。',
    english: 'The library is the quietest.',
    grammarTags: ['superlatives-ichiban-adjectives', 'description'],
    vocabTags: ['library', 'superlative'],
    sourceExampleIds: ['ex-toshokan-ga-ichiban-shizuka-desu'],
  },
  {
    id: 'capstone-line-ch07-06',
    japanese: 'えいががいちばんおもしろいです。',
    reading: 'えいががいちばんおもしろいです。',
    english: 'Movies are the most interesting.',
    grammarTags: ['superlatives-ichiban-adjectives', 'preference'],
    vocabTags: ['movies', 'superlative'],
    sourceExampleIds: ['ex-eiga-ga-ichiban-omoshiroi-desu'],
  },
  {
    id: 'capstone-line-ch07-07',
    japanese: 'よくカフェでコーヒーをのみます。',
    reading: 'よくカフェでコーヒーをのみます。',
    english: 'I often drink coffee at a cafe.',
    grammarTags: ['frequency-adverbs-routine', 'place-of-action-de', 'object'],
    vocabTags: ['cafe', 'coffee', 'frequency'],
    sourceExampleIds: ['ex-yoku-kafe-de-koohii-o-nomimasu'],
  },
  {
    id: 'capstone-line-ch07-08',
    japanese: 'あまりえいがをみません。',
    reading: 'あまりえいがをみません。',
    english: 'I do not watch movies very often.',
    grammarTags: ['frequency-adverbs-amari-masen', 'negative', 'object'],
    vocabTags: ['movies', 'frequency'],
    sourceExampleIds: ['ex-amari-eiga-o-mimasen'],
  },
  {
    id: 'capstone-line-ch07-09',
    japanese: 'このカフェはやすいですからよくいきます。',
    reading: 'このカフェはやすいですからよくいきます。',
    english: 'Because this cafe is cheap, I go there often.',
    grammarTags: ['reasons-kara-choices', 'frequency-adverbs-routine'],
    vocabTags: ['cafe', 'reason'],
    sourceExampleIds: ['ex-kono-kafe-wa-yasui-desukara-yoku-ikimasu'],
  },
  {
    id: 'capstone-line-ch07-10',
    japanese: 'としょかんはしずかですからべんきょうします。',
    reading: 'としょかんはしずかですからべんきょうします。',
    english: 'Because the library is quiet, I study there.',
    grammarTags: ['reasons-kara-choices', 'description'],
    vocabTags: ['library', 'study', 'reason'],
    sourceExampleIds: ['ex-toshokan-wa-shizuka-desukara-benkyoushimasu'],
  },
  {
    id: 'capstone-line-ch07-11',
    japanese: 'このレストランはたかいですからいきません。',
    reading: 'このレストランはたかいですからいきません。',
    english: 'Because this restaurant is expensive, I do not go there.',
    grammarTags: ['reasons-kara-refusals', 'negative'],
    vocabTags: ['restaurant', 'reason'],
    sourceExampleIds: ['ex-kono-resutoran-wa-takai-desukara-ikimasen'],
  },
  {
    id: 'capstone-line-ch08-01',
    japanese: 'どようびにえいがかんにいきたいです。',
    reading: 'どようびにえいがかんにいきたいです。',
    english: 'I want to go to the movie theater on Saturday.',
    grammarTags: ['desire-tai-places', 'time', 'destination-ni'],
    vocabTags: ['movie-theater', 'saturday', 'movement'],
    sourceExampleIds: ['ex-doyoubi-ni-eigakan-ni-ikitai-desu'],
  },
  {
    id: 'capstone-line-ch08-02',
    japanese: 'パンをたべたいです。',
    reading: 'パンをたべたいです。',
    english: 'I want to eat bread.',
    grammarTags: ['desire-tai-actions', 'object'],
    vocabTags: ['bread', 'food'],
    sourceExampleIds: ['ex-pan-o-tabetai-desu'],
  },
  {
    id: 'capstone-line-ch08-03',
    japanese: 'あたらしいカメラがほしいです。',
    reading: 'あたらしいカメラがほしいです。',
    english: 'I want a new camera.',
    grammarTags: ['desire-object-hoshii', 'adjectives'],
    vocabTags: ['camera', 'shopping'],
    sourceExampleIds: ['ex-atarashii-kamera-ga-hoshii-desu'],
  },
  {
    id: 'capstone-line-ch08-04',
    japanese: 'なにがほしいですか。',
    reading: 'なにがほしいですか。',
    english: 'What do you want?',
    grammarTags: ['desire-object-hoshii-questions', 'question'],
    vocabTags: ['question', 'shopping'],
    sourceExampleIds: ['ex-nani-ga-hoshii-desu-ka'],
  },
  {
    id: 'capstone-line-ch08-05',
    japanese: 'にほんごをよむことができます。',
    reading: 'にほんごをよむことができます。',
    english: 'I can read Japanese.',
    grammarTags: ['ability-kotoga-dekimasu-actions', 'object'],
    vocabTags: ['japanese-language', 'reading'],
    sourceExampleIds: ['ex-nihongo-o-yomu-koto-ga-dekimasu'],
  },
  {
    id: 'capstone-line-ch08-06',
    japanese: 'じてんしゃにのることができます。',
    reading: 'じてんしゃにのることができます。',
    english: 'I can ride a bicycle.',
    grammarTags: ['ability-kotoga-dekimasu-actions', 'transport'],
    vocabTags: ['bicycle', 'ability'],
    sourceExampleIds: ['ex-jitensha-ni-noru-koto-ga-dekimasu'],
  },
  {
    id: 'capstone-line-ch08-07',
    japanese: 'すしをたべたことがあります。',
    reading: 'すしをたべたことがあります。',
    english: 'I have eaten sushi before.',
    grammarTags: ['experience-takotoga-arimasu-activities', 'past'],
    vocabTags: ['sushi', 'food', 'experience'],
    sourceExampleIds: ['ex-sushi-o-tabeta-koto-ga-arimasu'],
  },
  {
    id: 'capstone-line-ch08-08',
    japanese: 'えいがかんにいったことがあります。',
    reading: 'えいがかんにいったことがあります。',
    english: 'I have been to a movie theater before.',
    grammarTags: ['experience-takotoga-arimasu-places', 'destination-ni'],
    vocabTags: ['movie-theater', 'experience'],
    sourceExampleIds: ['ex-eigakan-ni-itta-koto-ga-arimasu'],
  },
  {
    id: 'capstone-line-ch08-09',
    japanese: 'だれとえいがかんにいきますか。',
    reading: 'だれとえいがかんにいきますか。',
    english: 'Who do you go to the movie theater with?',
    grammarTags: ['companions-dare-to', 'question', 'destination-ni'],
    vocabTags: ['movie-theater', 'companion'],
    sourceExampleIds: ['ex-dare-to-eigakan-ni-ikimasu-ka'],
  },
  {
    id: 'capstone-line-ch08-10',
    japanese: 'ともだちとえいがかんにいきます。',
    reading: 'ともだちとえいがかんにいきます。',
    english: 'I go to the movie theater with a friend.',
    grammarTags: ['companions-dare-to', 'destination-ni'],
    vocabTags: ['friend', 'movie-theater', 'companion'],
    sourceExampleIds: ['ex-tomodachi-to-eigakan-ni-ikimasu'],
  },
  {
    id: 'capstone-line-ch08-11',
    japanese: 'じてんしゃでカフェにいきます。',
    reading: 'じてんしゃでカフェにいきます。',
    english: 'I go to the cafe by bicycle.',
    grammarTags: ['methods-douyatte-transport', 'transport-de', 'destination-ni'],
    vocabTags: ['bicycle', 'cafe', 'transport'],
    sourceExampleIds: ['ex-jitensha-de-kafe-ni-ikimasu'],
  },
  {
    id: 'capstone-line-ch09-01',
    japanese: 'どれがいいですか。',
    reading: 'どれがいいですか。',
    english: 'Which one is good?',
    grammarTags: ['choices-dore-dono-items', 'question'],
    vocabTags: ['choice', 'question'],
    sourceExampleIds: ['ex-dore-ga-ii-desu-ka'],
  },
  {
    id: 'capstone-line-ch09-02',
    japanese: 'どのくつがいいですか。',
    reading: 'どのくつがいいですか。',
    english: 'Which shoes are good?',
    grammarTags: ['choices-dore-dono-items', 'question'],
    vocabTags: ['shoes', 'choice'],
    sourceExampleIds: ['ex-dono-kutsu-ga-ii-desu-ka'],
  },
  {
    id: 'capstone-line-ch09-03',
    japanese: 'しろいくつがいいです。',
    reading: 'しろいくつがいいです。',
    english: 'The white shoes are good for me.',
    grammarTags: ['choices-dore-dono-items', 'adjectives'],
    vocabTags: ['shoes', 'white', 'choice'],
    sourceExampleIds: ['ex-shiroi-kutsu-ga-ii-desu'],
  },
  {
    id: 'capstone-line-ch09-04',
    japanese: 'だいじょうぶですか。',
    reading: 'だいじょうぶですか。',
    english: 'Are you okay?',
    grammarTags: ['health-condition-basics', 'question'],
    vocabTags: ['health', 'condition'],
    sourceExampleIds: ['ex-daijoubu-desu-ka'],
  },
  {
    id: 'capstone-line-ch09-05',
    japanese: 'きょうはあたまがいたいです。',
    reading: 'きょうはあたまがいたいです。',
    english: 'My head hurts today.',
    grammarTags: ['health-condition-basics', 'body-parts'],
    vocabTags: ['today', 'head', 'health'],
    sourceExampleIds: ['ex-kyou-wa-atama-ga-itai-desu'],
  },
  {
    id: 'capstone-line-ch09-06',
    japanese: 'きょうはあついですからみずをのみます。',
    reading: 'きょうはあついですからみずをのみます。',
    english: 'Because it is hot today, I drink water.',
    grammarTags: ['weather-practical-choices', 'reason-kara', 'object'],
    vocabTags: ['today', 'hot', 'water'],
    sourceExampleIds: ['ex-kyou-wa-atsui-desukara-mizu-o-nomimasu'],
  },
  {
    id: 'capstone-line-ch09-07',
    japanese: 'あめですからかさをもちます。',
    reading: 'あめですからかさをもちます。',
    english: 'Because it is raining, I carry an umbrella.',
    grammarTags: ['weather-practical-choices', 'reason-kara', 'object'],
    vocabTags: ['rain', 'umbrella', 'weather'],
    sourceExampleIds: ['ex-ame-desukara-kasa-o-mochimasu'],
  },
  {
    id: 'capstone-line-ch09-08',
    japanese: 'えきでのりかえます。',
    reading: 'えきでのりかえます。',
    english: 'I change trains at the station.',
    grammarTags: ['travel-steps-changing-arrival', 'place-of-action-de'],
    vocabTags: ['station', 'travel'],
    sourceExampleIds: ['ex-eki-de-norikaemasu'],
  },
  {
    id: 'capstone-line-ch09-09',
    japanese: 'でんしゃがおくれます。',
    reading: 'でんしゃがおくれます。',
    english: 'The train is delayed.',
    grammarTags: ['problems-okuremasu', 'particle-ga'],
    vocabTags: ['train', 'delay'],
    sourceExampleIds: ['ex-densha-ga-okuremasu'],
  },
  {
    id: 'capstone-line-ch09-10',
    japanese: 'すみません、ちょっとおくれます。',
    reading: 'すみません、ちょっとおくれます。',
    english: 'Sorry, I will be a little late.',
    grammarTags: ['problems-okuremasu', 'status'],
    vocabTags: ['delay', 'apology'],
    sourceExampleIds: ['ex-sumimasen-chotto-okuremasu'],
  },
  {
    id: 'capstone-line-ch09-11',
    japanese: 'すぐれんらくします。',
    reading: 'すぐれんらくします。',
    english: 'I will contact them right away.',
    grammarTags: ['problems-muzukashii-renraku', 'daily-action'],
    vocabTags: ['contact', 'right-away'],
    sourceExampleIds: ['ex-sugu-renrakushimasu'],
  },
  {
    id: 'capstone-line-ch10-01',
    japanese: 'がっこうのまえにパンをたべます。',
    reading: 'がっこうのまえにパンをたべます。',
    english: 'I eat bread before school.',
    grammarTags: ['before-after-maeni', 'object'],
    vocabTags: ['school', 'bread', 'before'],
    sourceExampleIds: ['ex-gakkou-no-mae-ni-pan-o-tabemasu'],
  },
  {
    id: 'capstone-line-ch10-02',
    japanese: 'がっこうのあとでカフェにいきます。',
    reading: 'がっこうのあとでカフェにいきます。',
    english: 'I go to a cafe after school.',
    grammarTags: ['before-after-atode', 'destination-ni'],
    vocabTags: ['school', 'cafe', 'after'],
    sourceExampleIds: ['ex-gakkou-no-ato-de-kafe-ni-ikimasu'],
  },
  {
    id: 'capstone-line-ch10-03',
    japanese: 'ともだちはがくせいだ。',
    reading: 'ともだちはがくせいだ。',
    english: 'My friend is a student.',
    grammarTags: ['plain-style-recognition-copula-na', 'topic'],
    vocabTags: ['friend', 'student', 'plain-style'],
    sourceExampleIds: ['ex-tomodachi-wa-gakusei-da'],
  },
  {
    id: 'capstone-line-ch10-04',
    japanese: 'きょうはげんきじゃない。',
    reading: 'きょうはげんきじゃない。',
    english: 'I am not feeling well today.',
    grammarTags: ['plain-style-recognition-copula-na', 'negative', 'health-condition-basics'],
    vocabTags: ['today', 'health', 'plain-style'],
    sourceExampleIds: ['ex-kyou-wa-genki-janai'],
  },
  {
    id: 'capstone-line-ch10-05',
    japanese: 'うちでほんをよむ。',
    reading: 'うちでほんをよむ。',
    english: 'I read a book at home.',
    grammarTags: ['plain-style-recognition-verbs-present', 'place-of-action-de', 'object'],
    vocabTags: ['home', 'book', 'plain-style'],
    sourceExampleIds: ['ex-uchi-de-hon-o-yomu'],
  },
  {
    id: 'capstone-line-ch10-06',
    japanese: 'きょうコーヒーをのまない。',
    reading: 'きょうコーヒーをのまない。',
    english: 'I will not drink coffee today.',
    grammarTags: ['plain-style-recognition-verbs-present', 'negative', 'object'],
    vocabTags: ['today', 'coffee', 'plain-style'],
    sourceExampleIds: ['ex-kyou-koohii-o-nomanai'],
  },
  {
    id: 'capstone-line-ch10-07',
    japanese: 'じゅぎょうのあとでカフェにいきます。それから、べんきょうします。',
    reading: 'じゅぎょうのあとでカフェにいきます。それから、べんきょうします。',
    english: 'After class, I go to a cafe, and after that I study.',
    grammarTags: ['before-after-atode', 'connected-speech-soshite-sorekara', 'destination-ni'],
    vocabTags: ['class', 'cafe', 'study'],
    sourceExampleIds: ['ex-jugyou-no-ato-de-kafe-ni-ikimasu-sorekara-benkyoushimasu'],
  },
  {
    id: 'capstone-line-ch10-08',
    japanese: 'てんきがいいです。でも、うちでべんきょうします。',
    reading: 'てんきがいいです。でも、うちでべんきょうします。',
    english: 'The weather is good, but I study at home.',
    grammarTags: ['connected-speech-demo-dakara', 'contrast', 'place-of-action-de'],
    vocabTags: ['weather', 'home', 'study'],
    sourceExampleIds: ['ex-tenki-ga-ii-desu-demo-uchi-de-benkyoushimasu'],
  },
  {
    id: 'capstone-line-ch10-09',
    japanese: 'コーヒーとおちゃがすきです。',
    reading: 'コーヒーとおちゃがすきです。',
    english: 'I like coffee and tea.',
    grammarTags: ['listing-to-combinations', 'preference', 'particle-ga'],
    vocabTags: ['coffee', 'tea', 'preference'],
    sourceExampleIds: ['ex-koohii-to-ocha-ga-suki-desu'],
  },
  {
    id: 'capstone-line-ch10-10',
    japanese: 'パンやケーキをたべます。',
    reading: 'パンやケーキをたべます。',
    english: 'I eat things like bread and cake.',
    grammarTags: ['listing-ya-open-lists', 'object'],
    vocabTags: ['bread', 'cake', 'open-list'],
    sourceExampleIds: ['ex-pan-ya-keeki-o-tabemasu'],
  },
  {
    id: 'capstone-line-ch10-11',
    japanese: 'くすりやみずをかいます。',
    reading: 'くすりやみずをかいます。',
    english: 'I buy things like medicine and water.',
    grammarTags: ['listing-ya-open-lists', 'object', 'shopping'],
    vocabTags: ['medicine', 'water', 'open-list'],
    sourceExampleIds: ['ex-kusuri-ya-mizu-o-kaimasu'],
  },
];

export const capstoneChecks: CapstoneCheck[] = [
  {
    id: 'capstone-check-ch01-identity',
    lineId: 'capstone-line-ch01-01',
    prompt: 'Who is speaking?',
    choices: ['Tanaka', 'The teacher', 'A friend'],
    answer: 'Tanaka',
    support: 'わたしはたなかです means "I am Tanaka."',
  },
  {
    id: 'capstone-check-ch01-place',
    lineId: 'capstone-line-ch01-05',
    prompt: 'Where does the studying happen?',
    choices: ['In the classroom', 'At the library', 'At the cafe'],
    answer: 'In the classroom',
    support: 'きょうしつで marks the classroom as the place of action.',
  },
  {
    id: 'capstone-check-ch01-object',
    lineId: 'capstone-line-ch01-03',
    prompt: 'What is this?',
    choices: ['A book', 'A notebook', 'Homework'],
    answer: 'A book',
    support: 'これはほんです means "This is a book."',
  },
  {
    id: 'capstone-check-ch01-bathroom',
    lineId: 'capstone-line-ch01-11',
    prompt: 'Where is the bathroom?',
    choices: ['Over there', 'Here', 'In the classroom'],
    answer: 'Over there',
    support: 'あそこ points to a place over there.',
  },
  {
    id: 'capstone-check-ch02-owner',
    lineId: 'capstone-line-ch02-01',
    prompt: 'Whose book is it?',
    choices: ['The speaker’s book', 'The older sister’s book', 'The teacher’s book'],
    answer: 'The speaker’s book',
    support: 'わたしのほん means "my book."',
  },
  {
    id: 'capstone-check-ch02-past-study',
    lineId: 'capstone-line-ch02-05',
    prompt: 'What happened yesterday?',
    choices: ['The speaker studied Japanese at home', 'The speaker went to school', 'The speaker drank coffee'],
    answer: 'The speaker studied Japanese at home',
    support: 'きのう and べんきょうしました show a past study action.',
  },
  {
    id: 'capstone-check-ch02-drink',
    lineId: 'capstone-line-ch02-07',
    prompt: 'What does the speaker not drink today?',
    choices: ['Coffee', 'Water', 'Tea'],
    answer: 'Coffee',
    support: 'コーヒーをのみません means "I do not drink coffee."',
  },
  {
    id: 'capstone-check-ch02-request',
    lineId: 'capstone-line-ch02-10',
    prompt: 'What does the speaker ask someone to do?',
    choices: ['Read slowly', 'Wait at the station', 'Open the window'],
    answer: 'Read slowly',
    support: 'ゆっくりよんでください means "Please read slowly."',
  },
  {
    id: 'capstone-check-ch03-time',
    lineId: 'capstone-line-ch03-02',
    prompt: 'What time is it?',
    choices: ['8 AM', '7 PM', '9 PM'],
    answer: '8 AM',
    support: 'ごぜんはちじです means "It is 8 AM."',
  },
  {
    id: 'capstone-check-ch03-shopping-day',
    lineId: 'capstone-line-ch03-03',
    prompt: 'When does the speaker go shopping?',
    choices: ['Tuesday', 'Saturday', 'Sunday'],
    answer: 'Tuesday',
    support: 'かようびに marks Tuesday as the day.',
  },
  {
    id: 'capstone-check-ch03-request',
    lineId: 'capstone-line-ch03-05',
    prompt: 'What does the speaker ask for?',
    choices: ['A rice ball', 'A book', 'A ticket'],
    answer: 'A rice ball',
    support: 'おにぎりをください means "Please give me a rice ball."',
  },
  {
    id: 'capstone-check-ch03-location',
    lineId: 'capstone-line-ch03-11',
    prompt: 'Where is the convenience store?',
    choices: ['Next to the station', 'Near the river', 'At the intersection'],
    answer: 'Next to the station',
    support: 'えきのとなり means "next to the station."',
  },
  {
    id: 'capstone-check-ch04-plan',
    lineId: 'capstone-line-ch04-01',
    prompt: 'Where are they invited to go together?',
    choices: ['The movie theater', 'The library', 'The supermarket'],
    answer: 'The movie theater',
    support: 'えいがかんにいきますか asks about going to the movie theater.',
  },
  {
    id: 'capstone-check-ch04-time',
    lineId: 'capstone-line-ch04-04',
    prompt: 'What time will they meet?',
    choices: ['Six o’clock', 'Eight o’clock', 'Nine o’clock'],
    answer: 'Six o’clock',
    support: 'ろくじにあいましょう means "Let’s meet at six."',
  },
  {
    id: 'capstone-check-ch04-place',
    lineId: 'capstone-line-ch04-06',
    prompt: 'Where will they meet?',
    choices: ['At the station', 'At the park', 'At home'],
    answer: 'At the station',
    support: 'えきであいます means "We will meet at the station."',
  },
  {
    id: 'capstone-check-ch04-waiting',
    lineId: 'capstone-line-ch04-09',
    prompt: 'What is the speaker doing at the station?',
    choices: ['Waiting', 'Buying snacks', 'Reading a book'],
    answer: 'Waiting',
    support: 'まっています means "am waiting."',
  },
  {
    id: 'capstone-check-ch05-date',
    lineId: 'capstone-line-ch05-02',
    prompt: 'When will they meet?',
    choices: ['April third at six', 'May eighth at nine', 'June tenth at six'],
    answer: 'April third at six',
    support: 'しがつみっかのろくじ means "six on April third."',
  },
  {
    id: 'capstone-check-ch05-time-range',
    lineId: 'capstone-line-ch05-04',
    prompt: 'What is the time range?',
    choices: ['Nine to five', 'Twelve to one', 'Six to seven'],
    answer: 'Nine to five',
    support: 'くじからごじまで means "from nine to five."',
  },
  {
    id: 'capstone-check-ch05-quantity',
    lineId: 'capstone-line-ch05-07',
    prompt: 'How many apples will the speaker buy?',
    choices: ['Two', 'Three', 'Five'],
    answer: 'Two',
    support: 'ふたつ means "two" for this counter pattern.',
  },
  {
    id: 'capstone-check-ch05-price',
    lineId: 'capstone-line-ch05-09',
    prompt: 'How much are the apples?',
    choices: ['300 yen', '100 yen', '500 yen'],
    answer: '300 yen',
    support: 'さんびゃくえん means "300 yen."',
  },
  {
    id: 'capstone-check-ch06-availability',
    lineId: 'capstone-line-ch06-02',
    prompt: 'Does the store have water?',
    choices: ['Yes', 'No', 'The story does not say'],
    answer: 'Yes',
    support: 'はい、あります means "Yes, we do."',
  },
  {
    id: 'capstone-check-ch06-sequence',
    lineId: 'capstone-line-ch06-07',
    prompt: 'What happens after buying apples?',
    choices: ['The speaker goes home', 'The speaker studies Japanese', 'The speaker waits at the station'],
    answer: 'The speaker goes home',
    support: 'それからうちにいきます means "and then go home."',
  },
  {
    id: 'capstone-check-ch06-progressive',
    lineId: 'capstone-line-ch06-08',
    prompt: 'What is the speaker doing now?',
    choices: ['Buying bread', 'Drinking coffee', 'Reading a book'],
    answer: 'Buying bread',
    support: 'かっています means "am buying."',
  },
  {
    id: 'capstone-check-ch06-description',
    lineId: 'capstone-line-ch06-10',
    prompt: 'What does the speaker say about the bread?',
    choices: ['It is not tasty', 'It is expensive', 'It is big'],
    answer: 'It is not tasty',
    support: 'おいしくないです means "is not tasty."',
  },
  {
    id: 'capstone-check-ch07-comparison',
    lineId: 'capstone-line-ch07-03',
    prompt: 'Which is cheaper?',
    choices: ['The cafe', 'The restaurant', 'The library'],
    answer: 'The cafe',
    support: 'カフェのほうがやすいです means "the cafe is cheaper."',
  },
  {
    id: 'capstone-check-ch07-superlative',
    lineId: 'capstone-line-ch07-05',
    prompt: 'Which place is the quietest?',
    choices: ['The library', 'The station', 'The cafe'],
    answer: 'The library',
    support: 'としょかんがいちばんしずかです means "the library is the quietest."',
  },
  {
    id: 'capstone-check-ch07-frequency',
    lineId: 'capstone-line-ch07-08',
    prompt: 'What does the speaker not do very often?',
    choices: ['Watch movies', 'Drink coffee', 'Study at the library'],
    answer: 'Watch movies',
    support: 'あまりえいがをみません means "I do not watch movies very often."',
  },
  {
    id: 'capstone-check-ch07-reason',
    lineId: 'capstone-line-ch07-11',
    prompt: 'Why does the speaker not go to this restaurant?',
    choices: ['Because it is expensive', 'Because it is quiet', 'Because it is far'],
    answer: 'Because it is expensive',
    support: 'たかいですから gives the reason: because it is expensive.',
  },
  {
    id: 'capstone-check-ch08-want-place',
    lineId: 'capstone-line-ch08-01',
    prompt: 'Where does the speaker want to go on Saturday?',
    choices: ['The movie theater', 'The library', 'A cafe'],
    answer: 'The movie theater',
    support: 'どようびにえいがかんにいきたいです means "I want to go to the movie theater on Saturday."',
  },
  {
    id: 'capstone-check-ch08-object-desire',
    lineId: 'capstone-line-ch08-03',
    prompt: 'What does the speaker want?',
    choices: ['A new camera', 'A new bicycle', 'A new book'],
    answer: 'A new camera',
    support: 'あたらしいカメラがほしいです means "I want a new camera."',
  },
  {
    id: 'capstone-check-ch08-ability',
    lineId: 'capstone-line-ch08-05',
    prompt: 'What can the speaker do?',
    choices: ['Read Japanese', 'Write kanji', 'Speak English'],
    answer: 'Read Japanese',
    support: 'にほんごをよむことができます means "I can read Japanese."',
  },
  {
    id: 'capstone-check-ch08-experience',
    lineId: 'capstone-line-ch08-07',
    prompt: 'What has the speaker eaten before?',
    choices: ['Sushi', 'Ramen', 'Cake'],
    answer: 'Sushi',
    support: 'すしをたべたことがあります means "I have eaten sushi before."',
  },
  {
    id: 'capstone-check-ch09-choice',
    lineId: 'capstone-line-ch09-03',
    prompt: 'Which shoes are good for the speaker?',
    choices: ['White shoes', 'Red shoes', 'Blue shoes'],
    answer: 'White shoes',
    support: 'しろいくつがいいです means "The white shoes are good for me."',
  },
  {
    id: 'capstone-check-ch09-health',
    lineId: 'capstone-line-ch09-05',
    prompt: 'What is wrong today?',
    choices: ['The speaker has a headache', 'The speaker has a fever', 'The speaker has a stomachache'],
    answer: 'The speaker has a headache',
    support: 'あたまがいたいです means "My head hurts."',
  },
  {
    id: 'capstone-check-ch09-weather',
    lineId: 'capstone-line-ch09-06',
    prompt: 'Why does the speaker drink water?',
    choices: ['Because it is hot', 'Because it is raining', 'Because it is cold'],
    answer: 'Because it is hot',
    support: 'あついですから gives the reason: because it is hot.',
  },
  {
    id: 'capstone-check-ch09-delay',
    lineId: 'capstone-line-ch09-09',
    prompt: 'What problem happened?',
    choices: ['The train is delayed', 'The bus is delayed', 'The station is closed'],
    answer: 'The train is delayed',
    support: 'でんしゃがおくれます means "The train is delayed."',
  },
  {
    id: 'capstone-check-ch10-before-after',
    lineId: 'capstone-line-ch10-02',
    prompt: 'When does the speaker go to a cafe?',
    choices: ['After school', 'Before school', 'After work'],
    answer: 'After school',
    support: 'がっこうのあとで means "after school."',
  },
  {
    id: 'capstone-check-ch10-plain-state',
    lineId: 'capstone-line-ch10-04',
    prompt: 'What does the plain-style line mean?',
    choices: ['I am not feeling well today', 'I am okay today', 'It is not hot today'],
    answer: 'I am not feeling well today',
    support: 'きょうはげんきじゃない is plain style for "I am not feeling well today."',
  },
  {
    id: 'capstone-check-ch10-plain-action',
    lineId: 'capstone-line-ch10-05',
    prompt: 'What action does the plain-style line describe?',
    choices: ['Reading a book at home', 'Going to a cafe tomorrow', 'Watching a movie today'],
    answer: 'Reading a book at home',
    support: 'うちでほんをよむ means "I read a book at home."',
  },
  {
    id: 'capstone-check-ch10-listing',
    lineId: 'capstone-line-ch10-10',
    prompt: 'What does や signal in this line?',
    choices: ['An open list like "things like bread and cake"', 'An exact list of only two items', 'A reason'],
    answer: 'An open list like "things like bread and cake"',
    support: 'パンやケーキ means "things like bread and cake," not necessarily only those two items.',
  },
];

export const capstoneStories: CapstoneStory[] = [
  {
    id: 'capstone-story-ch01-first-day',
    chapterId: 'chapter-core-01',
    title: 'First day basics',
    summary:
      'A chapter closeout for first-day identity, classroom objects, simple movement, existence, preferences, and location answers.',
    estimatedMinutes: 5,
    sourcePackIds: [1, 2, 3, 4, 5],
    lineIds: [
      'capstone-line-ch01-01',
      'capstone-line-ch01-02',
      'capstone-line-ch01-03',
      'capstone-line-ch01-04',
      'capstone-line-ch01-05',
      'capstone-line-ch01-06',
      'capstone-line-ch01-07',
      'capstone-line-ch01-08',
      'capstone-line-ch01-09',
      'capstone-line-ch01-10',
      'capstone-line-ch01-11',
    ],
    checkIds: [
      'capstone-check-ch01-identity',
      'capstone-check-ch01-object',
      'capstone-check-ch01-place',
      'capstone-check-ch01-bathroom',
    ],
  },
  {
    id: 'capstone-story-ch02-home-routine',
    chapterId: 'chapter-core-02',
    title: 'Home and daily routine',
    summary:
      'A chapter closeout for possession, daily actions, simple descriptions, past actions, and polite requests.',
    estimatedMinutes: 5,
    sourcePackIds: [6, 7, 8, 9, 10],
    lineIds: [
      'capstone-line-ch02-01',
      'capstone-line-ch02-02',
      'capstone-line-ch02-03',
      'capstone-line-ch02-04',
      'capstone-line-ch02-05',
      'capstone-line-ch02-06',
      'capstone-line-ch02-07',
      'capstone-line-ch02-08',
      'capstone-line-ch02-09',
      'capstone-line-ch02-10',
    ],
    checkIds: [
      'capstone-check-ch02-owner',
      'capstone-check-ch02-past-study',
      'capstone-check-ch02-drink',
      'capstone-check-ch02-request',
    ],
  },
  {
    id: 'capstone-story-ch03-errand-run',
    chapterId: 'chapter-core-03',
    title: 'Errand run through town',
    summary:
      'A chapter closeout for time, weekday plans, shopping requests, transport, destinations, and simple directions.',
    estimatedMinutes: 5,
    sourcePackIds: [11, 12, 13, 14, 15],
    lineIds: [
      'capstone-line-ch03-01',
      'capstone-line-ch03-02',
      'capstone-line-ch03-03',
      'capstone-line-ch03-04',
      'capstone-line-ch03-05',
      'capstone-line-ch03-06',
      'capstone-line-ch03-07',
      'capstone-line-ch03-08',
      'capstone-line-ch03-09',
      'capstone-line-ch03-10',
      'capstone-line-ch03-11',
    ],
    checkIds: [
      'capstone-check-ch03-time',
      'capstone-check-ch03-shopping-day',
      'capstone-check-ch03-request',
      'capstone-check-ch03-location',
    ],
  },
  {
    id: 'capstone-story-ch04-meetup-plan',
    chapterId: 'chapter-core-04',
    title: 'Meetup plan',
    summary:
      'A chapter closeout for invitations, meeting places, arrival and waiting status, suggestions, and proposals.',
    estimatedMinutes: 5,
    sourcePackIds: [16, 17, 18, 19, 20],
    lineIds: [
      'capstone-line-ch04-01',
      'capstone-line-ch04-02',
      'capstone-line-ch04-03',
      'capstone-line-ch04-04',
      'capstone-line-ch04-05',
      'capstone-line-ch04-06',
      'capstone-line-ch04-07',
      'capstone-line-ch04-08',
      'capstone-line-ch04-09',
      'capstone-line-ch04-10',
      'capstone-line-ch04-11',
    ],
    checkIds: [
      'capstone-check-ch04-plan',
      'capstone-check-ch04-time',
      'capstone-check-ch04-place',
      'capstone-check-ch04-waiting',
    ],
  },
  {
    id: 'capstone-story-ch05-calendar-outing',
    chapterId: 'chapter-core-05',
    title: 'A small outing on the calendar',
    summary:
      'A chapter closeout for time ranges, dates, appointment lines, quantities, and simple prices.',
    estimatedMinutes: 5,
    sourcePackIds: [21, 22, 23, 24, 25],
    lineIds: [
      'capstone-line-ch05-01',
      'capstone-line-ch05-02',
      'capstone-line-ch05-03',
      'capstone-line-ch05-04',
      'capstone-line-ch05-05',
      'capstone-line-ch05-06',
      'capstone-line-ch05-07',
      'capstone-line-ch05-08',
      'capstone-line-ch05-09',
      'capstone-line-ch05-10',
    ],
    checkIds: [
      'capstone-check-ch05-date',
      'capstone-check-ch05-time-range',
      'capstone-check-ch05-quantity',
      'capstone-check-ch05-price',
    ],
  },
  {
    id: 'capstone-story-ch06-store-follow-up',
    chapterId: 'chapter-core-06',
    title: 'Store request and follow-up',
    summary:
      'A chapter closeout for availability, te-form requests, action sequence, ongoing state, and adjective negatives.',
    estimatedMinutes: 5,
    sourcePackIds: [26, 27, 28, 29, 30],
    lineIds: [
      'capstone-line-ch06-01',
      'capstone-line-ch06-02',
      'capstone-line-ch06-03',
      'capstone-line-ch06-04',
      'capstone-line-ch06-05',
      'capstone-line-ch06-06',
      'capstone-line-ch06-07',
      'capstone-line-ch06-08',
      'capstone-line-ch06-09',
      'capstone-line-ch06-10',
      'capstone-line-ch06-11',
    ],
    checkIds: [
      'capstone-check-ch06-availability',
      'capstone-check-ch06-sequence',
      'capstone-check-ch06-progressive',
      'capstone-check-ch06-description',
    ],
  },
  {
    id: 'capstone-story-ch07-choosing-where-to-go',
    chapterId: 'chapter-core-07',
    title: 'Choosing where to go',
    summary:
      'A chapter closeout for adjective past, comparisons, superlatives, frequency, and short reasons.',
    estimatedMinutes: 5,
    sourcePackIds: [31, 32, 33, 34, 35],
    lineIds: [
      'capstone-line-ch07-01',
      'capstone-line-ch07-02',
      'capstone-line-ch07-03',
      'capstone-line-ch07-04',
      'capstone-line-ch07-05',
      'capstone-line-ch07-06',
      'capstone-line-ch07-07',
      'capstone-line-ch07-08',
      'capstone-line-ch07-09',
      'capstone-line-ch07-10',
      'capstone-line-ch07-11',
    ],
    checkIds: [
      'capstone-check-ch07-comparison',
      'capstone-check-ch07-superlative',
      'capstone-check-ch07-frequency',
      'capstone-check-ch07-reason',
    ],
  },
  {
    id: 'capstone-story-ch08-things-to-try',
    chapterId: 'chapter-core-08',
    title: 'Things to try',
    summary:
      'A chapter closeout for wanted activities, wanted objects, ability, prior experience, companions, and travel methods.',
    estimatedMinutes: 5,
    sourcePackIds: [36, 37, 38, 39, 40],
    lineIds: [
      'capstone-line-ch08-01',
      'capstone-line-ch08-02',
      'capstone-line-ch08-03',
      'capstone-line-ch08-04',
      'capstone-line-ch08-05',
      'capstone-line-ch08-06',
      'capstone-line-ch08-07',
      'capstone-line-ch08-08',
      'capstone-line-ch08-09',
      'capstone-line-ch08-10',
      'capstone-line-ch08-11',
    ],
    checkIds: [
      'capstone-check-ch08-want-place',
      'capstone-check-ch08-object-desire',
      'capstone-check-ch08-ability',
      'capstone-check-ch08-experience',
    ],
  },
  {
    id: 'capstone-story-ch09-travel-problem',
    chapterId: 'chapter-core-09',
    title: 'A small travel problem',
    summary:
      'A chapter closeout for choices, health and weather context, travel steps, delays, and low-stakes contact lines.',
    estimatedMinutes: 5,
    sourcePackIds: [41, 42, 43, 44, 45],
    lineIds: [
      'capstone-line-ch09-01',
      'capstone-line-ch09-02',
      'capstone-line-ch09-03',
      'capstone-line-ch09-04',
      'capstone-line-ch09-05',
      'capstone-line-ch09-06',
      'capstone-line-ch09-07',
      'capstone-line-ch09-08',
      'capstone-line-ch09-09',
      'capstone-line-ch09-10',
      'capstone-line-ch09-11',
    ],
    checkIds: [
      'capstone-check-ch09-choice',
      'capstone-check-ch09-health',
      'capstone-check-ch09-weather',
      'capstone-check-ch09-delay',
    ],
  },
  {
    id: 'capstone-story-ch10-late-n5-flow',
    chapterId: 'chapter-core-10',
    title: 'Late N5 flow wrap-up',
    summary:
      'A chapter closeout for before/after timing, plain-style recognition, connected flow, contrast, and flexible listing.',
    estimatedMinutes: 5,
    sourcePackIds: [46, 47, 48, 49, 50],
    lineIds: [
      'capstone-line-ch10-01',
      'capstone-line-ch10-02',
      'capstone-line-ch10-03',
      'capstone-line-ch10-04',
      'capstone-line-ch10-05',
      'capstone-line-ch10-06',
      'capstone-line-ch10-07',
      'capstone-line-ch10-08',
      'capstone-line-ch10-09',
      'capstone-line-ch10-10',
      'capstone-line-ch10-11',
    ],
    checkIds: [
      'capstone-check-ch10-before-after',
      'capstone-check-ch10-plain-state',
      'capstone-check-ch10-plain-action',
      'capstone-check-ch10-listing',
    ],
  },
];
