import type { ExampleSentence } from '../lib/content/types';

export const exampleSentences = [
  {
    id: 'ex-colin-desu',
    japanese: 'わたしはコリンです。',
    reading: 'わたしはコリンです。',
    english: 'I am Colin.',
    grammarTags: ['topic', 'copula', 'self-introduction'],
    vocabTags: ['self', 'name'],
  },
  {
    id: 'ex-student-desu',
    japanese: 'わたしはがくせいです。',
    reading: 'わたしはがくせいです。',
    english: 'I am a student.',
    grammarTags: ['topic', 'copula', 'identity'],
    vocabTags: ['self', 'school'],
  },
  {
    id: 'ex-teacher-question',
    japanese: 'せんせいですか。',
    reading: 'せんせいですか。',
    english: 'Are you a teacher?',
    grammarTags: ['copula', 'question'],
    vocabTags: ['school', 'role'],
  },
  {
    id: 'ex-company-worker',
    japanese: 'ともだちはかいしゃいんです。',
    reading: 'ともだちはかいしゃいんです。',
    english: 'My friend is an office worker.',
    grammarTags: ['topic', 'copula', 'identity'],
    vocabTags: ['people', 'work'],
  },
  {
    id: 'ex-study-home',
    japanese: 'うちでにほんごをべんきょうします。',
    reading: 'うちでにほんごをべんきょうします。',
    english: 'I study Japanese at home.',
    grammarTags: ['location', 'object', 'daily-routine'],
    vocabTags: ['home', 'study'],
  },
  {
    id: 'ex-coffee-cafe',
    japanese: 'カフェでコーヒーをのみます。',
    reading: 'カフェでコーヒーをのみます。',
    english: 'I drink coffee at a cafe.',
    grammarTags: ['location', 'object', 'daily-routine'],
    vocabTags: ['cafe', 'drink'],
  },
  {
    id: 'ex-read-library',
    japanese: 'としょかんでほんをよみます。',
    reading: 'としょかんでほんをよみます。',
    english: 'I read a book at the library.',
    grammarTags: ['location', 'object', 'daily-routine'],
    vocabTags: ['library', 'reading'],
  },
  {
    id: 'ex-classroom-study',
    japanese: 'きょうしつでべんきょうします。',
    reading: 'きょうしつでべんきょうします。',
    english: 'I study in the classroom.',
    grammarTags: ['location', 'daily-routine'],
    vocabTags: ['school', 'study'],
  },
  {
    id: 'ex-kore-hon',
    japanese: 'これはほんです。',
    reading: 'これはほんです。',
    english: 'This is a book.',
    grammarTags: ['demonstrative', 'copula', 'identity'],
    vocabTags: ['classroom', 'book'],
  },
  {
    id: 'ex-kore-nan',
    japanese: 'これはなんですか。',
    reading: 'これはなんですか。',
    english: 'What is this?',
    grammarTags: ['demonstrative', 'question', 'copula'],
    vocabTags: ['classroom', 'question'],
  },
  {
    id: 'ex-sore-shukudai',
    japanese: 'それはしゅくだいです。',
    reading: 'それはしゅくだいです。',
    english: 'That is homework.',
    grammarTags: ['demonstrative', 'copula', 'identity'],
    vocabTags: ['classroom', 'study'],
  },
  {
    id: 'ex-kore-eigo-hon',
    japanese: 'これはえいごのほんです。',
    reading: 'これはえいごのほんです。',
    english: 'This is an English book.',
    grammarTags: ['demonstrative', 'copula', 'noun-linking'],
    vocabTags: ['classroom', 'book', 'study'],
  },
  {
    id: 'ex-doko-ikimasu',
    japanese: 'どこにいきますか。',
    reading: 'どこにいきますか。',
    english: 'Where do you go?',
    grammarTags: ['question', 'destination', 'movement'],
    vocabTags: ['question', 'daily-routine'],
  },
  {
    id: 'ex-mainichi-gakkou',
    japanese: 'まいにちがっこうにいきます。',
    reading: 'まいにちがっこうにいきます。',
    english: 'I go to school every day.',
    grammarTags: ['destination', 'movement', 'daily-routine'],
    vocabTags: ['school', 'time', 'daily-routine'],
  },
  {
    id: 'ex-kyou-toshokan',
    japanese: 'きょうとしょかんにいきます。',
    reading: 'きょうとしょかんにいきます。',
    english: 'I go to the library today.',
    grammarTags: ['destination', 'movement', 'daily-routine'],
    vocabTags: ['study', 'time', 'library'],
  },
  {
    id: 'ex-ima-kyoushitsu',
    japanese: 'いまきょうしつにいきます。',
    reading: 'いまきょうしつにいきます。',
    english: 'I am going to the classroom now.',
    grammarTags: ['destination', 'movement', 'daily-routine'],
    vocabTags: ['school', 'time', 'classroom'],
  },
  {
    id: 'ex-sensei-doko',
    japanese: 'せんせいはどこにいきますか。',
    reading: 'せんせいはどこにいきますか。',
    english: 'Where does the teacher go?',
    grammarTags: ['topic', 'question', 'destination'],
    vocabTags: ['school', 'question'],
  },
  {
    id: 'ex-tomodachi-gakkou',
    japanese: 'ともだちはがっこうにいきます。',
    reading: 'ともだちはがっこうにいきます。',
    english: 'My friend goes to school.',
    grammarTags: ['topic', 'destination', 'movement'],
    vocabTags: ['people', 'school'],
  },
  {
    id: 'ex-neko-heya-imasu',
    japanese: 'ねこはへやにいます。',
    reading: 'ねこはへやにいます。',
    english: 'The cat is in the room.',
    grammarTags: ['existence', 'location', 'animate'],
    vocabTags: ['animal', 'room'],
  },
  {
    id: 'ex-sensei-kyoushitsu-imasu',
    japanese: 'せんせいはきょうしつにいます。',
    reading: 'せんせいはきょうしつにいます。',
    english: 'The teacher is in the classroom.',
    grammarTags: ['existence', 'location', 'animate'],
    vocabTags: ['school', 'role', 'classroom'],
  },
  {
    id: 'ex-inu-uchi-imasu',
    japanese: 'いぬはうちにいます。',
    reading: 'いぬはうちにいます。',
    english: 'The dog is at home.',
    grammarTags: ['existence', 'location', 'animate'],
    vocabTags: ['animal', 'home'],
  },
  {
    id: 'ex-hon-toshokan-arimasu',
    japanese: 'ほんはとしょかんにあります。',
    reading: 'ほんはとしょかんにあります。',
    english: 'The book is in the library.',
    grammarTags: ['existence', 'location', 'inanimate'],
    vocabTags: ['book', 'library'],
  },
  {
    id: 'ex-hon-tsukue-ue',
    japanese: 'ほんはつくえのうえにあります。',
    reading: 'ほんはつくえのうえにあります。',
    english: 'The book is on the desk.',
    grammarTags: ['existence', 'position', 'location'],
    vocabTags: ['book', 'desk'],
  },
  {
    id: 'ex-kaban-isu-shita',
    japanese: 'かばんはいすのしたにあります。',
    reading: 'かばんはいすのしたにあります。',
    english: 'The bag is under the chair.',
    grammarTags: ['existence', 'position', 'location'],
    vocabTags: ['bag', 'chair'],
  },
  {
    id: 'ex-hon-kaban-naka',
    japanese: 'ほんはかばんのなかにあります。',
    reading: 'ほんはかばんのなかにあります。',
    english: 'The book is inside the bag.',
    grammarTags: ['existence', 'position', 'location'],
    vocabTags: ['book', 'bag'],
  },
  {
    id: 'ex-neko-tsukue-shita',
    japanese: 'ねこはつくえのしたにいます。',
    reading: 'ねこはつくえのしたにいます。',
    english: 'The cat is under the desk.',
    grammarTags: ['existence', 'position', 'location'],
    vocabTags: ['animal', 'desk'],
  },
  {
    id: 'ex-watashi-sushi-suki',
    japanese: 'わたしはすしがすきです。',
    reading: 'わたしはすしがすきです。',
    english: 'I like sushi.',
    grammarTags: ['preference', 'particle-ga', 'daily-conversation'],
    vocabTags: ['food', 'preference'],
  },
  {
    id: 'ex-tomodachi-raamen-suki',
    japanese: 'ともだちはラーメンがすきです。',
    reading: 'ともだちはラーメンがすきです。',
    english: 'My friend likes ramen.',
    grammarTags: ['preference', 'particle-ga', 'daily-conversation'],
    vocabTags: ['food', 'people'],
  },
  {
    id: 'ex-watashi-koohii-kirai',
    japanese: 'わたしはコーヒーがきらいです。',
    reading: 'わたしはコーヒーがきらいです。',
    english: 'I dislike coffee.',
    grammarTags: ['preference', 'particle-ga', 'daily-conversation'],
    vocabTags: ['drink', 'preference'],
  },
  {
    id: 'ex-ongaku-suki',
    japanese: 'おんがくがすきです。',
    reading: 'おんがくがすきです。',
    english: 'I like music.',
    grammarTags: ['preference', 'particle-ga', 'daily-conversation'],
    vocabTags: ['hobby', 'preference'],
  },
  {
    id: 'ex-anime-suki',
    japanese: 'アニメがすきです。',
    reading: 'アニメがすきです。',
    english: 'I like anime.',
    grammarTags: ['preference', 'particle-ga', 'daily-conversation'],
    vocabTags: ['hobby', 'preference'],
  },
  {
    id: 'ex-sakkaa-kirai',
    japanese: 'サッカーがきらいです。',
    reading: 'サッカーがきらいです。',
    english: 'I dislike soccer.',
    grammarTags: ['preference', 'particle-ga', 'daily-conversation'],
    vocabTags: ['sport', 'preference'],
  },
  {
    id: 'ex-nani-suki',
    japanese: 'なにがすきですか。',
    reading: 'なにがすきですか。',
    english: 'What do you like?',
    grammarTags: ['question', 'preference', 'particle-ga'],
    vocabTags: ['question', 'preference'],
  },
  {
    id: 'ex-tabemono-nani-suki',
    japanese: 'たべものはなにがすきですか。',
    reading: 'たべものはなにがすきですか。',
    english: 'What food do you like?',
    grammarTags: ['question', 'preference', 'topic'],
    vocabTags: ['food', 'question'],
  },
  {
    id: 'ex-cha-suki',
    japanese: 'ちゃがすきです。',
    reading: 'ちゃがすきです。',
    english: 'I like tea.',
    grammarTags: ['preference', 'particle-ga', 'daily-conversation'],
    vocabTags: ['drink', 'preference'],
  },
  {
    id: 'ex-eiga-suki-ka',
    japanese: 'えいががすきですか。',
    reading: 'えいががすきですか。',
    english: 'Do you like movies?',
    grammarTags: ['question', 'preference', 'particle-ga'],
    vocabTags: ['hobby', 'question'],
  },
  {
    id: 'ex-nomimono-nani-suki',
    japanese: 'のみものはなにがすきですか。',
    reading: 'のみものはなにがすきですか。',
    english: 'What drink do you like?',
    grammarTags: ['question', 'preference', 'topic'],
    vocabTags: ['drink', 'question'],
  },
  {
    id: 'ex-toire-doko',
    japanese: 'トイレはどこですか。',
    reading: 'トイレはどこですか。',
    english: 'Where is the bathroom?',
    grammarTags: ['question', 'location', 'topic'],
    vocabTags: ['place', 'question'],
  },
  {
    id: 'ex-kagi-doko',
    japanese: 'かぎはどこですか。',
    reading: 'かぎはどこですか。',
    english: 'Where is the key?',
    grammarTags: ['question', 'location', 'topic'],
    vocabTags: ['object', 'question'],
  },
  {
    id: 'ex-sensei-doko-desu',
    japanese: 'せんせいはどこですか。',
    reading: 'せんせいはどこですか。',
    english: 'Where is the teacher?',
    grammarTags: ['question', 'location', 'topic'],
    vocabTags: ['school', 'question'],
  },
  {
    id: 'ex-jitensha-doko',
    japanese: 'じてんしゃはどこですか。',
    reading: 'じてんしゃはどこですか。',
    english: 'Where is the bicycle?',
    grammarTags: ['question', 'location', 'topic'],
    vocabTags: ['daily-routine', 'question'],
  },
  {
    id: 'ex-toire-asoko',
    japanese: 'トイレはあそこです。',
    reading: 'トイレはあそこです。',
    english: 'The bathroom is over there.',
    grammarTags: ['location', 'answer-patterns', 'topic'],
    vocabTags: ['place', 'location'],
  },
  {
    id: 'ex-jimusho-koko',
    japanese: 'じむしょはここです。',
    reading: 'じむしょはここです。',
    english: 'The office is here.',
    grammarTags: ['location', 'answer-patterns', 'topic'],
    vocabTags: ['place', 'location'],
  },
  {
    id: 'ex-genkan-soko',
    japanese: 'げんかんはそこです。',
    reading: 'げんかんはそこです。',
    english: 'The entrance is there.',
    grammarTags: ['location', 'answer-patterns', 'topic'],
    vocabTags: ['place', 'location'],
  },
  {
    id: 'ex-kagi-tsukue-ue-arimasu',
    japanese: 'かぎはつくえのうえにあります。',
    reading: 'かぎはつくえのうえにあります。',
    english: 'The key is on the desk.',
    grammarTags: ['location', 'existence', 'position'],
    vocabTags: ['object', 'desk'],
  },
  {
    id: 'ex-kutsu-genkan-arimasu',
    japanese: 'くつはげんかんにあります。',
    reading: 'くつはげんかんにあります。',
    english: 'The shoes are at the entrance.',
    grammarTags: ['location', 'existence', 'topic'],
    vocabTags: ['daily-routine', 'place'],
  },
  {
    id: 'ex-sensei-jimusho-imasu',
    japanese: 'せんせいはじむしょにいます。',
    reading: 'せんせいはじむしょにいます。',
    english: 'The teacher is in the office.',
    grammarTags: ['location', 'existence', 'animate'],
    vocabTags: ['school', 'place'],
  },
  {
    id: 'ex-kore-watashi-no-hon',
    japanese: 'これはわたしのほんです。',
    reading: 'これはわたしのほんです。',
    english: 'This is my book.',
    grammarTags: ['possession', 'noun-linking', 'identity'],
    vocabTags: ['self', 'book'],
  },
  {
    id: 'ex-sore-ane-no-kaban',
    japanese: 'それはあねのかばんです。',
    reading: 'それはあねのかばんです。',
    english: "That is my older sister's bag.",
    grammarTags: ['possession', 'noun-linking', 'identity'],
    vocabTags: ['family', 'object'],
  },
  {
    id: 'ex-kore-chichi-no-kamera',
    japanese: 'これはちちのカメラです。',
    reading: 'これはちちのカメラです。',
    english: "This is my father's camera.",
    grammarTags: ['possession', 'noun-linking', 'identity'],
    vocabTags: ['family', 'object'],
  },
  {
    id: 'ex-kore-kazoku-no-shashin',
    japanese: 'これはかぞくのしゃしんです。',
    reading: 'これはかぞくのしゃしんです。',
    english: 'This is a family photo.',
    grammarTags: ['possession', 'noun-linking', 'identity'],
    vocabTags: ['family', 'object'],
  },
  {
    id: 'ex-sore-haha-no-kasa',
    japanese: 'それはははのかさです。',
    reading: 'それはははのかさです。',
    english: "That is my mother's umbrella.",
    grammarTags: ['possession', 'noun-linking', 'identity'],
    vocabTags: ['family', 'object'],
  },
  {
    id: 'ex-kore-otouto-no-hon',
    japanese: 'これはおとうとのほんです。',
    reading: 'これはおとうとのほんです。',
    english: "This is my younger brother's book.",
    grammarTags: ['possession', 'noun-linking', 'identity'],
    vocabTags: ['family', 'book'],
  },
  {
    id: 'ex-sore-imouto-no-keitai',
    japanese: 'それはいもうとのけいたいです。',
    reading: 'それはいもうとのけいたいです。',
    english: "That is my younger sister's phone.",
    grammarTags: ['possession', 'noun-linking', 'identity'],
    vocabTags: ['family', 'object'],
  },
  {
    id: 'ex-ani-no-kasa',
    japanese: 'あにのかさです。',
    reading: 'あにのかさです。',
    english: "It is my older brother's umbrella.",
    grammarTags: ['possession', 'noun-linking', 'identity'],
    vocabTags: ['family', 'object'],
  },
  {
    id: 'ex-watashi-no-kamera',
    japanese: 'わたしのカメラです。',
    reading: 'わたしのカメラです。',
    english: 'It is my camera.',
    grammarTags: ['possession', 'noun-linking', 'identity'],
    vocabTags: ['self', 'object'],
  },
  {
    id: 'ex-ane-no-shashin',
    japanese: 'あねのしゃしんです。',
    reading: 'あねのしゃしんです。',
    english: "It is my older sister's photo.",
    grammarTags: ['possession', 'noun-linking', 'identity'],
    vocabTags: ['family', 'object'],
  },
  {
    id: 'ex-asa-pan-tabemasu',
    japanese: 'あさパンをたべます。',
    reading: 'あさパンをたべます。',
    english: 'I eat bread in the morning.',
    grammarTags: ['daily-routine', 'time', 'verb-forms'],
    vocabTags: ['food', 'time'],
  },
  {
    id: 'ex-yoru-hon-yomimasu',
    japanese: 'よるほんをよみます。',
    reading: 'よるほんをよみます。',
    english: 'I read a book at night.',
    grammarTags: ['daily-routine', 'time', 'verb-forms'],
    vocabTags: ['book', 'time'],
  },
  {
    id: 'ex-uchi-terebi-mimasu',
    japanese: 'うちでテレビをみます。',
    reading: 'うちでテレビをみます。',
    english: 'I watch TV at home.',
    grammarTags: ['daily-routine', 'location', 'verb-forms'],
    vocabTags: ['home', 'object'],
  },
  {
    id: 'ex-kouen-ongaku-kikimasu',
    japanese: 'こうえんでおんがくをききます。',
    reading: 'こうえんでおんがくをききます。',
    english: 'I listen to music at the park.',
    grammarTags: ['daily-routine', 'location', 'verb-forms'],
    vocabTags: ['place', 'hobby'],
  },
  {
    id: 'ex-yoru-nihongo-benkyoushimasu',
    japanese: 'よるにほんごをべんきょうします。',
    reading: 'よるにほんごをべんきょうします。',
    english: 'I study Japanese at night.',
    grammarTags: ['daily-routine', 'time', 'verb-forms'],
    vocabTags: ['study', 'time'],
  },
  {
    id: 'ex-kyou-mizu-nomimasu',
    japanese: 'きょうみずをのみます。',
    reading: 'きょうみずをのみます。',
    english: 'I drink water today.',
    grammarTags: ['daily-routine', 'time', 'verb-forms'],
    vocabTags: ['drink', 'time'],
  },
  {
    id: 'ex-kyou-koohii-nomimasen',
    japanese: 'きょうコーヒーをのみません。',
    reading: 'きょうコーヒーをのみません。',
    english: 'I do not drink coffee today.',
    grammarTags: ['daily-routine', 'time', 'verb-forms-negative'],
    vocabTags: ['drink', 'time'],
  },
  {
    id: 'ex-ashita-toshokan-ikimasen',
    japanese: 'あしたとしょかんにいきません。',
    reading: 'あしたとしょかんにいきません。',
    english: 'I am not going to the library tomorrow.',
    grammarTags: ['daily-routine', 'destination', 'verb-forms-negative'],
    vocabTags: ['place', 'time'],
  },
  {
    id: 'ex-uchi-terebi-mimasen',
    japanese: 'うちでテレビをみません。',
    reading: 'うちでテレビをみません。',
    english: 'I do not watch TV at home.',
    grammarTags: ['daily-routine', 'location', 'verb-forms-negative'],
    vocabTags: ['home', 'object'],
  },
  {
    id: 'ex-asa-pan-tabemasen',
    japanese: 'あさパンをたべません。',
    reading: 'あさパンをたべません。',
    english: 'I do not eat bread in the morning.',
    grammarTags: ['daily-routine', 'time', 'verb-forms-negative'],
    vocabTags: ['food', 'time'],
  },
  {
    id: 'ex-hon-omoshiroi',
    japanese: 'ほんはおもしろいです。',
    reading: 'ほんはおもしろいです。',
    english: 'The book is interesting.',
    grammarTags: ['adjectives', 'description', 'predicate'],
    vocabTags: ['book', 'adjectives'],
  },
  {
    id: 'ex-kaban-ookii',
    japanese: 'かばんはおおきいです。',
    reading: 'かばんはおおきいです。',
    english: 'The bag is big.',
    grammarTags: ['adjectives', 'description', 'predicate'],
    vocabTags: ['object', 'adjectives'],
  },
  {
    id: 'ex-heya-shizuka',
    japanese: 'へやはしずかです。',
    reading: 'へやはしずかです。',
    english: 'The room is quiet.',
    grammarTags: ['adjectives', 'description', 'predicate'],
    vocabTags: ['home', 'adjectives'],
  },
  {
    id: 'ex-kamera-atarashii',
    japanese: 'カメラはあたらしいです。',
    reading: 'カメラはあたらしいです。',
    english: 'The camera is new.',
    grammarTags: ['adjectives', 'description', 'predicate'],
    vocabTags: ['object', 'adjectives'],
  },
  {
    id: 'ex-hon-furui',
    japanese: 'ほんはふるいです。',
    reading: 'ほんはふるいです。',
    english: 'The book is old.',
    grammarTags: ['adjectives', 'description', 'predicate'],
    vocabTags: ['book', 'adjectives'],
  },
  {
    id: 'ex-atarashii-kamera-desu',
    japanese: 'あたらしいカメラです。',
    reading: 'あたらしいカメラです。',
    english: 'It is a new camera.',
    grammarTags: ['adjectives', 'noun-description', 'identity'],
    vocabTags: ['object', 'adjectives'],
  },
  {
    id: 'ex-shizuka-heya-desu',
    japanese: 'しずかなへやです。',
    reading: 'しずかなへやです。',
    english: 'It is a quiet room.',
    grammarTags: ['adjectives', 'noun-description', 'identity'],
    vocabTags: ['home', 'adjectives'],
  },
  {
    id: 'ex-kirei-mise-desu',
    japanese: 'きれいなみせです。',
    reading: 'きれいなみせです。',
    english: 'It is a pretty shop.',
    grammarTags: ['adjectives', 'noun-description', 'identity'],
    vocabTags: ['place', 'adjectives'],
  },
  {
    id: 'ex-yasashii-sensei-desu',
    japanese: 'やさしいせんせいです。',
    reading: 'やさしいせんせいです。',
    english: 'It is a kind teacher.',
    grammarTags: ['adjectives', 'noun-description', 'identity'],
    vocabTags: ['people', 'adjectives'],
  },
  {
    id: 'ex-hiroi-heya-desu',
    japanese: 'ひろいへやです。',
    reading: 'ひろいへやです。',
    english: 'It is a spacious room.',
    grammarTags: ['adjectives', 'noun-description', 'identity'],
    vocabTags: ['home', 'adjectives'],
  },
  {
    id: 'ex-chiisai-kaban-desu',
    japanese: 'ちいさいかばんです。',
    reading: 'ちいさいかばんです。',
    english: 'It is a small bag.',
    grammarTags: ['adjectives', 'noun-description', 'identity'],
    vocabTags: ['object', 'adjectives'],
  },
  {
    id: 'ex-hito-yasashii',
    japanese: 'あのひとはやさしいです。',
    reading: 'あのひとはやさしいです。',
    english: 'That person is kind.',
    grammarTags: ['adjectives', 'description', 'predicate'],
    vocabTags: ['people', 'adjectives'],
  },
  {
    id: 'ex-kinou-hon-yomimashita',
    japanese: 'きのうほんをよみました。',
    reading: 'きのうほんをよみました。',
    english: 'I read a book yesterday.',
    grammarTags: ['daily-routine', 'time', 'verb-forms-past'],
    vocabTags: ['book', 'time'],
  },
  {
    id: 'ex-asa-pan-tabemashita',
    japanese: 'あさパンをたべました。',
    reading: 'あさパンをたべました。',
    english: 'I ate bread in the morning.',
    grammarTags: ['daily-routine', 'time', 'verb-forms-past'],
    vocabTags: ['food', 'time'],
  },
  {
    id: 'ex-kafe-koohii-nomimashita',
    japanese: 'カフェでコーヒーをのみました。',
    reading: 'カフェでコーヒーをのみました。',
    english: 'I drank coffee at a cafe.',
    grammarTags: ['daily-routine', 'location', 'verb-forms-past'],
    vocabTags: ['drink', 'place'],
  },
  {
    id: 'ex-kyou-toshokan-ikimashita',
    japanese: 'きょうとしょかんにいきました。',
    reading: 'きょうとしょかんにいきました。',
    english: 'I went to the library today.',
    grammarTags: ['daily-routine', 'destination', 'verb-forms-past'],
    vocabTags: ['place', 'time'],
  },
  {
    id: 'ex-kinou-uchi-nihongo-benkyoushimashita',
    japanese: 'きのううちでにほんごをべんきょうしました。',
    reading: 'きのううちでにほんごをべんきょうしました。',
    english: 'I studied Japanese at home yesterday.',
    grammarTags: ['daily-routine', 'location', 'verb-forms-past'],
    vocabTags: ['home', 'study', 'time'],
  },
  {
    id: 'ex-senshuu-eiga-mimashita',
    japanese: 'せんしゅうえいがをみました。',
    reading: 'せんしゅうえいがをみました。',
    english: 'I watched a movie last week.',
    grammarTags: ['daily-routine', 'time', 'verb-forms-past'],
    vocabTags: ['hobby', 'time'],
  },
  {
    id: 'ex-asa-mizu-nomimashita',
    japanese: 'あさみずをのみました。',
    reading: 'あさみずをのみました。',
    english: 'I drank water in the morning.',
    grammarTags: ['daily-routine', 'time', 'verb-forms-past'],
    vocabTags: ['drink', 'time'],
  },
  {
    id: 'ex-kinou-kouen-ongaku-kikimashita',
    japanese: 'きのうこうえんでおんがくをききました。',
    reading: 'きのうこうえんでおんがくをききました。',
    english: 'I listened to music at the park yesterday.',
    grammarTags: ['daily-routine', 'location', 'verb-forms-past'],
    vocabTags: ['place', 'hobby', 'time'],
  },
  {
    id: 'ex-kinou-koohii-nomimasendeshita',
    japanese: 'きのうコーヒーをのみませんでした。',
    reading: 'きのうコーヒーをのみませんでした。',
    english: 'I did not drink coffee yesterday.',
    grammarTags: ['daily-routine', 'time', 'verb-forms-negative-past'],
    vocabTags: ['drink', 'time'],
  },
  {
    id: 'ex-kinou-gakkou-ikimasendeshita',
    japanese: 'きのうがっこうにいきませんでした。',
    reading: 'きのうがっこうにいきませんでした。',
    english: 'I did not go to school yesterday.',
    grammarTags: ['daily-routine', 'destination', 'verb-forms-negative-past'],
    vocabTags: ['school', 'time'],
  },
  {
    id: 'ex-kinou-eiga-mimasendeshita',
    japanese: 'きのうえいがをみませんでした。',
    reading: 'きのうえいがをみませんでした。',
    english: 'I did not watch a movie yesterday.',
    grammarTags: ['daily-routine', 'time', 'verb-forms-negative-past'],
    vocabTags: ['hobby', 'time'],
  },
  {
    id: 'ex-mizu-nonde-mo-ii',
    japanese: 'みずをのんでもいいですか。',
    reading: 'みずをのんでもいいですか。',
    english: 'May I drink water?',
    grammarTags: ['permission', 'verb-forms', 'daily-conversation'],
    vocabTags: ['drink', 'daily-conversation'],
  },
  {
    id: 'ex-toire-itte-mo-ii',
    japanese: 'トイレにいってもいいですか。',
    reading: 'トイレにいってもいいですか。',
    english: 'May I go to the bathroom?',
    grammarTags: ['permission', 'verb-forms', 'destination'],
    vocabTags: ['place', 'daily-conversation'],
  },
  {
    id: 'ex-koko-suwatte-mo-ii',
    japanese: 'ここにすわってもいいですか。',
    reading: 'ここにすわってもいいですか。',
    english: 'May I sit here?',
    grammarTags: ['permission', 'verb-forms', 'location'],
    vocabTags: ['location', 'daily-conversation'],
  },
  {
    id: 'ex-hon-yonde-mo-ii',
    japanese: 'ほんをよんでもいいですか。',
    reading: 'ほんをよんでもいいですか。',
    english: 'May I read the book?',
    grammarTags: ['permission', 'verb-forms', 'object'],
    vocabTags: ['book', 'daily-conversation'],
  },
  {
    id: 'ex-mado-akete-mo-ii',
    japanese: 'まどをあけてもいいですか。',
    reading: 'まどをあけてもいいですか。',
    english: 'May I open the window?',
    grammarTags: ['permission', 'verb-forms', 'object'],
    vocabTags: ['place', 'daily-conversation'],
  },
  {
    id: 'ex-chotto-matte-kudasai',
    japanese: 'ちょっとまってください。',
    reading: 'ちょっとまってください。',
    english: 'Please wait a moment.',
    grammarTags: ['request', 'verb-forms', 'daily-conversation'],
    vocabTags: ['daily-conversation', 'request'],
  },
  {
    id: 'ex-kore-mite-kudasai',
    japanese: 'これをみてください。',
    reading: 'これをみてください。',
    english: 'Please look at this.',
    grammarTags: ['request', 'verb-forms', 'object'],
    vocabTags: ['classroom', 'request'],
  },
  {
    id: 'ex-koko-suwatte-kudasai',
    japanese: 'ここにすわってください。',
    reading: 'ここにすわってください。',
    english: 'Please sit here.',
    grammarTags: ['request', 'verb-forms', 'location'],
    vocabTags: ['location', 'daily-conversation'],
  },
  {
    id: 'ex-yukkuri-yonde-kudasai',
    japanese: 'ゆっくりよんでください。',
    reading: 'ゆっくりよんでください。',
    english: 'Please read slowly.',
    grammarTags: ['request', 'verb-forms', 'daily-conversation'],
    vocabTags: ['daily-conversation', 'request'],
  },
  {
    id: 'ex-mou-ichido-yonde-kudasai',
    japanese: 'もういちどよんでください。',
    reading: 'もういちどよんでください。',
    english: 'Please read it one more time.',
    grammarTags: ['request', 'verb-forms', 'daily-conversation'],
    vocabTags: ['daily-conversation', 'request'],
  },
  {
    id: 'ex-mado-akete-kudasai',
    japanese: 'まどをあけてください。',
    reading: 'まどをあけてください。',
    english: 'Please open the window.',
    grammarTags: ['request', 'verb-forms', 'object'],
    vocabTags: ['place', 'daily-conversation'],
  },
  {
    id: 'ex-kore-o-kudasai',
    japanese: 'これをください。',
    reading: 'これをください。',
    english: 'Please give me this.',
    grammarTags: ['shopping', 'request', 'object'],
    vocabTags: ['shopping', 'demonstrative'],
  },
  {
    id: 'ex-kono-hon-o-kudasai',
    japanese: 'このほんをください。',
    reading: 'このほんをください。',
    english: 'Please give me this book.',
    grammarTags: ['shopping', 'request', 'object'],
    vocabTags: ['shopping', 'book'],
  },
  {
    id: 'ex-pan-o-kudasai',
    japanese: 'パンをください。',
    reading: 'パンをください。',
    english: 'Please give me bread.',
    grammarTags: ['shopping', 'request', 'object'],
    vocabTags: ['shopping', 'food'],
  },
  {
    id: 'ex-mizu-o-kaimasu',
    japanese: 'みずをかいます。',
    reading: 'みずをかいます。',
    english: 'I buy water.',
    grammarTags: ['shopping', 'object', 'verb-forms'],
    vocabTags: ['shopping', 'drink'],
  },
  {
    id: 'ex-ringo-o-kaimasu',
    japanese: 'りんごをかいます。',
    reading: 'りんごをかいます。',
    english: 'I buy apples.',
    grammarTags: ['shopping', 'object', 'verb-forms'],
    vocabTags: ['shopping', 'food'],
  },
  {
    id: 'ex-juusu-o-kaimasu',
    japanese: 'ジュースをかいます。',
    reading: 'ジュースをかいます。',
    english: 'I buy juice.',
    grammarTags: ['shopping', 'object', 'verb-forms'],
    vocabTags: ['shopping', 'drink'],
  },
  {
    id: 'ex-kudamono-o-kaimasu',
    japanese: 'くだものをかいます。',
    reading: 'くだものをかいます。',
    english: 'I buy fruit.',
    grammarTags: ['shopping', 'object', 'verb-forms'],
    vocabTags: ['shopping', 'food'],
  },
  {
    id: 'ex-sakana-o-kaimasu',
    japanese: 'さかなをかいます。',
    reading: 'さかなをかいます。',
    english: 'I buy fish.',
    grammarTags: ['shopping', 'object', 'verb-forms'],
    vocabTags: ['shopping', 'food'],
  },
  {
    id: 'ex-niku-o-kaimasu',
    japanese: 'にくをかいます。',
    reading: 'にくをかいます。',
    english: 'I buy meat.',
    grammarTags: ['shopping', 'object', 'verb-forms'],
    vocabTags: ['shopping', 'food'],
  },
  {
    id: 'ex-nani-o-kaimasu',
    japanese: 'なにをかいますか。',
    reading: 'なにをかいますか。',
    english: 'What do you buy?',
    grammarTags: ['shopping', 'question', 'object'],
    vocabTags: ['shopping', 'question'],
  },
  {
    id: 'ex-dore-o-kaimasu',
    japanese: 'どれをかいますか。',
    reading: 'どれをかいますか。',
    english: 'Which one do you buy?',
    grammarTags: ['shopping', 'question', 'object'],
    vocabTags: ['shopping', 'question'],
  },
  {
    id: 'ex-konbini-de-okashi-o-kaimasu',
    japanese: 'コンビニでおかしをかいます。',
    reading: 'コンビニでおかしをかいます。',
    english: 'I buy snacks at the convenience store.',
    grammarTags: ['shopping', 'location', 'object'],
    vocabTags: ['shopping', 'place', 'food'],
  },
] satisfies ExampleSentence[];
