import type { ExampleSentence } from '../lib/content/types';

export const exampleSentences = [
  {
    id: 'ex-colin-desu',
    japanese: 'わたしはコリンです。',
    reading: 'わたしはコリンです。',
    english: 'I am Colin.',
    grammarTags: ['topic', 'copula', 'self-introduction'],
    vocabTags: ['self', 'name'],
  },
  {
    id: 'ex-student-desu',
    japanese: 'わたしはがくせいです。',
    reading: 'わたしはがくせいです。',
    english: 'I am a student.',
    grammarTags: ['topic', 'copula', 'identity'],
    vocabTags: ['self', 'school'],
  },
  {
    id: 'ex-teacher-question',
    japanese: 'せんせいですか。',
    reading: 'せんせいですか。',
    english: 'Are you a teacher?',
    grammarTags: ['copula', 'question'],
    vocabTags: ['school', 'role'],
  },
  {
    id: 'ex-company-worker',
    japanese: 'ともだちはかいしゃいんです。',
    reading: 'ともだちはかいしゃいんです。',
    english: 'My friend is an office worker.',
    grammarTags: ['topic', 'copula', 'identity'],
    vocabTags: ['people', 'work'],
  },
  {
    id: 'ex-study-home',
    japanese: 'うちでにほんごをべんきょうします。',
    reading: 'うちでにほんごをべんきょうします。',
    english: 'I study Japanese at home.',
    grammarTags: ['location', 'object', 'daily-routine'],
    vocabTags: ['home', 'study'],
  },
  {
    id: 'ex-coffee-cafe',
    japanese: 'カフェでコーヒーをのみます。',
    reading: 'カフェでコーヒーをのみます。',
    english: 'I drink coffee at a cafe.',
    grammarTags: ['location', 'object', 'daily-routine'],
    vocabTags: ['cafe', 'drink'],
  },
  {
    id: 'ex-read-library',
    japanese: 'としょかんでほんをよみます。',
    reading: 'としょかんでほんをよみます。',
    english: 'I read a book at the library.',
    grammarTags: ['location', 'object', 'daily-routine'],
    vocabTags: ['library', 'reading'],
  },
  {
    id: 'ex-classroom-study',
    japanese: 'きょうしつでべんきょうします。',
    reading: 'きょうしつでべんきょうします。',
    english: 'I study in the classroom.',
    grammarTags: ['location', 'daily-routine'],
    vocabTags: ['school', 'study'],
  },
  {
    id: 'ex-kore-hon',
    japanese: 'これはほんです。',
    reading: 'これはほんです。',
    english: 'This is a book.',
    grammarTags: ['demonstrative', 'copula', 'identity'],
    vocabTags: ['classroom', 'book'],
  },
  {
    id: 'ex-kore-nan',
    japanese: 'これはなんですか。',
    reading: 'これはなんですか。',
    english: 'What is this?',
    grammarTags: ['demonstrative', 'question', 'copula'],
    vocabTags: ['classroom', 'question'],
  },
  {
    id: 'ex-sore-shukudai',
    japanese: 'それはしゅくだいです。',
    reading: 'それはしゅくだいです。',
    english: 'That is homework.',
    grammarTags: ['demonstrative', 'copula', 'identity'],
    vocabTags: ['classroom', 'study'],
  },
  {
    id: 'ex-kore-eigo-hon',
    japanese: 'これはえいごのほんです。',
    reading: 'これはえいごのほんです。',
    english: 'This is an English book.',
    grammarTags: ['demonstrative', 'copula', 'noun-linking'],
    vocabTags: ['classroom', 'book', 'study'],
  },
  {
    id: 'ex-doko-ikimasu',
    japanese: 'どこにいきますか。',
    reading: 'どこにいきますか。',
    english: 'Where do you go?',
    grammarTags: ['question', 'destination', 'movement'],
    vocabTags: ['question', 'daily-routine'],
  },
  {
    id: 'ex-mainichi-gakkou',
    japanese: 'まいにちがっこうにいきます。',
    reading: 'まいにちがっこうにいきます。',
    english: 'I go to school every day.',
    grammarTags: ['destination', 'movement', 'daily-routine'],
    vocabTags: ['school', 'time', 'daily-routine'],
  },
  {
    id: 'ex-kyou-toshokan',
    japanese: 'きょうとしょかんにいきます。',
    reading: 'きょうとしょかんにいきます。',
    english: 'I go to the library today.',
    grammarTags: ['destination', 'movement', 'daily-routine'],
    vocabTags: ['study', 'time', 'library'],
  },
  {
    id: 'ex-ima-kyoushitsu',
    japanese: 'いまきょうしつにいきます。',
    reading: 'いまきょうしつにいきます。',
    english: 'I am going to the classroom now.',
    grammarTags: ['destination', 'movement', 'daily-routine'],
    vocabTags: ['school', 'time', 'classroom'],
  },
  {
    id: 'ex-sensei-doko',
    japanese: 'せんせいはどこにいきますか。',
    reading: 'せんせいはどこにいきますか。',
    english: 'Where does the teacher go?',
    grammarTags: ['topic', 'question', 'destination'],
    vocabTags: ['school', 'question'],
  },
  {
    id: 'ex-tomodachi-gakkou',
    japanese: 'ともだちはがっこうにいきます。',
    reading: 'ともだちはがっこうにいきます。',
    english: 'My friend goes to school.',
    grammarTags: ['topic', 'destination', 'movement'],
    vocabTags: ['people', 'school'],
  },
] satisfies ExampleSentence[];
