import type { ListeningItem } from '../lib/content/types';

export const listeningItems = [
  {
    id: 'listening-self-intro',
    audioRef: '/audio/listening/listening-self-intro.mp3',
    transcript: 'わたしはコリンです。',
    reading: 'わたしはコリンです。',
    translation: 'I am Colin.',
    focusPoint: 'Hear the topic marker は and the polite ending です.',
    difficulty: 'easy',
  },
  {
    id: 'listening-teacher-question',
    audioRef: '/audio/listening/listening-teacher-question.mp3',
    transcript: 'せんせいですか。',
    reading: 'せんせいですか。',
    translation: 'Are you a teacher?',
    focusPoint: 'Catch the question ending か without relying on English-style word order.',
    difficulty: 'easy',
  },
  {
    id: 'listening-home-study',
    audioRef: '/audio/listening/listening-home-study.mp3',
    transcript: 'うちでにほんごをべんきょうします。',
    reading: 'うちでにほんごをべんきょうします。',
    translation: 'I study Japanese at home.',
    focusPoint: 'Identify the location particle で and the study verb.',
    difficulty: 'medium',
  },
  {
    id: 'listening-cafe-coffee',
    audioRef: '/audio/listening/listening-cafe-coffee.mp3',
    transcript: 'カフェでコーヒーをのみます。',
    reading: 'カフェでコーヒーをのみます。',
    translation: 'I drink coffee at a cafe.',
    focusPoint: 'Listen for where the action happens before the object and verb.',
    difficulty: 'medium',
  },
  {
    id: 'listening-kore-nan',
    audioRef: '/audio/listening/listening-kore-nan.mp3',
    transcript: 'これはなんですか。',
    reading: 'これはなんですか。',
    translation: 'What is this?',
    focusPoint: 'Catch the question word なん and the polite question ending か.',
    difficulty: 'easy',
  },
  {
    id: 'listening-kore-hon',
    audioRef: '/audio/listening/listening-kore-hon.mp3',
    transcript: 'これはほんです。',
    reading: 'これはほんです。',
    translation: 'This is a book.',
    focusPoint: 'Hear the demonstrative これ and the simple noun plus です answer pattern.',
    difficulty: 'easy',
  },
  {
    id: 'listening-sore-shukudai',
    audioRef: '/audio/listening/listening-sore-shukudai.mp3',
    transcript: 'それはしゅくだいです。',
    reading: 'それはしゅくだいです。',
    translation: 'That is homework.',
    focusPoint: 'Listen for それは at the start, then hear the noun before the polite ending.',
    difficulty: 'easy',
  },
  {
    id: 'listening-kore-eigo-hon',
    audioRef: '/audio/listening/listening-kore-eigo-hon.mp3',
    transcript: 'これはえいごのほんです。',
    reading: 'これはえいごのほんです。',
    translation: 'This is an English book.',
    focusPoint: 'Hear how の links the two nouns before the final です.',
    difficulty: 'medium',
  },
  {
    id: 'listening-sore-nan',
    audioRef: '/audio/listening/listening-sore-nan.mp3',
    transcript: 'それはなんですか。',
    reading: 'それはなんですか。',
    translation: 'What is that?',
    focusPoint: 'Notice the same question pattern as これはなんですか, but with それ for something near the listener.',
    difficulty: 'easy',
  },
  {
    id: 'listening-neko-heya',
    audioRef: '/audio/listening/listening-neko-heya.mp3',
    transcript: 'ねこはへやにいます。',
    reading: 'ねこはへやにいます。',
    translation: 'The cat is in the room.',
    focusPoint: 'Hear に before います, and notice that います is used for an animal.',
    difficulty: 'easy',
  },
  {
    id: 'listening-sensei-kyoushitsu',
    audioRef: '/audio/listening/listening-sensei-kyoushitsu.mp3',
    transcript: 'せんせいはきょうしつにいます。',
    reading: 'せんせいはきょうしつにいます。',
    translation: 'The teacher is in the classroom.',
    focusPoint: 'Catch the location particle に and the animate existence verb います.',
    difficulty: 'easy',
  },
  {
    id: 'listening-hon-tsukue-ue',
    audioRef: '/audio/listening/listening-hon-tsukue-ue.mp3',
    transcript: 'ほんはつくえのうえにあります。',
    reading: 'ほんはつくえのうえにあります。',
    translation: 'The book is on the desk.',
    focusPoint: 'Listen for the full location phrase つくえのうえに before あります.',
    difficulty: 'medium',
  },
  {
    id: 'listening-kaban-isu-shita',
    audioRef: '/audio/listening/listening-kaban-isu-shita.mp3',
    transcript: 'かばんはいすのしたにあります。',
    reading: 'かばんはいすのしたにあります。',
    translation: 'The bag is under the chair.',
    focusPoint: 'Notice how のしたに builds the location before the existence verb.',
    difficulty: 'medium',
  },
  {
    id: 'listening-hon-kaban-naka',
    audioRef: '/audio/listening/listening-hon-kaban-naka.mp3',
    transcript: 'ほんはかばんのなかにあります。',
    reading: 'ほんはかばんのなかにあります。',
    translation: 'The book is inside the bag.',
    focusPoint: 'Catch なかに as the inside-location phrase and あります for the object.',
    difficulty: 'medium',
  },
  {
    id: 'listening-watashi-sushi-suki',
    audioRef: '/audio/listening/listening-watashi-sushi-suki.mp3',
    transcript: 'わたしはすしがすきです。',
    reading: 'わたしはすしがすきです。',
    translation: 'I like sushi.',
    focusPoint: 'Hear the liked thing before が, then catch すきです at the end.',
    difficulty: 'easy',
  },
  {
    id: 'listening-koohii-kirai',
    audioRef: '/audio/listening/listening-koohii-kirai.mp3',
    transcript: 'わたしはコーヒーがきらいです。',
    reading: 'わたしはコーヒーがきらいです。',
    translation: 'I dislike coffee.',
    focusPoint: 'Notice が before the target noun phrase and listen for きらいです.',
    difficulty: 'easy',
  },
  {
    id: 'listening-ongaku-suki',
    audioRef: '/audio/listening/listening-ongaku-suki.mp3',
    transcript: 'おんがくがすきです。',
    reading: 'おんがくがすきです。',
    translation: 'I like music.',
    focusPoint: 'Catch the short pattern noun plus が plus すきです.',
    difficulty: 'easy',
  },
  {
    id: 'listening-nani-suki',
    audioRef: '/audio/listening/listening-nani-suki.mp3',
    transcript: 'なにがすきですか。',
    reading: 'なにがすきですか。',
    translation: 'What do you like?',
    focusPoint: 'Hear the question word なに and the polite question ending か.',
    difficulty: 'easy',
  },
  {
    id: 'listening-tabemono-nani-suki',
    audioRef: '/audio/listening/listening-tabemono-nani-suki.mp3',
    transcript: 'たべものはなにがすきですか。',
    reading: 'たべものはなにがすきですか。',
    translation: 'What food do you like?',
    focusPoint: 'Notice the category topic は first, then the question phrase なにが.',
    difficulty: 'medium',
  },
  {
    id: 'listening-toire-doko',
    audioRef: '/audio/listening/listening-toire-doko.mp3',
    transcript: 'トイレはどこですか。',
    reading: 'トイレはどこですか。',
    translation: 'Where is the bathroom?',
    focusPoint: 'Catch the location question どこですか after the topic は.',
    difficulty: 'easy',
  },
  {
    id: 'listening-toire-asoko',
    audioRef: '/audio/listening/listening-toire-asoko.mp3',
    transcript: 'トイレはあそこです。',
    reading: 'トイレはあそこです。',
    translation: 'The bathroom is over there.',
    focusPoint: 'Listen for the short location answer あそこです.',
    difficulty: 'easy',
  },
  {
    id: 'listening-kagi-doko',
    audioRef: '/audio/listening/listening-kagi-doko.mp3',
    transcript: 'かぎはどこですか。',
    reading: 'かぎはどこですか。',
    translation: 'Where is the key?',
    focusPoint: 'Hear the topic first, then the full where-question pattern.',
    difficulty: 'easy',
  },
  {
    id: 'listening-kagi-tsukue-ue',
    audioRef: '/audio/listening/listening-kagi-tsukue-ue.mp3',
    transcript: 'かぎはつくえのうえにあります。',
    reading: 'かぎはつくえのうえにあります。',
    translation: 'The key is on the desk.',
    focusPoint: 'Notice the full location phrase つくえのうえに before あります.',
    difficulty: 'medium',
  },
  {
    id: 'listening-sensei-jimusho',
    audioRef: '/audio/listening/listening-sensei-jimusho.mp3',
    transcript: 'せんせいはじむしょにいます。',
    reading: 'せんせいはじむしょにいます。',
    translation: 'The teacher is in the office.',
    focusPoint: 'Catch the place with に and the animate existence verb います.',
    difficulty: 'medium',
  },
  {
    id: 'listening-kore-watashi-no-hon',
    audioRef: '/audio/listening/listening-kore-watashi-no-hon.mp3',
    transcript: 'これはわたしのほんです。',
    reading: 'これはわたしのほんです。',
    translation: 'This is my book.',
    focusPoint: 'Hear how の links the owner to the object before the final です.',
    difficulty: 'easy',
  },
  {
    id: 'listening-sore-ane-no-kaban',
    audioRef: '/audio/listening/listening-sore-ane-no-kaban.mp3',
    transcript: 'それはあねのかばんです。',
    reading: 'それはあねのかばんです。',
    translation: "That is my older sister's bag.",
    focusPoint: 'Catch the family noun first, then hear の linking it to かばん.',
    difficulty: 'easy',
  },
  {
    id: 'listening-kore-chichi-no-kamera',
    audioRef: '/audio/listening/listening-kore-chichi-no-kamera.mp3',
    transcript: 'これはちちのカメラです。',
    reading: 'これはちちのカメラです。',
    translation: "This is my father's camera.",
    focusPoint: 'Listen for the owner phrase ちちの before the object noun カメラ.',
    difficulty: 'easy',
  },
  {
    id: 'listening-kore-kazoku-no-shashin',
    audioRef: '/audio/listening/listening-kore-kazoku-no-shashin.mp3',
    transcript: 'これはかぞくのしゃしんです。',
    reading: 'これはかぞくのしゃしんです。',
    translation: 'This is a family photo.',
    focusPoint: 'Notice how かぞくのしゃしん forms one noun phrase before です.',
    difficulty: 'medium',
  },
  {
    id: 'listening-sore-haha-no-kasa',
    audioRef: '/audio/listening/listening-sore-haha-no-kasa.mp3',
    transcript: 'それはははのかさです。',
    reading: 'それはははのかさです。',
    translation: "That is my mother's umbrella.",
    focusPoint: 'Hear それは first, then the ownership phrase before the final noun.',
    difficulty: 'easy',
  },
  {
    id: 'listening-asa-pan-tabemasu',
    audioRef: '/audio/listening/listening-asa-pan-tabemasu.mp3',
    transcript: 'あさパンをたべます。',
    reading: 'あさパンをたべます。',
    translation: 'I eat bread in the morning.',
    focusPoint: 'Catch the morning time word first, then the object and polite verb.',
    difficulty: 'easy',
  },
  {
    id: 'listening-yoru-hon-yomimasu',
    audioRef: '/audio/listening/listening-yoru-hon-yomimasu.mp3',
    transcript: 'よるほんをよみます。',
    reading: 'よるほんをよみます。',
    translation: 'I read a book at night.',
    focusPoint: 'Listen for the time word よる, then hear the object before よみます.',
    difficulty: 'easy',
  },
  {
    id: 'listening-uchi-terebi-mimasu',
    audioRef: '/audio/listening/listening-uchi-terebi-mimasu.mp3',
    transcript: 'うちでテレビをみます。',
    reading: 'うちでテレビをみます。',
    translation: 'I watch TV at home.',
    focusPoint: 'Notice the place particle で before the object and polite verb.',
    difficulty: 'medium',
  },
  {
    id: 'listening-kyou-koohii-nomimasen',
    audioRef: '/audio/listening/listening-kyou-koohii-nomimasen.mp3',
    transcript: 'きょうコーヒーをのみません。',
    reading: 'きょうコーヒーをのみません。',
    translation: 'I do not drink coffee today.',
    focusPoint: 'Listen for the negative ending ません after the object phrase.',
    difficulty: 'medium',
  },
  {
    id: 'listening-ashita-toshokan-ikimasen',
    audioRef: '/audio/listening/listening-ashita-toshokan-ikimasen.mp3',
    transcript: 'あしたとしょかんにいきません。',
    reading: 'あしたとしょかんにいきません。',
    translation: 'I am not going to the library tomorrow.',
    focusPoint: 'Catch the destination with に, then hear the negative polite ending in いきません.',
    difficulty: 'medium',
  },
  {
    id: 'listening-hon-omoshiroi',
    audioRef: '/audio/listening/listening-hon-omoshiroi.mp3',
    transcript: 'ほんはおもしろいです。',
    reading: 'ほんはおもしろいです。',
    translation: 'The book is interesting.',
    focusPoint: 'Catch the topic first, then hear the adjective before the polite ending です.',
    difficulty: 'easy',
  },
  {
    id: 'listening-kaban-ookii',
    audioRef: '/audio/listening/listening-kaban-ookii.mp3',
    transcript: 'かばんはおおきいです。',
    reading: 'かばんはおおきいです。',
    translation: 'The bag is big.',
    focusPoint: 'Listen for the bag first, then the い-adjective おおきい.',
    difficulty: 'easy',
  },
  {
    id: 'listening-heya-shizuka',
    audioRef: '/audio/listening/listening-heya-shizuka.mp3',
    transcript: 'へやはしずかです。',
    reading: 'へやはしずかです。',
    translation: 'The room is quiet.',
    focusPoint: 'Notice that the line ends with しずかです as a short polite description.',
    difficulty: 'easy',
  },
  {
    id: 'listening-kamera-atarashii',
    audioRef: '/audio/listening/listening-kamera-atarashii.mp3',
    transcript: 'カメラはあたらしいです。',
    reading: 'カメラはあたらしいです。',
    translation: 'The camera is new.',
    focusPoint: 'Catch the object first, then hear the adjective あたらしい before です.',
    difficulty: 'easy',
  },
  {
    id: 'listening-kirei-mise',
    audioRef: '/audio/listening/listening-kirei-mise.mp3',
    transcript: 'きれいなみせです。',
    reading: 'きれいなみせです。',
    translation: 'It is a pretty shop.',
    focusPoint: 'Listen for the noun phrase きれいなみせ as one description unit.',
    difficulty: 'medium',
  },
  {
    id: 'listening-kinou-hon-yomimashita',
    audioRef: '/audio/listening/listening-kinou-hon-yomimashita.mp3',
    transcript: 'きのうほんをよみました。',
    reading: 'きのうほんをよみました。',
    translation: 'I read a book yesterday.',
    focusPoint: 'Catch the time word きのう first, then listen for the past ending ました.',
    difficulty: 'easy',
  },
  {
    id: 'listening-asa-pan-tabemashita',
    audioRef: '/audio/listening/listening-asa-pan-tabemashita.mp3',
    transcript: 'あさパンをたべました。',
    reading: 'あさパンをたべました。',
    translation: 'I ate bread in the morning.',
    focusPoint: 'Notice the familiar food line, but with the completed-action ending ました.',
    difficulty: 'easy',
  },
  {
    id: 'listening-kafe-koohii-nomimashita',
    audioRef: '/audio/listening/listening-kafe-koohii-nomimashita.mp3',
    transcript: 'カフェでコーヒーをのみました。',
    reading: 'カフェでコーヒーをのみました。',
    translation: 'I drank coffee at a cafe.',
    focusPoint: 'Listen for the place with で, then catch the object before the past verb.',
    difficulty: 'medium',
  },
  {
    id: 'listening-kyou-toshokan-ikimashita',
    audioRef: '/audio/listening/listening-kyou-toshokan-ikimashita.mp3',
    transcript: 'きょうとしょかんにいきました。',
    reading: 'きょうとしょかんにいきました。',
    translation: 'I went to the library today.',
    focusPoint: 'Catch the destination with に, then hear いきました as a completed action.',
    difficulty: 'medium',
  },
  {
    id: 'listening-kinou-koohii-nomimasendeshita',
    audioRef: '/audio/listening/listening-kinou-koohii-nomimasendeshita.mp3',
    transcript: 'きのうコーヒーをのみませんでした。',
    reading: 'きのうコーヒーをのみませんでした。',
    translation: 'I did not drink coffee yesterday.',
    focusPoint: 'Listen for the longer negative-past ending ませんでした after the object phrase.',
    difficulty: 'medium',
  },
  {
    id: 'listening-mizu-nonde-mo-ii',
    audioRef: '/audio/listening/listening-mizu-nonde-mo-ii.mp3',
    transcript: 'みずをのんでもいいですか。',
    reading: 'みずをのんでもいいですか。',
    translation: 'May I drink water?',
    focusPoint: 'Catch the permission ending もいいですか after the て-form verb.',
    difficulty: 'easy',
  },
  {
    id: 'listening-toire-itte-mo-ii',
    audioRef: '/audio/listening/listening-toire-itte-mo-ii.mp3',
    transcript: 'トイレにいってもいいですか。',
    reading: 'トイレにいってもいいですか。',
    translation: 'May I go to the bathroom?',
    focusPoint: 'Listen for the destination with に, then the permission pattern いってもいいですか.',
    difficulty: 'medium',
  },
  {
    id: 'listening-chotto-matte-kudasai',
    audioRef: '/audio/listening/listening-chotto-matte-kudasai.mp3',
    transcript: 'ちょっとまってください。',
    reading: 'ちょっとまってください。',
    translation: 'Please wait a moment.',
    focusPoint: 'Catch the short request ending ください after the て-form verb.',
    difficulty: 'easy',
  },
  {
    id: 'listening-koko-suwatte-kudasai',
    audioRef: '/audio/listening/listening-koko-suwatte-kudasai.mp3',
    transcript: 'ここにすわってください。',
    reading: 'ここにすわってください。',
    translation: 'Please sit here.',
    focusPoint: 'Listen for the place with に before the request ending ください.',
    difficulty: 'easy',
  },
  {
    id: 'listening-yukkuri-yonde-kudasai',
    audioRef: '/audio/listening/listening-yukkuri-yonde-kudasai.mp3',
    transcript: 'ゆっくりよんでください。',
    reading: 'ゆっくりよんでください。',
    translation: 'Please read slowly.',
    focusPoint: 'Catch the adverb ゆっくり first, then the て-form request ending ください.',
    difficulty: 'medium',
  },
  {
    id: 'listening-kore-o-kudasai',
    audioRef: '/audio/listening/listening-kore-o-kudasai.mp3',
    transcript: 'これをください。',
    reading: 'これをください。',
    translation: 'Please give me this.',
    focusPoint: 'Catch the object marker を before the short shopping request ください.',
    difficulty: 'easy',
  },
  {
    id: 'listening-kono-hon-o-kudasai',
    audioRef: '/audio/listening/listening-kono-hon-o-kudasai.mp3',
    transcript: 'このほんをください。',
    reading: 'このほんをください。',
    translation: 'Please give me this book.',
    focusPoint: 'Listen for この before the noun, then the object marker を before ください.',
    difficulty: 'easy',
  },
  {
    id: 'listening-mizu-o-kaimasu',
    audioRef: '/audio/listening/listening-mizu-o-kaimasu.mp3',
    transcript: 'みずをかいます。',
    reading: 'みずをかいます。',
    translation: 'I buy water.',
    focusPoint: 'Catch the familiar object phrase, then hear the shopping verb かいます.',
    difficulty: 'easy',
  },
  {
    id: 'listening-nani-o-kaimasu',
    audioRef: '/audio/listening/listening-nani-o-kaimasu.mp3',
    transcript: 'なにをかいますか。',
    reading: 'なにをかいますか。',
    translation: 'What do you buy?',
    focusPoint: 'Listen for the question word なに before をかいますか.',
    difficulty: 'easy',
  },
  {
    id: 'listening-konbini-de-okashi-o-kaimasu',
    audioRef: '/audio/listening/listening-konbini-de-okashi-o-kaimasu.mp3',
    transcript: 'コンビニでおかしをかいます。',
    reading: 'コンビニでおかしをかいます。',
    translation: 'I buy snacks at the convenience store.',
    focusPoint: 'Catch the place with で first, then the object phrase before かいます.',
    difficulty: 'medium',
  },
  {
    id: 'listening-nanji-desu-ka',
    audioRef: '/audio/listening/listening-nanji-desu-ka.mp3',
    transcript: 'なんじですか。',
    reading: 'なんじですか。',
    translation: 'What time is it?',
    focusPoint: 'Catch the short time-question pattern ending with ですか.',
    difficulty: 'easy',
  },
  {
    id: 'listening-gozen-hachiji-desu',
    audioRef: '/audio/listening/listening-gozen-hachiji-desu.mp3',
    transcript: 'ごぜんはちじです。',
    reading: 'ごぜんはちじです。',
    translation: 'It is 8 AM.',
    focusPoint: 'Listen for the morning marker ごぜん before the clock time.',
    difficulty: 'easy',
  },
  {
    id: 'listening-hachiji-ni-gakkou-ikimasu',
    audioRef: '/audio/listening/listening-hachiji-ni-gakkou-ikimasu.mp3',
    transcript: 'はちじにがっこうにいきます。',
    reading: 'はちじにがっこうにいきます。',
    translation: 'I go to school at eight o’clock.',
    focusPoint: 'Catch the time phrase with に first, then the destination phrase with に.',
    difficulty: 'medium',
  },
  {
    id: 'listening-kuji-ni-nihongo-benkyoushimasu',
    audioRef: '/audio/listening/listening-kuji-ni-nihongo-benkyoushimasu.mp3',
    transcript: 'くじににほんごをべんきょうします。',
    reading: 'くじににほんごをべんきょうします。',
    translation: 'I study Japanese at nine o’clock.',
    focusPoint: 'Listen for the time phrase before the object and study verb.',
    difficulty: 'medium',
  },
  {
    id: 'listening-yoru-juuji-ni-nemasu',
    audioRef: '/audio/listening/listening-yoru-juuji-ni-nemasu.mp3',
    transcript: 'よるじゅうじにねます。',
    reading: 'よるじゅうじにねます。',
    translation: 'I go to bed at ten at night.',
    focusPoint: 'Catch the night expression first, then the time with に before ねます.',
    difficulty: 'medium',
  },
  {
    id: 'listening-getsuyoubi-ni-gakkou-ikimasu',
    audioRef: '/audio/listening/listening-getsuyoubi-ni-gakkou-ikimasu.mp3',
    transcript: 'げつようびにがっこうにいきます。',
    reading: 'げつようびにがっこうにいきます。',
    translation: 'I go to school on Monday.',
    focusPoint: 'Catch the weekday first, then the destination phrase with に before いきます.',
    difficulty: 'medium',
  },
  {
    id: 'listening-mokuyoubi-ni-nihongo-o-benkyoushimasu',
    audioRef: '/audio/listening/listening-mokuyoubi-ni-nihongo-o-benkyoushimasu.mp3',
    transcript: 'もくようびににほんごをべんきょうします。',
    reading: 'もくようびににほんごをべんきょうします。',
    translation: 'I study Japanese on Thursday.',
    focusPoint: 'Listen for the weekday with に before the object and study verb.',
    difficulty: 'medium',
  },
  {
    id: 'listening-doyoubi-ni-nani-o-shimasu-ka',
    audioRef: '/audio/listening/listening-doyoubi-ni-nani-o-shimasu-ka.mp3',
    transcript: 'どようびになにをしますか。',
    reading: 'どようびになにをしますか。',
    translation: 'What do you do on Saturday?',
    focusPoint: 'Catch the weekday phrase first, then the question pattern なにをしますか.',
    difficulty: 'easy',
  },
  {
    id: 'listening-nichiyoubi-wa-uchi-de-yasumimasu',
    audioRef: '/audio/listening/listening-nichiyoubi-wa-uchi-de-yasumimasu.mp3',
    transcript: 'にちようびはうちでやすみます。',
    reading: 'にちようびはうちでやすみます。',
    translation: 'I rest at home on Sunday.',
    focusPoint: 'Listen for the topic marker は after the weekday, then the place with で.',
    difficulty: 'medium',
  },
  {
    id: 'listening-raishuu-doyoubi-ni-toshokan-ni-ikimasu',
    audioRef: '/audio/listening/listening-raishuu-doyoubi-ni-toshokan-ni-ikimasu.mp3',
    transcript: 'らいしゅうどようびにとしょかんにいきます。',
    reading: 'らいしゅうどようびにとしょかんにいきます。',
    translation: 'I go to the library next Saturday.',
    focusPoint: 'Catch the next-week expression first, then the weekday and destination phrases.',
    difficulty: 'medium',
  },
] satisfies ListeningItem[];
