import type { ListeningItem } from '../lib/content/types';

export const listeningItems = [
  {
    id: 'listening-self-intro',
    audioRef: '/audio/listening/listening-self-intro.mp3',
    transcript: 'わたしはコリンです。',
    reading: 'わたしはコリンです。',
    translation: 'I am Colin.',
    focusPoint: 'Hear the topic marker は and the polite ending です.',
    difficulty: 'easy',
  },
  {
    id: 'listening-teacher-question',
    audioRef: '/audio/listening/listening-teacher-question.mp3',
    transcript: 'せんせいですか。',
    reading: 'せんせいですか。',
    translation: 'Are you a teacher?',
    focusPoint: 'Catch the question ending か without relying on English-style word order.',
    difficulty: 'easy',
  },
  {
    id: 'listening-home-study',
    audioRef: '/audio/listening/listening-home-study.mp3',
    transcript: 'うちでにほんごをべんきょうします。',
    reading: 'うちでにほんごをべんきょうします。',
    translation: 'I study Japanese at home.',
    focusPoint: 'Identify the location particle で and the study verb.',
    difficulty: 'medium',
  },
  {
    id: 'listening-cafe-coffee',
    audioRef: '/audio/listening/listening-cafe-coffee.mp3',
    transcript: 'カフェでコーヒーをのみます。',
    reading: 'カフェでコーヒーをのみます。',
    translation: 'I drink coffee at a cafe.',
    focusPoint: 'Listen for where the action happens before the object and verb.',
    difficulty: 'medium',
  },
  {
    id: 'listening-kore-nan',
    audioRef: '/audio/listening/listening-kore-nan.mp3',
    transcript: 'これはなんですか。',
    reading: 'これはなんですか。',
    translation: 'What is this?',
    focusPoint: 'Catch the question word なん and the polite question ending か.',
    difficulty: 'easy',
  },
  {
    id: 'listening-kore-hon',
    audioRef: '/audio/listening/listening-kore-hon.mp3',
    transcript: 'これはほんです。',
    reading: 'これはほんです。',
    translation: 'This is a book.',
    focusPoint: 'Hear the demonstrative これ and the simple noun plus です answer pattern.',
    difficulty: 'easy',
  },
  {
    id: 'listening-sore-shukudai',
    audioRef: '/audio/listening/listening-sore-shukudai.mp3',
    transcript: 'それはしゅくだいです。',
    reading: 'それはしゅくだいです。',
    translation: 'That is homework.',
    focusPoint: 'Listen for それは at the start, then hear the noun before the polite ending.',
    difficulty: 'easy',
  },
  {
    id: 'listening-kore-eigo-hon',
    audioRef: '/audio/listening/listening-kore-eigo-hon.mp3',
    transcript: 'これはえいごのほんです。',
    reading: 'これはえいごのほんです。',
    translation: 'This is an English book.',
    focusPoint: 'Hear how の links the two nouns before the final です.',
    difficulty: 'medium',
  },
  {
    id: 'listening-sore-nan',
    audioRef: '/audio/listening/listening-sore-nan.mp3',
    transcript: 'それはなんですか。',
    reading: 'それはなんですか。',
    translation: 'What is that?',
    focusPoint: 'Notice the same question pattern as これはなんですか, but with それ for something near the listener.',
    difficulty: 'easy',
  },
] satisfies ListeningItem[];
