import type { ListeningItem } from '../lib/content/types';

export const listeningItems = [
  {
    id: 'listening-self-intro',
    audioRef: '/audio/listening/listening-self-intro.mp3',
    transcript: 'わたしはコリンです。',
    reading: 'わたしはコリンです。',
    translation: 'I am Colin.',
    focusPoint: 'Hear the topic marker は and the polite ending です.',
    difficulty: 'easy',
  },
  {
    id: 'listening-teacher-question',
    audioRef: '/audio/listening/listening-teacher-question.mp3',
    transcript: 'せんせいですか。',
    reading: 'せんせいですか。',
    translation: 'Are you a teacher?',
    focusPoint: 'Catch the question ending か without relying on English-style word order.',
    difficulty: 'easy',
  },
  {
    id: 'listening-home-study',
    audioRef: '/audio/listening/listening-home-study.mp3',
    transcript: 'うちでにほんごをべんきょうします。',
    reading: 'うちでにほんごをべんきょうします。',
    translation: 'I study Japanese at home.',
    focusPoint: 'Identify the location particle で and the study verb.',
    difficulty: 'medium',
  },
  {
    id: 'listening-cafe-coffee',
    audioRef: '/audio/listening/listening-cafe-coffee.mp3',
    transcript: 'カフェでコーヒーをのみます。',
    reading: 'カフェでコーヒーをのみます。',
    translation: 'I drink coffee at a cafe.',
    focusPoint: 'Listen for where the action happens before the object and verb.',
    difficulty: 'medium',
  },
  {
    id: 'listening-kore-nan',
    audioRef: '/audio/listening/listening-kore-nan.mp3',
    transcript: 'これはなんですか。',
    reading: 'これはなんですか。',
    translation: 'What is this?',
    focusPoint: 'Catch the question word なん and the polite question ending か.',
    difficulty: 'easy',
  },
  {
    id: 'listening-kore-hon',
    audioRef: '/audio/listening/listening-kore-hon.mp3',
    transcript: 'これはほんです。',
    reading: 'これはほんです。',
    translation: 'This is a book.',
    focusPoint: 'Hear the demonstrative これ and the simple noun plus です answer pattern.',
    difficulty: 'easy',
  },
  {
    id: 'listening-sore-shukudai',
    audioRef: '/audio/listening/listening-sore-shukudai.mp3',
    transcript: 'それはしゅくだいです。',
    reading: 'それはしゅくだいです。',
    translation: 'That is homework.',
    focusPoint: 'Listen for それは at the start, then hear the noun before the polite ending.',
    difficulty: 'easy',
  },
  {
    id: 'listening-kore-eigo-hon',
    audioRef: '/audio/listening/listening-kore-eigo-hon.mp3',
    transcript: 'これはえいごのほんです。',
    reading: 'これはえいごのほんです。',
    translation: 'This is an English book.',
    focusPoint: 'Hear how の links the two nouns before the final です.',
    difficulty: 'medium',
  },
  {
    id: 'listening-sore-nan',
    audioRef: '/audio/listening/listening-sore-nan.mp3',
    transcript: 'それはなんですか。',
    reading: 'それはなんですか。',
    translation: 'What is that?',
    focusPoint: 'Notice the same question pattern as これはなんですか, but with それ for something near the listener.',
    difficulty: 'easy',
  },
  {
    id: 'listening-neko-heya',
    audioRef: '/audio/listening/listening-neko-heya.mp3',
    transcript: 'ねこはへやにいます。',
    reading: 'ねこはへやにいます。',
    translation: 'The cat is in the room.',
    focusPoint: 'Hear に before います, and notice that います is used for an animal.',
    difficulty: 'easy',
  },
  {
    id: 'listening-sensei-kyoushitsu',
    audioRef: '/audio/listening/listening-sensei-kyoushitsu.mp3',
    transcript: 'せんせいはきょうしつにいます。',
    reading: 'せんせいはきょうしつにいます。',
    translation: 'The teacher is in the classroom.',
    focusPoint: 'Catch the location particle に and the animate existence verb います.',
    difficulty: 'easy',
  },
  {
    id: 'listening-hon-tsukue-ue',
    audioRef: '/audio/listening/listening-hon-tsukue-ue.mp3',
    transcript: 'ほんはつくえのうえにあります。',
    reading: 'ほんはつくえのうえにあります。',
    translation: 'The book is on the desk.',
    focusPoint: 'Listen for the full location phrase つくえのうえに before あります.',
    difficulty: 'medium',
  },
  {
    id: 'listening-kaban-isu-shita',
    audioRef: '/audio/listening/listening-kaban-isu-shita.mp3',
    transcript: 'かばんはいすのしたにあります。',
    reading: 'かばんはいすのしたにあります。',
    translation: 'The bag is under the chair.',
    focusPoint: 'Notice how のしたに builds the location before the existence verb.',
    difficulty: 'medium',
  },
  {
    id: 'listening-hon-kaban-naka',
    audioRef: '/audio/listening/listening-hon-kaban-naka.mp3',
    transcript: 'ほんはかばんのなかにあります。',
    reading: 'ほんはかばんのなかにあります。',
    translation: 'The book is inside the bag.',
    focusPoint: 'Catch なかに as the inside-location phrase and あります for the object.',
    difficulty: 'medium',
  },
  {
    id: 'listening-watashi-sushi-suki',
    audioRef: '/audio/listening/listening-watashi-sushi-suki.mp3',
    transcript: 'わたしはすしがすきです。',
    reading: 'わたしはすしがすきです。',
    translation: 'I like sushi.',
    focusPoint: 'Hear the liked thing before が, then catch すきです at the end.',
    difficulty: 'easy',
  },
  {
    id: 'listening-koohii-kirai',
    audioRef: '/audio/listening/listening-koohii-kirai.mp3',
    transcript: 'わたしはコーヒーがきらいです。',
    reading: 'わたしはコーヒーがきらいです。',
    translation: 'I dislike coffee.',
    focusPoint: 'Notice が before the target noun phrase and listen for きらいです.',
    difficulty: 'easy',
  },
  {
    id: 'listening-ongaku-suki',
    audioRef: '/audio/listening/listening-ongaku-suki.mp3',
    transcript: 'おんがくがすきです。',
    reading: 'おんがくがすきです。',
    translation: 'I like music.',
    focusPoint: 'Catch the short pattern noun plus が plus すきです.',
    difficulty: 'easy',
  },
  {
    id: 'listening-nani-suki',
    audioRef: '/audio/listening/listening-nani-suki.mp3',
    transcript: 'なにがすきですか。',
    reading: 'なにがすきですか。',
    translation: 'What do you like?',
    focusPoint: 'Hear the question word なに and the polite question ending か.',
    difficulty: 'easy',
  },
  {
    id: 'listening-tabemono-nani-suki',
    audioRef: '/audio/listening/listening-tabemono-nani-suki.mp3',
    transcript: 'たべものはなにがすきですか。',
    reading: 'たべものはなにがすきですか。',
    translation: 'What food do you like?',
    focusPoint: 'Notice the category topic は first, then the question phrase なにが.',
    difficulty: 'medium',
  },
  {
    id: 'listening-toire-doko',
    audioRef: '/audio/listening/listening-toire-doko.mp3',
    transcript: 'トイレはどこですか。',
    reading: 'トイレはどこですか。',
    translation: 'Where is the bathroom?',
    focusPoint: 'Catch the location question どこですか after the topic は.',
    difficulty: 'easy',
  },
  {
    id: 'listening-toire-asoko',
    audioRef: '/audio/listening/listening-toire-asoko.mp3',
    transcript: 'トイレはあそこです。',
    reading: 'トイレはあそこです。',
    translation: 'The bathroom is over there.',
    focusPoint: 'Listen for the short location answer あそこです.',
    difficulty: 'easy',
  },
  {
    id: 'listening-kagi-doko',
    audioRef: '/audio/listening/listening-kagi-doko.mp3',
    transcript: 'かぎはどこですか。',
    reading: 'かぎはどこですか。',
    translation: 'Where is the key?',
    focusPoint: 'Hear the topic first, then the full where-question pattern.',
    difficulty: 'easy',
  },
  {
    id: 'listening-kagi-tsukue-ue',
    audioRef: '/audio/listening/listening-kagi-tsukue-ue.mp3',
    transcript: 'かぎはつくえのうえにあります。',
    reading: 'かぎはつくえのうえにあります。',
    translation: 'The key is on the desk.',
    focusPoint: 'Notice the full location phrase つくえのうえに before あります.',
    difficulty: 'medium',
  },
  {
    id: 'listening-sensei-jimusho',
    audioRef: '/audio/listening/listening-sensei-jimusho.mp3',
    transcript: 'せんせいはじむしょにいます。',
    reading: 'せんせいはじむしょにいます。',
    translation: 'The teacher is in the office.',
    focusPoint: 'Catch the place with に and the animate existence verb います.',
    difficulty: 'medium',
  },
  {
    id: 'listening-kore-watashi-no-hon',
    audioRef: '/audio/listening/listening-kore-watashi-no-hon.mp3',
    transcript: 'これはわたしのほんです。',
    reading: 'これはわたしのほんです。',
    translation: 'This is my book.',
    focusPoint: 'Hear how の links the owner to the object before the final です.',
    difficulty: 'easy',
  },
  {
    id: 'listening-sore-ane-no-kaban',
    audioRef: '/audio/listening/listening-sore-ane-no-kaban.mp3',
    transcript: 'それはあねのかばんです。',
    reading: 'それはあねのかばんです。',
    translation: "That is my older sister's bag.",
    focusPoint: 'Catch the family noun first, then hear の linking it to かばん.',
    difficulty: 'easy',
  },
  {
    id: 'listening-kore-chichi-no-kamera',
    audioRef: '/audio/listening/listening-kore-chichi-no-kamera.mp3',
    transcript: 'これはちちのカメラです。',
    reading: 'これはちちのカメラです。',
    translation: "This is my father's camera.",
    focusPoint: 'Listen for the owner phrase ちちの before the object noun カメラ.',
    difficulty: 'easy',
  },
  {
    id: 'listening-kore-kazoku-no-shashin',
    audioRef: '/audio/listening/listening-kore-kazoku-no-shashin.mp3',
    transcript: 'これはかぞくのしゃしんです。',
    reading: 'これはかぞくのしゃしんです。',
    translation: 'This is a family photo.',
    focusPoint: 'Notice how かぞくのしゃしん forms one noun phrase before です.',
    difficulty: 'medium',
  },
  {
    id: 'listening-sore-haha-no-kasa',
    audioRef: '/audio/listening/listening-sore-haha-no-kasa.mp3',
    transcript: 'それはははのかさです。',
    reading: 'それはははのかさです。',
    translation: "That is my mother's umbrella.",
    focusPoint: 'Hear それは first, then the ownership phrase before the final noun.',
    difficulty: 'easy',
  },
  {
    id: 'listening-asa-pan-tabemasu',
    audioRef: '/audio/listening/listening-asa-pan-tabemasu.mp3',
    transcript: 'あさパンをたべます。',
    reading: 'あさパンをたべます。',
    translation: 'I eat bread in the morning.',
    focusPoint: 'Catch the morning time word first, then the object and polite verb.',
    difficulty: 'easy',
  },
  {
    id: 'listening-yoru-hon-yomimasu',
    audioRef: '/audio/listening/listening-yoru-hon-yomimasu.mp3',
    transcript: 'よるほんをよみます。',
    reading: 'よるほんをよみます。',
    translation: 'I read a book at night.',
    focusPoint: 'Listen for the time word よる, then hear the object before よみます.',
    difficulty: 'easy',
  },
  {
    id: 'listening-uchi-terebi-mimasu',
    audioRef: '/audio/listening/listening-uchi-terebi-mimasu.mp3',
    transcript: 'うちでテレビをみます。',
    reading: 'うちでテレビをみます。',
    translation: 'I watch TV at home.',
    focusPoint: 'Notice the place particle で before the object and polite verb.',
    difficulty: 'medium',
  },
  {
    id: 'listening-kyou-koohii-nomimasen',
    audioRef: '/audio/listening/listening-kyou-koohii-nomimasen.mp3',
    transcript: 'きょうコーヒーをのみません。',
    reading: 'きょうコーヒーをのみません。',
    translation: 'I do not drink coffee today.',
    focusPoint: 'Listen for the negative ending ません after the object phrase.',
    difficulty: 'medium',
  },
  {
    id: 'listening-ashita-toshokan-ikimasen',
    audioRef: '/audio/listening/listening-ashita-toshokan-ikimasen.mp3',
    transcript: 'あしたとしょかんにいきません。',
    reading: 'あしたとしょかんにいきません。',
    translation: 'I am not going to the library tomorrow.',
    focusPoint: 'Catch the destination with に, then hear the negative polite ending in いきません.',
    difficulty: 'medium',
  },
  {
    id: 'listening-hon-omoshiroi',
    audioRef: '/audio/listening/listening-hon-omoshiroi.mp3',
    transcript: 'ほんはおもしろいです。',
    reading: 'ほんはおもしろいです。',
    translation: 'The book is interesting.',
    focusPoint: 'Catch the topic first, then hear the adjective before the polite ending です.',
    difficulty: 'easy',
  },
  {
    id: 'listening-kaban-ookii',
    audioRef: '/audio/listening/listening-kaban-ookii.mp3',
    transcript: 'かばんはおおきいです。',
    reading: 'かばんはおおきいです。',
    translation: 'The bag is big.',
    focusPoint: 'Listen for the bag first, then the い-adjective おおきい.',
    difficulty: 'easy',
  },
  {
    id: 'listening-heya-shizuka',
    audioRef: '/audio/listening/listening-heya-shizuka.mp3',
    transcript: 'へやはしずかです。',
    reading: 'へやはしずかです。',
    translation: 'The room is quiet.',
    focusPoint: 'Notice that the line ends with しずかです as a short polite description.',
    difficulty: 'easy',
  },
  {
    id: 'listening-kamera-atarashii',
    audioRef: '/audio/listening/listening-kamera-atarashii.mp3',
    transcript: 'カメラはあたらしいです。',
    reading: 'カメラはあたらしいです。',
    translation: 'The camera is new.',
    focusPoint: 'Catch the object first, then hear the adjective あたらしい before です.',
    difficulty: 'easy',
  },
  {
    id: 'listening-kirei-mise',
    audioRef: '/audio/listening/listening-kirei-mise.mp3',
    transcript: 'きれいなみせです。',
    reading: 'きれいなみせです。',
    translation: 'It is a pretty shop.',
    focusPoint: 'Listen for the noun phrase きれいなみせ as one description unit.',
    difficulty: 'medium',
  },
  {
    id: 'listening-kinou-hon-yomimashita',
    audioRef: '/audio/listening/listening-kinou-hon-yomimashita.mp3',
    transcript: 'きのうほんをよみました。',
    reading: 'きのうほんをよみました。',
    translation: 'I read a book yesterday.',
    focusPoint: 'Catch the time word きのう first, then listen for the past ending ました.',
    difficulty: 'easy',
  },
  {
    id: 'listening-asa-pan-tabemashita',
    audioRef: '/audio/listening/listening-asa-pan-tabemashita.mp3',
    transcript: 'あさパンをたべました。',
    reading: 'あさパンをたべました。',
    translation: 'I ate bread in the morning.',
    focusPoint: 'Notice the familiar food line, but with the completed-action ending ました.',
    difficulty: 'easy',
  },
  {
    id: 'listening-kafe-koohii-nomimashita',
    audioRef: '/audio/listening/listening-kafe-koohii-nomimashita.mp3',
    transcript: 'カフェでコーヒーをのみました。',
    reading: 'カフェでコーヒーをのみました。',
    translation: 'I drank coffee at a cafe.',
    focusPoint: 'Listen for the place with で, then catch the object before the past verb.',
    difficulty: 'medium',
  },
  {
    id: 'listening-kyou-toshokan-ikimashita',
    audioRef: '/audio/listening/listening-kyou-toshokan-ikimashita.mp3',
    transcript: 'きょうとしょかんにいきました。',
    reading: 'きょうとしょかんにいきました。',
    translation: 'I went to the library today.',
    focusPoint: 'Catch the destination with に, then hear いきました as a completed action.',
    difficulty: 'medium',
  },
  {
    id: 'listening-kinou-koohii-nomimasendeshita',
    audioRef: '/audio/listening/listening-kinou-koohii-nomimasendeshita.mp3',
    transcript: 'きのうコーヒーをのみませんでした。',
    reading: 'きのうコーヒーをのみませんでした。',
    translation: 'I did not drink coffee yesterday.',
    focusPoint: 'Listen for the longer negative-past ending ませんでした after the object phrase.',
    difficulty: 'medium',
  },
  {
    id: 'listening-mizu-nonde-mo-ii',
    audioRef: '/audio/listening/listening-mizu-nonde-mo-ii.mp3',
    transcript: 'みずをのんでもいいですか。',
    reading: 'みずをのんでもいいですか。',
    translation: 'May I drink water?',
    focusPoint: 'Catch the permission ending もいいですか after the て-form verb.',
    difficulty: 'easy',
  },
  {
    id: 'listening-toire-itte-mo-ii',
    audioRef: '/audio/listening/listening-toire-itte-mo-ii.mp3',
    transcript: 'トイレにいってもいいですか。',
    reading: 'トイレにいってもいいですか。',
    translation: 'May I go to the bathroom?',
    focusPoint: 'Listen for the destination with に, then the permission pattern いってもいいですか.',
    difficulty: 'medium',
  },
  {
    id: 'listening-chotto-matte-kudasai',
    audioRef: '/audio/listening/listening-chotto-matte-kudasai.mp3',
    transcript: 'ちょっとまってください。',
    reading: 'ちょっとまってください。',
    translation: 'Please wait a moment.',
    focusPoint: 'Catch the short request ending ください after the て-form verb.',
    difficulty: 'easy',
  },
  {
    id: 'listening-koko-suwatte-kudasai',
    audioRef: '/audio/listening/listening-koko-suwatte-kudasai.mp3',
    transcript: 'ここにすわってください。',
    reading: 'ここにすわってください。',
    translation: 'Please sit here.',
    focusPoint: 'Listen for the place with に before the request ending ください.',
    difficulty: 'easy',
  },
  {
    id: 'listening-yukkuri-yonde-kudasai',
    audioRef: '/audio/listening/listening-yukkuri-yonde-kudasai.mp3',
    transcript: 'ゆっくりよんでください。',
    reading: 'ゆっくりよんでください。',
    translation: 'Please read slowly.',
    focusPoint: 'Catch the adverb ゆっくり first, then the て-form request ending ください.',
    difficulty: 'medium',
  },
  {
    id: 'listening-kore-o-kudasai',
    audioRef: '/audio/listening/listening-kore-o-kudasai.mp3',
    transcript: 'これをください。',
    reading: 'これをください。',
    translation: 'Please give me this.',
    focusPoint: 'Catch the object marker を before the short shopping request ください.',
    difficulty: 'easy',
  },
  {
    id: 'listening-kono-hon-o-kudasai',
    audioRef: '/audio/listening/listening-kono-hon-o-kudasai.mp3',
    transcript: 'このほんをください。',
    reading: 'このほんをください。',
    translation: 'Please give me this book.',
    focusPoint: 'Listen for この before the noun, then the object marker を before ください.',
    difficulty: 'easy',
  },
  {
    id: 'listening-mizu-o-kaimasu',
    audioRef: '/audio/listening/listening-mizu-o-kaimasu.mp3',
    transcript: 'みずをかいます。',
    reading: 'みずをかいます。',
    translation: 'I buy water.',
    focusPoint: 'Catch the familiar object phrase, then hear the shopping verb かいます.',
    difficulty: 'easy',
  },
  {
    id: 'listening-nani-o-kaimasu',
    audioRef: '/audio/listening/listening-nani-o-kaimasu.mp3',
    transcript: 'なにをかいますか。',
    reading: 'なにをかいますか。',
    translation: 'What do you buy?',
    focusPoint: 'Listen for the question word なに before をかいますか.',
    difficulty: 'easy',
  },
  {
    id: 'listening-konbini-de-okashi-o-kaimasu',
    audioRef: '/audio/listening/listening-konbini-de-okashi-o-kaimasu.mp3',
    transcript: 'コンビニでおかしをかいます。',
    reading: 'コンビニでおかしをかいます。',
    translation: 'I buy snacks at the convenience store.',
    focusPoint: 'Catch the place with で first, then the object phrase before かいます.',
    difficulty: 'medium',
  },
  {
    id: 'listening-nanji-desu-ka',
    audioRef: '/audio/listening/listening-nanji-desu-ka.mp3',
    transcript: 'なんじですか。',
    reading: 'なんじですか。',
    translation: 'What time is it?',
    focusPoint: 'Catch the short time-question pattern ending with ですか.',
    difficulty: 'easy',
  },
  {
    id: 'listening-gozen-hachiji-desu',
    audioRef: '/audio/listening/listening-gozen-hachiji-desu.mp3',
    transcript: 'ごぜんはちじです。',
    reading: 'ごぜんはちじです。',
    translation: 'It is 8 AM.',
    focusPoint: 'Listen for the morning marker ごぜん before the clock time.',
    difficulty: 'easy',
  },
  {
    id: 'listening-hachiji-ni-gakkou-ikimasu',
    audioRef: '/audio/listening/listening-hachiji-ni-gakkou-ikimasu.mp3',
    transcript: 'はちじにがっこうにいきます。',
    reading: 'はちじにがっこうにいきます。',
    translation: 'I go to school at eight o’clock.',
    focusPoint: 'Catch the time phrase with に first, then the destination phrase with に.',
    difficulty: 'medium',
  },
  {
    id: 'listening-kuji-ni-nihongo-benkyoushimasu',
    audioRef: '/audio/listening/listening-kuji-ni-nihongo-benkyoushimasu.mp3',
    transcript: 'くじににほんごをべんきょうします。',
    reading: 'くじににほんごをべんきょうします。',
    translation: 'I study Japanese at nine o’clock.',
    focusPoint: 'Listen for the time phrase before the object and study verb.',
    difficulty: 'medium',
  },
  {
    id: 'listening-yoru-juuji-ni-nemasu',
    audioRef: '/audio/listening/listening-yoru-juuji-ni-nemasu.mp3',
    transcript: 'よるじゅうじにねます。',
    reading: 'よるじゅうじにねます。',
    translation: 'I go to bed at ten at night.',
    focusPoint: 'Catch the night expression first, then the time with に before ねます.',
    difficulty: 'medium',
  },
  {
    id: 'listening-getsuyoubi-ni-gakkou-ikimasu',
    audioRef: '/audio/listening/listening-getsuyoubi-ni-gakkou-ikimasu.mp3',
    transcript: 'げつようびにがっこうにいきます。',
    reading: 'げつようびにがっこうにいきます。',
    translation: 'I go to school on Monday.',
    focusPoint: 'Catch the weekday first, then the destination phrase with に before いきます.',
    difficulty: 'medium',
  },
  {
    id: 'listening-mokuyoubi-ni-nihongo-o-benkyoushimasu',
    audioRef: '/audio/listening/listening-mokuyoubi-ni-nihongo-o-benkyoushimasu.mp3',
    transcript: 'もくようびににほんごをべんきょうします。',
    reading: 'もくようびににほんごをべんきょうします。',
    translation: 'I study Japanese on Thursday.',
    focusPoint: 'Listen for the weekday with に before the object and study verb.',
    difficulty: 'medium',
  },
  {
    id: 'listening-doyoubi-ni-nani-o-shimasu-ka',
    audioRef: '/audio/listening/listening-doyoubi-ni-nani-o-shimasu-ka.mp3',
    transcript: 'どようびになにをしますか。',
    reading: 'どようびになにをしますか。',
    translation: 'What do you do on Saturday?',
    focusPoint: 'Catch the weekday phrase first, then the question pattern なにをしますか.',
    difficulty: 'easy',
  },
  {
    id: 'listening-nichiyoubi-wa-uchi-de-yasumimasu',
    audioRef: '/audio/listening/listening-nichiyoubi-wa-uchi-de-yasumimasu.mp3',
    transcript: 'にちようびはうちでやすみます。',
    reading: 'にちようびはうちでやすみます。',
    translation: 'I rest at home on Sunday.',
    focusPoint: 'Listen for the topic marker は after the weekday, then the place with で.',
    difficulty: 'medium',
  },
  {
    id: 'listening-raishuu-doyoubi-ni-toshokan-ni-ikimasu',
    audioRef: '/audio/listening/listening-raishuu-doyoubi-ni-toshokan-ni-ikimasu.mp3',
    transcript: 'らいしゅうどようびにとしょかんにいきます。',
    reading: 'らいしゅうどようびにとしょかんにいきます。',
    translation: 'I go to the library next Saturday.',
    focusPoint: 'Catch the next-week expression first, then the weekday and destination phrases.',
    difficulty: 'medium',
  },
  {
    id: 'listening-basu-de-ikimasu',
    audioRef: '/audio/listening/listening-basu-de-ikimasu.mp3',
    transcript: 'バスでいきます。',
    reading: 'バスでいきます。',
    translation: 'I go by bus.',
    focusPoint: 'Listen for the transport method before the movement verb.',
    difficulty: 'easy',
  },
  {
    id: 'listening-densha-de-kaisha-ni-ikimasu',
    audioRef: '/audio/listening/listening-densha-de-kaisha-ni-ikimasu.mp3',
    transcript: 'でんしゃでかいしゃにいきます。',
    reading: 'でんしゃでかいしゃにいきます。',
    translation: 'I go to the office by train.',
    focusPoint: 'Catch the transport phrase with で first, then the destination phrase with に.',
    difficulty: 'medium',
  },
  {
    id: 'listening-doko-made-ikimasu-ka',
    audioRef: '/audio/listening/listening-doko-made-ikimasu-ka.mp3',
    transcript: 'どこまでいきますか。',
    reading: 'どこまでいきますか。',
    translation: 'How far are you going?',
    focusPoint: 'Listen for the destination question pattern with まで before いきますか.',
    difficulty: 'easy',
  },
  {
    id: 'listening-eki-made-arukimasu',
    audioRef: '/audio/listening/listening-eki-made-arukimasu.mp3',
    transcript: 'えきまであるきます。',
    reading: 'えきまであるきます。',
    translation: 'I walk to the station.',
    focusPoint: 'Catch the destination phrase with まで before the walking verb.',
    difficulty: 'medium',
  },
  {
    id: 'listening-takushii-de-kuukou-ni-ikimasu',
    audioRef: '/audio/listening/listening-takushii-de-kuukou-ni-ikimasu.mp3',
    transcript: 'タクシーでくうこうにいきます。',
    reading: 'タクシーでくうこうにいきます。',
    translation: 'I go to the airport by taxi.',
    focusPoint: 'Listen for the transport method with で, then the airport destination with に.',
    difficulty: 'medium',
  },
  {
    id: 'listening-migi-ni-magarimasu',
    audioRef: '/audio/listening/listening-migi-ni-magarimasu.mp3',
    transcript: 'みぎにまがります。',
    reading: 'みぎにまがります。',
    translation: 'Turn right.',
    focusPoint: 'Catch the direction word before the turning verb.',
    difficulty: 'easy',
  },
  {
    id: 'listening-massugu-ikimasu',
    audioRef: '/audio/listening/listening-massugu-ikimasu.mp3',
    transcript: 'まっすぐいきます。',
    reading: 'まっすぐいきます。',
    translation: 'Go straight.',
    focusPoint: 'Listen for the straight-ahead expression before いきます.',
    difficulty: 'easy',
  },
  {
    id: 'listening-eki-wa-doko-desu-ka',
    audioRef: '/audio/listening/listening-eki-wa-doko-desu-ka.mp3',
    transcript: 'えきはどこですか。',
    reading: 'えきはどこですか。',
    translation: 'Where is the station?',
    focusPoint: 'Catch the place topic first, then the short location question pattern.',
    difficulty: 'easy',
  },
  {
    id: 'listening-eki-wa-asoko-desu',
    audioRef: '/audio/listening/listening-eki-wa-asoko-desu.mp3',
    transcript: 'えきはあそこです。',
    reading: 'えきはあそこです。',
    translation: 'The station is over there.',
    focusPoint: 'Listen for the topic marker は, then the short place answer あそこです.',
    difficulty: 'easy',
  },
  {
    id: 'listening-shingou-de-hidari-ni-magarimasu',
    audioRef: '/audio/listening/listening-shingou-de-hidari-ni-magarimasu.mp3',
    transcript: 'しんごうでひだりにまがります。',
    reading: 'しんごうでひだりにまがります。',
    translation: 'Turn left at the traffic light.',
    focusPoint: 'Catch the landmark phrase first, then the left-turn direction.',
    difficulty: 'medium',
  },
  {
    id: 'listening-issho-ni-ikimasu-ka',
    audioRef: '/audio/listening/listening-issho-ni-ikimasu-ka.mp3',
    transcript: 'いっしょにいきますか。',
    reading: 'いっしょにいきますか。',
    translation: 'Will you go together?',
    focusPoint: 'Catch いっしょに before the verb, then hear the short polite question ending.',
    difficulty: 'easy',
  },
  {
    id: 'listening-doyoubi-ni-ikimasu-ka',
    audioRef: '/audio/listening/listening-doyoubi-ni-ikimasu-ka.mp3',
    transcript: 'どようびにいきますか。',
    reading: 'どようびにいきますか。',
    translation: 'Are you going on Saturday?',
    focusPoint: 'Listen for the weekday phrase first, then the movement verb in question form.',
    difficulty: 'easy',
  },
  {
    id: 'listening-nanji-ni-aimasu-ka',
    audioRef: '/audio/listening/listening-nanji-ni-aimasu-ka.mp3',
    transcript: 'なんじにあいますか。',
    reading: 'なんじにあいますか。',
    translation: 'What time shall we meet?',
    focusPoint: 'Catch the time question なんじ, then listen for に before あいますか.',
    difficulty: 'medium',
  },
  {
    id: 'listening-hai-ikimasu',
    audioRef: '/audio/listening/listening-hai-ikimasu.mp3',
    transcript: 'はい、いきます。',
    reading: 'はい、いきます。',
    translation: 'Yes, I will go.',
    focusPoint: 'Hear the short yes response first, then the polite verb いきます.',
    difficulty: 'easy',
  },
  {
    id: 'listening-iie-ikimasen',
    audioRef: '/audio/listening/listening-iie-ikimasen.mp3',
    transcript: 'いいえ、いきません。',
    reading: 'いいえ、いきません。',
    translation: 'No, I will not go.',
    focusPoint: 'Catch the short no response first, then the negative polite ending いきません.',
    difficulty: 'easy',
  },
  {
    id: 'listening-doko-de-aimasu-ka',
    audioRef: '/audio/listening/listening-doko-de-aimasu-ka.mp3',
    transcript: 'どこであいますか。',
    reading: 'どこであいますか。',
    translation: 'Where should we meet?',
    focusPoint: 'Catch the question word どこ first, then listen for the meeting-place particle で.',
    difficulty: 'easy',
  },
  {
    id: 'listening-eki-de-aimasu',
    audioRef: '/audio/listening/listening-eki-de-aimasu.mp3',
    transcript: 'えきであいます。',
    reading: 'えきであいます。',
    translation: 'We will meet at the station.',
    focusPoint: 'Listen for the place noun first, then catch で before あいます.',
    difficulty: 'easy',
  },
  {
    id: 'listening-ekimae-de-aimasu',
    audioRef: '/audio/listening/listening-ekimae-de-aimasu.mp3',
    transcript: 'えきまえであいます。',
    reading: 'えきまえであいます。',
    translation: 'We will meet in front of the station.',
    focusPoint: 'Catch えきまえ as one place phrase before であいます.',
    difficulty: 'easy',
  },
  {
    id: 'listening-kouen-no-iriguchi-de-aimasu',
    audioRef: '/audio/listening/listening-kouen-no-iriguchi-de-aimasu.mp3',
    transcript: 'こうえんのいりぐちであいます。',
    reading: 'こうえんのいりぐちであいます。',
    translation: 'We will meet at the park entrance.',
    focusPoint: 'Listen for the landmark phrase こうえんのいりぐち before the meeting verb.',
    difficulty: 'medium',
  },
  {
    id: 'listening-biru-no-deguchi-de-aimasu',
    audioRef: '/audio/listening/listening-biru-no-deguchi-de-aimasu.mp3',
    transcript: 'ビルのでぐちであいます。',
    reading: 'ビルのでぐちであいます。',
    translation: 'We will meet at the building exit.',
    focusPoint: 'Catch the place phrase first, then hear で right before あいます.',
    difficulty: 'medium',
  },
  {
    id: 'listening-tsukimashita',
    audioRef: '/audio/listening/listening-tsukimashita.mp3',
    transcript: 'つきました。',
    reading: 'つきました。',
    translation: 'I arrived.',
    focusPoint: 'Catch the short past-form arrival update as one compact status line.',
    difficulty: 'easy',
  },
  {
    id: 'listening-ima-eki-desu',
    audioRef: '/audio/listening/listening-ima-eki-desu.mp3',
    transcript: 'いまえきです。',
    reading: 'いまえきです。',
    translation: 'I am at the station now.',
    focusPoint: 'Listen for いま first, then catch the short current-location status line.',
    difficulty: 'easy',
  },
  {
    id: 'listening-eki-de-matteimasu',
    audioRef: '/audio/listening/listening-eki-de-matteimasu.mp3',
    transcript: 'えきでまっています。',
    reading: 'えきでまっています。',
    translation: 'I am waiting at the station.',
    focusPoint: 'Catch the waiting place first, then hear the long waiting verb まっています.',
    difficulty: 'easy',
  },
  {
    id: 'listening-kaisatsu-no-mae-de-matteimasu',
    audioRef: '/audio/listening/listening-kaisatsu-no-mae-de-matteimasu.mp3',
    transcript: 'かいさつのまえでまっています。',
    reading: 'かいさつのまえでまっています。',
    translation: 'I am waiting in front of the ticket gate.',
    focusPoint: 'Listen for the landmark phrase かいさつのまえ before the waiting verb.',
    difficulty: 'medium',
  },
  {
    id: 'listening-sugu-ikimasu',
    audioRef: '/audio/listening/listening-sugu-ikimasu.mp3',
    transcript: 'すぐいきます。',
    reading: 'すぐいきます。',
    translation: 'I will go soon.',
    focusPoint: 'Catch すぐ first, then the short movement update いきます.',
    difficulty: 'easy',
  },
  {
    id: 'listening-issho-ni-eiga-o-mimasen-ka',
    audioRef: '/audio/listening/listening-issho-ni-eiga-o-mimasen-ka.mp3',
    transcript: 'いっしょにえいがをみませんか。',
    reading: 'いっしょにえいがをみませんか。',
    translation: 'Won’t you watch a movie together?',
    focusPoint: 'Catch いっしょに first, then hear the polite suggestion ending ませんか.',
    difficulty: 'medium',
  },
  {
    id: 'listening-rokuji-ni-aimasen-ka',
    audioRef: '/audio/listening/listening-rokuji-ni-aimasen-ka.mp3',
    transcript: 'ろくじにあいませんか。',
    reading: 'ろくじにあいませんか。',
    translation: 'Won’t you meet at six?',
    focusPoint: 'Listen for the time phrase first, then catch the suggestion ending ませんか.',
    difficulty: 'medium',
  },
  {
    id: 'listening-konya-resutoran-ni-ikimasen-ka',
    audioRef: '/audio/listening/listening-konya-resutoran-ni-ikimasen-ka.mp3',
    transcript: 'こんやレストランにいきませんか。',
    reading: 'こんやレストランにいきませんか。',
    translation: 'Won’t you go to the restaurant tonight?',
    focusPoint: 'Catch こんや first, then hear the destination phrase before いきませんか.',
    difficulty: 'medium',
  },
  {
    id: 'listening-koohii-o-nomimasen-ka',
    audioRef: '/audio/listening/listening-koohii-o-nomimasen-ka.mp3',
    transcript: 'コーヒーをのみませんか。',
    reading: 'コーヒーをのみませんか。',
    translation: 'Won’t you drink coffee?',
    focusPoint: 'Listen for the object first, then catch the polite suggestion ending.',
    difficulty: 'easy',
  },
  {
    id: 'listening-issho-ni-benkyoushimasen-ka',
    audioRef: '/audio/listening/listening-issho-ni-benkyoushimasen-ka.mp3',
    transcript: 'いっしょにべんきょうしませんか。',
    reading: 'いっしょにべんきょうしませんか。',
    translation: 'Won’t you study together?',
    focusPoint: 'Catch いっしょに first, then listen for the long verb phrase べんきょうしませんか.',
    difficulty: 'medium',
  },
  {
    id: 'listening-rokuji-ni-aimashou',
    audioRef: '/audio/listening/listening-rokuji-ni-aimashou.mp3',
    transcript: 'ろくじにあいましょう。',
    reading: 'ろくじにあいましょう。',
    translation: 'Let’s meet at six.',
    focusPoint: 'Catch the time phrase first, then hear the proposal ending ましょう.',
    difficulty: 'easy',
  },
  {
    id: 'listening-doyoubi-ni-eigakan-ni-ikimashou',
    audioRef: '/audio/listening/listening-doyoubi-ni-eigakan-ni-ikimashou.mp3',
    transcript: 'どようびにえいがかんにいきましょう。',
    reading: 'どようびにえいがかんにいきましょう。',
    translation: 'Let’s go to the movie theater on Saturday.',
    focusPoint: 'Listen for the weekday first, then the destination before いきましょう.',
    difficulty: 'medium',
  },
  {
    id: 'listening-eki-de-aimashou',
    audioRef: '/audio/listening/listening-eki-de-aimashou.mp3',
    transcript: 'えきであいましょう。',
    reading: 'えきであいましょう。',
    translation: 'Let’s meet at the station.',
    focusPoint: 'Catch the meeting place first, then hear the proposal ending ましょう.',
    difficulty: 'easy',
  },
  {
    id: 'listening-nani-o-shimashou-ka',
    audioRef: '/audio/listening/listening-nani-o-shimashou-ka.mp3',
    transcript: 'なにをしましょうか。',
    reading: 'なにをしましょうか。',
    translation: 'What shall we do?',
    focusPoint: 'Catch the question word なに first, then listen for the planning question ending ましょうか.',
    difficulty: 'easy',
  },
  {
    id: 'listening-ashita-toshokan-ni-ikimashou-ka',
    audioRef: '/audio/listening/listening-ashita-toshokan-ni-ikimashou-ka.mp3',
    transcript: 'あしたとしょかんにいきましょうか。',
    reading: 'あしたとしょかんにいきましょうか。',
    translation: 'Shall we go to the library tomorrow?',
    focusPoint: 'Listen for あした first, then catch the proposal-question ending ましょうか.',
    difficulty: 'medium',
  },
  {
    id: 'listening-jugyou-wa-kuji-kara-desu',
    audioRef: '/audio/listening/listening-jugyou-wa-kuji-kara-desu.mp3',
    transcript: 'じゅぎょうはくじからです。',
    reading: 'じゅぎょうはくじからです。',
    translation: 'Class starts at nine.',
    focusPoint: 'Catch the topic first, then listen for くじから as one start-time phrase.',
    difficulty: 'easy',
  },
  {
    id: 'listening-shigoto-wa-goji-made-desu',
    audioRef: '/audio/listening/listening-shigoto-wa-goji-made-desu.mp3',
    transcript: 'しごとはごじまでです。',
    reading: 'しごとはごじまでです。',
    translation: 'Work is until five.',
    focusPoint: 'Listen for the schedule noun first, then catch ごじまで as the end time.',
    difficulty: 'easy',
  },
  {
    id: 'listening-jugyou-wa-kuji-kara-juuji-made-desu',
    audioRef: '/audio/listening/listening-jugyou-wa-kuji-kara-juuji-made-desu.mp3',
    transcript: 'じゅぎょうはくじからじゅうじまでです。',
    reading: 'じゅぎょうはくじからじゅうじまでです。',
    translation: 'Class is from nine to ten.',
    focusPoint: 'Catch both ends of the range: くじから first, then じゅうじまで.',
    difficulty: 'medium',
  },
  {
    id: 'listening-nanji-kara-desu-ka',
    audioRef: '/audio/listening/listening-nanji-kara-desu-ka.mp3',
    transcript: 'なんじからですか。',
    reading: 'なんじからですか。',
    translation: 'What time does it start?',
    focusPoint: 'Listen for the short start-time question with から before ですか.',
    difficulty: 'easy',
  },
  {
    id: 'listening-nanji-kara-nanji-made-desu-ka',
    audioRef: '/audio/listening/listening-nanji-kara-nanji-made-desu-ka.mp3',
    transcript: 'なんじからなんじまでですか。',
    reading: 'なんじからなんじまでですか。',
    translation: 'From what time until what time is it?',
    focusPoint: 'Catch the full range question by listening for both から and まで.',
    difficulty: 'medium',
  },
  {
    id: 'listening-itsu-aimasu-ka',
    audioRef: '/audio/listening/listening-itsu-aimasu-ka.mp3',
    transcript: 'いつあいますか。',
    reading: 'いつあいますか。',
    translation: 'When will we meet?',
    focusPoint: 'Catch いつ first, then hear the familiar meeting verb at the end.',
    difficulty: 'easy',
  },
  {
    id: 'listening-nangatsu-ni-ikimasu-ka',
    audioRef: '/audio/listening/listening-nangatsu-ni-ikimasu-ka.mp3',
    transcript: 'なんがつにいきますか。',
    reading: 'なんがつにいきますか。',
    translation: 'What month will you go?',
    focusPoint: 'Listen for the month question なんがつ, then catch に before いきますか.',
    difficulty: 'medium',
  },
  {
    id: 'listening-shigatsu-ni-aimasu',
    audioRef: '/audio/listening/listening-shigatsu-ni-aimasu.mp3',
    transcript: 'しがつにあいます。',
    reading: 'しがつにあいます。',
    translation: 'We will meet in April.',
    focusPoint: 'Catch the month phrase first, then hear the short meeting line.',
    difficulty: 'easy',
  },
  {
    id: 'listening-nannichi-ni-aimasu-ka',
    audioRef: '/audio/listening/listening-nannichi-ni-aimasu-ka.mp3',
    transcript: 'なんにちにあいますか。',
    reading: 'なんにちにあいますか。',
    translation: 'On what day of the month will we meet?',
    focusPoint: 'Listen for the day-of-month question なんにち before the meeting verb.',
    difficulty: 'medium',
  },
  {
    id: 'listening-gogatsu-youka-ni-toshokan-ni-ikimasu',
    audioRef: '/audio/listening/listening-gogatsu-youka-ni-toshokan-ni-ikimasu.mp3',
    transcript: 'ごがつようかにとしょかんにいきます。',
    reading: 'ごがつようかにとしょかんにいきます。',
    translation: 'I will go to the library on May eighth.',
    focusPoint: 'Catch the date phrase first, then listen for the destination after it.',
    difficulty: 'medium',
  },
  {
    id: 'listening-shigatsu-mikka-no-rokuji-ni-aimasu',
    audioRef: '/audio/listening/listening-shigatsu-mikka-no-rokuji-ni-aimasu.mp3',
    transcript: 'しがつみっかのろくじにあいます。',
    reading: 'しがつみっかのろくじにあいます。',
    translation: 'We will meet at six on April third.',
    focusPoint: 'Catch the date phrase first, then listen for の before the time phrase.',
    difficulty: 'medium',
  },
  {
    id: 'listening-raigetsu-futsuka-no-gogo-shichiji-ni-eki-de-aimasu',
    audioRef: '/audio/listening/listening-raigetsu-futsuka-no-gogo-shichiji-ni-eki-de-aimasu.mp3',
    transcript: 'らいげつふつかのごごしちじにえきであいます。',
    reading: 'らいげつふつかのごごしちじにえきであいます。',
    translation: 'We will meet at the station at seven PM on the second of next month.',
    focusPoint: 'Listen in chunks: date first, then time, then the meeting place at the end.',
    difficulty: 'medium',
  },
  {
    id: 'listening-itsu-aimashou-ka',
    audioRef: '/audio/listening/listening-itsu-aimashou-ka.mp3',
    transcript: 'いつあいましょうか。',
    reading: 'いつあいましょうか。',
    translation: 'When shall we meet?',
    focusPoint: 'Catch いつ first, then listen for the planning-question ending ましょうか.',
    difficulty: 'easy',
  },
  {
    id: 'listening-gogatsu-youka-ni-toshokan-ni-ikimashou-ka',
    audioRef: '/audio/listening/listening-gogatsu-youka-ni-toshokan-ni-ikimashou-ka.mp3',
    transcript: 'ごがつようかにとしょかんにいきましょうか。',
    reading: 'ごがつようかにとしょかんにいきましょうか。',
    translation: 'Shall we go to the library on May eighth?',
    focusPoint: 'Catch the date phrase first, then listen for the proposal-question ending ましょうか.',
    difficulty: 'medium',
  },
  {
    id: 'listening-raigetsu-futsuka-no-gogo-shichiji-ni-eiga-o-mimasen-ka',
    audioRef: '/audio/listening/listening-raigetsu-futsuka-no-gogo-shichiji-ni-eiga-o-mimasen-ka.mp3',
    transcript: 'らいげつふつかのごごしちじにえいがをみませんか。',
    reading: 'らいげつふつかのごごしちじにえいがをみませんか。',
    translation: 'Won’t you watch a movie at seven PM on the second of next month?',
    focusPoint: 'Listen for the date and time first, then catch the soft invitation ending みませんか.',
    difficulty: 'medium',
  },
  {
    id: 'listening-ikutsu-kaimasu-ka',
    audioRef: '/audio/listening/listening-ikutsu-kaimasu-ka.mp3',
    transcript: 'いくつかいますか。',
    reading: 'いくつかいますか。',
    translation: 'How many will you buy?',
    focusPoint: 'Catch いくつ first, then listen for the buying verb at the end.',
    difficulty: 'easy',
  },
  {
    id: 'listening-hitotsu-kudasai',
    audioRef: '/audio/listening/listening-hitotsu-kudasai.mp3',
    transcript: 'ひとつください。',
    reading: 'ひとつください。',
    translation: 'One, please.',
    focusPoint: 'Listen for the counter first, then the short request ending ください.',
    difficulty: 'easy',
  },
  {
    id: 'listening-futatsu-kudasai',
    audioRef: '/audio/listening/listening-futatsu-kudasai.mp3',
    transcript: 'ふたつください。',
    reading: 'ふたつください。',
    translation: 'Two, please.',
    focusPoint: 'Catch the counter ふたつ as one chunk before ください.',
    difficulty: 'easy',
  },
  {
    id: 'listening-pan-o-mittsu-kudasai',
    audioRef: '/audio/listening/listening-pan-o-mittsu-kudasai.mp3',
    transcript: 'パンをみっつください。',
    reading: 'パンをみっつください。',
    translation: 'Three breads, please.',
    focusPoint: 'Listen for the item first, then the counter, then ください.',
    difficulty: 'medium',
  },
  {
    id: 'listening-ringo-o-futatsu-kaimasu',
    audioRef: '/audio/listening/listening-ringo-o-futatsu-kaimasu.mp3',
    transcript: 'りんごをふたつかいます。',
    reading: 'りんごをふたつかいます。',
    translation: 'I will buy two apples.',
    focusPoint: 'Catch the item first, then hear the counter before the buying verb.',
    difficulty: 'medium',
  },
  {
    id: 'listening-kore-wa-ikura-desu-ka',
    audioRef: '/audio/listening/listening-kore-wa-ikura-desu-ka.mp3',
    transcript: 'これはいくらですか。',
    reading: 'これはいくらですか。',
    translation: 'How much is this?',
    focusPoint: 'Catch いくら in the middle of the sentence as the price question word.',
    difficulty: 'easy',
  },
  {
    id: 'listening-pan-wa-ikura-desu-ka',
    audioRef: '/audio/listening/listening-pan-wa-ikura-desu-ka.mp3',
    transcript: 'パンはいくらですか。',
    reading: 'パンはいくらですか。',
    translation: 'How much is the bread?',
    focusPoint: 'Listen for the item topic first, then catch いくらですか.',
    difficulty: 'easy',
  },
  {
    id: 'listening-kore-wa-hyaku-en-desu',
    audioRef: '/audio/listening/listening-kore-wa-hyaku-en-desu.mp3',
    transcript: 'これはひゃくえんです。',
    reading: 'これはひゃくえんです。',
    translation: 'This is 100 yen.',
    focusPoint: 'Catch the item topic first, then the fixed price expression ひゃくえん.',
    difficulty: 'easy',
  },
  {
    id: 'listening-pan-wa-nihyaku-en-desu',
    audioRef: '/audio/listening/listening-pan-wa-nihyaku-en-desu.mp3',
    transcript: 'パンはにひゃくえんです。',
    reading: 'パンはにひゃくえんです。',
    translation: 'The bread is 200 yen.',
    focusPoint: 'Listen for the item first, then hear the full price answer  にひゃくえんです.',
    difficulty: 'medium',
  },
  {
    id: 'listening-kono-hon-wa-gohyaku-en-desu',
    audioRef: '/audio/listening/listening-kono-hon-wa-gohyaku-en-desu.mp3',
    transcript: 'このほんはごひゃくえんです。',
    reading: 'このほんはごひゃくえんです。',
    translation: 'This book is 500 yen.',
    focusPoint: 'Catch このほん first, then hear the longer price expression ごひゃくえん.',
    difficulty: 'medium',
  },
  {
    id: 'listening-mizu-wa-arimasu-ka',
    audioRef: '/audio/listening/listening-mizu-wa-arimasu-ka.mp3',
    transcript: 'みずはありますか。',
    reading: 'みずはありますか。',
    translation: 'Do you have water?',
    focusPoint: 'Listen for the item first, then catch the availability question ending ありますか.',
    difficulty: 'easy',
  },
  {
    id: 'listening-kono-hon-wa-arimasu-ka',
    audioRef: '/audio/listening/listening-kono-hon-wa-arimasu-ka.mp3',
    transcript: 'このほんはありますか。',
    reading: 'このほんはありますか。',
    translation: 'Do you have this book?',
    focusPoint: 'Catch このほん first, then listen for the familiar existence verb in question form.',
    difficulty: 'medium',
  },
  {
    id: 'listening-hai-arimasu',
    audioRef: '/audio/listening/listening-hai-arimasu.mp3',
    transcript: 'はい、あります。',
    reading: 'はい、あります。',
    translation: 'Yes, we do.',
    focusPoint: 'Catch the short yes response first, then the simple availability answer あります.',
    difficulty: 'easy',
  },
  {
    id: 'listening-sore-o-kudasai',
    audioRef: '/audio/listening/listening-sore-o-kudasai.mp3',
    transcript: 'それをください。',
    reading: 'それをください。',
    translation: 'That one, please.',
    focusPoint: 'Listen for それ first, then catch を before the request ending.',
    difficulty: 'easy',
  },
  {
    id: 'listening-korede-ii-desu',
    audioRef: '/audio/listening/listening-korede-ii-desu.mp3',
    transcript: 'これでいいです。',
    reading: 'これでいいです。',
    translation: 'This is fine.',
    focusPoint: 'Catch これで as one chunk before the short decision ending いいです.',
    difficulty: 'easy',
  },
] satisfies ListeningItem[];
