import type { Mission } from '../lib/content/types';

export const missions = [
  {
    id: 'mission-grammar-topic-desu',
    type: 'grammar',
    title: 'Introduce yourself with は and です',
    targetSkill: 'sentence-structure',
    contentRefs: {
      grammarLessonIds: ['grammar-topic-desu'],
      vocabIds: ['vocab-watashi', 'vocab-gakusei', 'vocab-sensei'],
      exampleIds: ['ex-colin-desu', 'ex-student-desu', 'ex-teacher-question'],
    },
    estimatedMinutes: 7,
  },
  {
    id: 'mission-listening-place-de',
    type: 'listening',
    title: 'Hear where the action happens',
    targetSkill: 'listening-comprehension',
    contentRefs: {
      grammarLessonIds: ['grammar-place-de'],
      listeningItemIds: [
        'listening-home-study',
        'listening-cafe-coffee',
        'listening-teacher-question',
      ],
      exampleIds: ['ex-study-home', 'ex-coffee-cafe'],
    },
    estimatedMinutes: 6,
  },
  {
    id: 'mission-output-daily-lines',
    type: 'output',
    title: 'Write two short daily-life lines',
    targetSkill: 'output-confidence',
    contentRefs: {
      grammarLessonIds: ['grammar-topic-desu', 'grammar-place-de'],
      vocabIds: ['vocab-watashi', 'vocab-uchi', 'vocab-benkyoushimasu', 'vocab-kafe'],
      exampleIds: ['ex-colin-desu', 'ex-study-home', 'ex-coffee-cafe'],
    },
    estimatedMinutes: 8,
    unlockRules: {
      requiredMissionIds: ['mission-grammar-topic-desu'],
    },
    outputTasks: [
      {
        id: 'output-self-intro',
        prompt: 'Type a polite self-introduction line: "I am Colin."',
        acceptableAnswers: ['わたしはコリンです。', 'わたしはコリンです'],
        hint: 'Use は after the topic and finish with です.',
        evaluation: {
          tokenPatterns: [['わたし', 'は', 'コリン', 'です']],
        },
      },
      {
        id: 'output-home-study',
        prompt: 'Type a line that says: "I study Japanese at home."',
        acceptableAnswers: [
          'うちでにほんごをべんきょうします。',
          'うちでにほんごをべんきょうします',
        ],
        hint: 'Put the place with で before the object and verb.',
        evaluation: {
          tokenPatterns: [['うち', 'で', 'にほんご', 'を', 'べんきょうします']],
        },
      },
    ],
  },
  {
    id: 'mission-grammar-destination-ni',
    type: 'grammar',
    title: 'Say where someone goes with に',
    targetSkill: 'particles',
    contentRefs: {
      grammarLessonIds: ['grammar-destination-ni'],
      vocabIds: [
        'vocab-doko',
        'vocab-gakkou',
        'vocab-ikimasu',
        'vocab-mainichi',
        'vocab-kyou',
        'vocab-ima',
        'vocab-kyoushitsu',
        'vocab-toshokan',
      ],
      exampleIds: [
        'ex-doko-ikimasu',
        'ex-mainichi-gakkou',
        'ex-kyou-toshokan',
        'ex-ima-kyoushitsu',
      ],
    },
    estimatedMinutes: 7,
  },
  {
    id: 'mission-listening-question-nan',
    type: 'listening',
    title: 'Hear simple classroom questions',
    targetSkill: 'listening-comprehension',
    contentRefs: {
      grammarLessonIds: ['grammar-question-nan'],
      listeningItemIds: [
        'listening-kore-nan',
        'listening-kore-hon',
        'listening-sore-shukudai',
        'listening-kore-eigo-hon',
        'listening-sore-nan',
      ],
      exampleIds: [
        'ex-kore-hon',
        'ex-kore-nan',
        'ex-sore-shukudai',
        'ex-kore-eigo-hon',
      ],
    },
    estimatedMinutes: 7,
  },
  {
    id: 'mission-output-classroom-destination',
    type: 'output',
    title: 'Ask one question and write one destination line',
    targetSkill: 'output-confidence',
    contentRefs: {
      grammarLessonIds: ['grammar-question-nan', 'grammar-destination-ni'],
      vocabIds: [
        'vocab-kore',
        'vocab-nan',
        'vocab-gakkou',
        'vocab-ikimasu',
        'vocab-mainichi',
      ],
      exampleIds: [
        'ex-kore-nan',
        'ex-kore-hon',
        'ex-mainichi-gakkou',
        'ex-doko-ikimasu',
      ],
    },
    estimatedMinutes: 8,
    outputTasks: [
      {
        id: 'output-kore-nan',
        prompt: 'Type a polite classroom question: "What is this?"',
        acceptableAnswers: ['これはなんですか。', 'これはなんですか'],
        hint: 'Use これは first, then なんですか.',
        evaluation: {
          tokenPatterns: [['これ', 'は', 'なん', 'です', 'か']],
        },
      },
      {
        id: 'output-mainichi-gakkou',
        prompt: 'Type a line that says: "I go to school every day."',
        acceptableAnswers: [
          'まいにちがっこうにいきます。',
          'まいにちがっこうにいきます',
        ],
        hint: 'Put the destination with に before いきます.',
        evaluation: {
          tokenPatterns: [['まいにち', 'がっこう', 'に', 'いきます']],
        },
      },
    ],
  },
  {
    id: 'mission-grammar-existence-arimasu-imasu',
    type: 'grammar',
    title: 'Say where things and people are',
    targetSkill: 'particles',
    contentRefs: {
      grammarLessonIds: ['grammar-existence-arimasu-imasu'],
      vocabIds: [
        'vocab-heya',
        'vocab-neko',
        'vocab-inu',
        'vocab-arimasu',
        'vocab-imasu',
        'vocab-hon',
        'vocab-sensei',
        'vocab-toshokan',
        'vocab-kyoushitsu',
      ],
      exampleIds: [
        'ex-neko-heya-imasu',
        'ex-sensei-kyoushitsu-imasu',
        'ex-inu-uchi-imasu',
        'ex-hon-toshokan-arimasu',
      ],
    },
    estimatedMinutes: 7,
    unlockRules: {
      requiredMissionIds: ['mission-grammar-destination-ni'],
    },
  },
  {
    id: 'mission-listening-existence-position',
    type: 'listening',
    title: 'Hear where things are in a room',
    targetSkill: 'listening-comprehension',
    contentRefs: {
      grammarLessonIds: ['grammar-existence-arimasu-imasu', 'grammar-position-no'],
      listeningItemIds: [
        'listening-neko-heya',
        'listening-sensei-kyoushitsu',
        'listening-hon-tsukue-ue',
        'listening-kaban-isu-shita',
        'listening-hon-kaban-naka',
      ],
      exampleIds: [
        'ex-neko-heya-imasu',
        'ex-sensei-kyoushitsu-imasu',
        'ex-hon-tsukue-ue',
        'ex-kaban-isu-shita',
        'ex-hon-kaban-naka',
      ],
    },
    estimatedMinutes: 7,
    unlockRules: {
      requiredMissionIds: ['mission-grammar-existence-arimasu-imasu'],
    },
  },
  {
    id: 'mission-output-room-locations',
    type: 'output',
    title: 'Write two short location lines',
    targetSkill: 'output-confidence',
    contentRefs: {
      grammarLessonIds: ['grammar-existence-arimasu-imasu', 'grammar-position-no'],
      vocabIds: [
        'vocab-hon',
        'vocab-tsukue',
        'vocab-kaban',
        'vocab-neko',
        'vocab-heya',
        'vocab-ue',
        'vocab-shita',
        'vocab-arimasu',
        'vocab-imasu',
      ],
      exampleIds: ['ex-hon-tsukue-ue', 'ex-kaban-isu-shita', 'ex-neko-heya-imasu'],
    },
    estimatedMinutes: 8,
    unlockRules: {
      requiredMissionIds: ['mission-grammar-existence-arimasu-imasu'],
    },
    outputTasks: [
      {
        id: 'output-hon-tsukue-ue',
        prompt: 'Type a line that says: "The book is on the desk."',
        acceptableAnswers: ['ほんはつくえのうえにあります。', 'ほんはつくえのうえにあります'],
        hint: 'Use noun plus の plus うえ に before あります.',
        evaluation: {
          tokenPatterns: [['ほん', 'は', 'つくえ', 'の', 'うえ', 'に', 'あります']],
        },
      },
      {
        id: 'output-neko-heya-imasu',
        prompt: 'Type a line that says: "The cat is in the room."',
        acceptableAnswers: ['ねこはへやにいます。', 'ねこはへやにいます'],
        hint: 'Use に after へや, then finish with います for the cat.',
        evaluation: {
          tokenPatterns: [['ねこ', 'は', 'へや', 'に', 'います']],
        },
      },
    ],
  },
  {
    id: 'mission-grammar-preference-suki-kirai',
    type: 'grammar',
    title: 'Say what you like and dislike',
    targetSkill: 'particles',
    contentRefs: {
      grammarLessonIds: ['grammar-preference-suki-kirai'],
      vocabIds: [
        'vocab-suki',
        'vocab-kirai',
        'vocab-sushi',
        'vocab-raamen',
        'vocab-ongaku',
        'vocab-anime',
        'vocab-sakkaa',
        'vocab-eiga',
      ],
      exampleIds: [
        'ex-watashi-sushi-suki',
        'ex-tomodachi-raamen-suki',
        'ex-watashi-koohii-kirai',
        'ex-ongaku-suki',
        'ex-anime-suki',
        'ex-sakkaa-kirai',
      ],
    },
    estimatedMinutes: 7,
    unlockRules: {
      requiredMissionIds: ['mission-grammar-existence-arimasu-imasu'],
    },
  },
  {
    id: 'mission-listening-preferences',
    type: 'listening',
    title: 'Hear simple likes and dislikes',
    targetSkill: 'listening-comprehension',
    contentRefs: {
      grammarLessonIds: ['grammar-preference-suki-kirai', 'grammar-preference-questions'],
      listeningItemIds: [
        'listening-watashi-sushi-suki',
        'listening-koohii-kirai',
        'listening-ongaku-suki',
        'listening-nani-suki',
        'listening-tabemono-nani-suki',
      ],
      exampleIds: [
        'ex-watashi-sushi-suki',
        'ex-watashi-koohii-kirai',
        'ex-ongaku-suki',
        'ex-nani-suki',
        'ex-tabemono-nani-suki',
      ],
    },
    estimatedMinutes: 7,
    unlockRules: {
      requiredMissionIds: ['mission-grammar-preference-suki-kirai'],
    },
  },
  {
    id: 'mission-output-preference-questions',
    type: 'output',
    title: 'Ask and answer one simple preference',
    targetSkill: 'output-confidence',
    contentRefs: {
      grammarLessonIds: ['grammar-preference-suki-kirai', 'grammar-preference-questions'],
      vocabIds: [
        'vocab-suki',
        'vocab-anime',
        'vocab-nomimono',
        'vocab-cha',
        'vocab-tabemono',
      ],
      exampleIds: [
        'ex-anime-suki',
        'ex-cha-suki',
        'ex-nomimono-nani-suki',
        'ex-tabemono-nani-suki',
      ],
    },
    estimatedMinutes: 8,
    unlockRules: {
      requiredMissionIds: ['mission-grammar-preference-suki-kirai'],
    },
    outputTasks: [
      {
        id: 'output-anime-suki',
        prompt: 'Type a line that says: "I like anime."',
        acceptableAnswers: [
          'アニメがすきです。',
          'アニメがすきです',
          'わたしはアニメがすきです。',
          'わたしはアニメがすきです',
        ],
        hint: 'Use the thing plus が plus すきです. Adding わたしは is also acceptable.',
        evaluation: {
          tokenPatterns: [
            ['アニメ', 'が', 'すき', 'です'],
            ['わたし', 'は', 'アニメ', 'が', 'すき', 'です'],
          ],
        },
      },
      {
        id: 'output-nomimono-nani-suki',
        prompt: 'Type a polite question that says: "What drink do you like?"',
        acceptableAnswers: ['のみものはなにがすきですか。', 'のみものはなにがすきですか'],
        hint: 'Start with the category topic のみものは, then ask なにがすきですか.',
        evaluation: {
          tokenPatterns: [['のみもの', 'は', 'なに', 'が', 'すき', 'です', 'か']],
        },
      },
    ],
  },
  {
    id: 'mission-grammar-where-doko-desu',
    type: 'grammar',
    title: 'Ask where something is with どこですか',
    targetSkill: 'sentence-structure',
    contentRefs: {
      grammarLessonIds: ['grammar-where-doko-desu'],
      vocabIds: [
        'vocab-toire',
        'vocab-kagi',
        'vocab-jitensha',
        'vocab-doko-desu',
        'vocab-sensei',
      ],
      exampleIds: [
        'ex-toire-doko',
        'ex-kagi-doko',
        'ex-sensei-doko-desu',
        'ex-jitensha-doko',
      ],
    },
    estimatedMinutes: 7,
    unlockRules: {
      requiredMissionIds: ['mission-grammar-preference-suki-kirai'],
    },
  },
  {
    id: 'mission-listening-where-things-are',
    type: 'listening',
    title: 'Hear where things and places are',
    targetSkill: 'listening-comprehension',
    contentRefs: {
      grammarLessonIds: ['grammar-where-doko-desu', 'grammar-location-answer-places'],
      listeningItemIds: [
        'listening-toire-doko',
        'listening-toire-asoko',
        'listening-kagi-doko',
        'listening-kagi-tsukue-ue',
        'listening-sensei-jimusho',
      ],
      exampleIds: [
        'ex-toire-doko',
        'ex-toire-asoko',
        'ex-kagi-doko',
        'ex-kagi-tsukue-ue-arimasu',
        'ex-sensei-jimusho-imasu',
      ],
    },
    estimatedMinutes: 7,
    unlockRules: {
      requiredMissionIds: ['mission-grammar-where-doko-desu'],
    },
  },
  {
    id: 'mission-output-where-answers',
    type: 'output',
    title: 'Ask one where-question and answer one location',
    targetSkill: 'output-confidence',
    contentRefs: {
      grammarLessonIds: ['grammar-where-doko-desu', 'grammar-location-answer-places'],
      vocabIds: [
        'vocab-toire',
        'vocab-kagi',
        'vocab-tsukue',
        'vocab-ue',
        'vocab-doko-desu',
      ],
      exampleIds: ['ex-toire-doko', 'ex-kagi-tsukue-ue-arimasu', 'ex-toire-asoko'],
    },
    estimatedMinutes: 8,
    unlockRules: {
      requiredMissionIds: ['mission-grammar-where-doko-desu'],
    },
    outputTasks: [
      {
        id: 'output-toire-doko',
        prompt: 'Type a polite question that says: "Where is the bathroom?"',
        acceptableAnswers: ['トイレはどこですか。', 'トイレはどこですか'],
        hint: 'Use the topic first, then どこですか.',
        evaluation: {
          tokenPatterns: [['トイレ', 'は', 'どこ', 'です', 'か']],
        },
      },
      {
        id: 'output-kagi-tsukue-ue',
        prompt: 'Type a line that says: "The key is on the desk."',
        acceptableAnswers: ['かぎはつくえのうえにあります。', 'かぎはつくえのうえにあります'],
        hint: 'Use the topic first, then the location phrase つくえのうえに, then あります.',
        evaluation: {
          tokenPatterns: [['かぎ', 'は', 'つくえ', 'の', 'うえ', 'に', 'あります']],
        },
      },
    ],
  },
  {
    id: 'mission-reading-starter-recognition',
    type: 'reading',
    title: 'Read short beginner lines before the reveal',
    targetSkill: 'reading-recognition',
    contentRefs: {
      exampleIds: [
        'ex-kore-eigo-hon',
        'ex-neko-heya-imasu',
        'ex-watashi-sushi-suki',
        'ex-toire-doko',
        'ex-kagi-tsukue-ue-arimasu',
      ],
    },
    estimatedMinutes: 6,
    unlockRules: {
      requiredMissionIds: ['mission-grammar-topic-desu'],
    },
    readingChecks: [
      {
        id: 'reading-check-kore-eigo-hon-meaning',
        exampleId: 'ex-kore-eigo-hon',
        prompt: 'Which meaning matches this line?',
        choices: [
          'This is an English book.',
          'This book is in English class.',
          'That is an English teacher.',
        ],
        answer: 'This is an English book.',
        support: 'Read これ as "this" and notice how えいごのほん links two nouns before です.',
      },
      {
        id: 'reading-check-neko-heya-location',
        exampleId: 'ex-neko-heya-imasu',
        prompt: 'What location does this sentence describe?',
        choices: [
          'The cat is in the room.',
          'The cat goes to the room.',
          'The room likes the cat.',
        ],
        answer: 'The cat is in the room.',
        support: 'にいます marks where an animate thing is, not where it goes.',
      },
      {
        id: 'reading-check-watashi-sushi-suki-preference',
        exampleId: 'ex-watashi-sushi-suki',
        prompt: 'What is the speaker saying here?',
        choices: [
          'I like sushi.',
          'I am sushi.',
          'I eat sushi at home.',
        ],
        answer: 'I like sushi.',
        support: 'すしがすきです is the beginner preference pattern: the thing you like comes before が.',
      },
      {
        id: 'reading-check-toire-doko-question',
        exampleId: 'ex-toire-doko',
        prompt: 'What kind of sentence is this?',
        choices: [
          'A where-question asking for a location.',
          'A statement that says the bathroom is over there.',
          'A sentence about going to the bathroom.',
        ],
        answer: 'A where-question asking for a location.',
        support: 'どこですか signals a polite where-question, so read it as asking for location information.',
      },
      {
        id: 'reading-check-kagi-tsukue-ue-location',
        exampleId: 'ex-kagi-tsukue-ue-arimasu',
        prompt: 'Which English meaning is the best match?',
        choices: [
          'The key is on the desk.',
          'The desk is under the key.',
          'The key goes to the desk.',
        ],
        answer: 'The key is on the desk.',
        support: 'つくえのうえにあります gives a full location phrase: "on the desk" before the existence verb.',
      },
    ],
  },
  {
    id: 'mission-reading-questions-and-answers',
    type: 'reading',
    title: 'Read simple questions and answers',
    targetSkill: 'reading-recognition',
    contentRefs: {
      exampleIds: [
        'ex-kore-nan',
        'ex-kore-hon',
        'ex-sore-shukudai',
        'ex-nani-suki',
        'ex-tabemono-nani-suki',
      ],
    },
    estimatedMinutes: 6,
    unlockRules: {
      requiredMissionIds: ['mission-reading-starter-recognition'],
    },
    readingChecks: [
      {
        id: 'reading-check-kore-nan-question-type',
        exampleId: 'ex-kore-nan',
        prompt: 'What is this line doing?',
        choices: [
          'It asks, "What is this?"',
          'It says, "This is a book."',
          'It asks where this is.',
        ],
        answer: 'It asks, "What is this?"',
        support: 'これはなんですか ends with か, so read it as a question, not a statement.',
      },
      {
        id: 'reading-check-kore-hon-answer-meaning',
        exampleId: 'ex-kore-hon',
        prompt: 'Which answer matches this short line?',
        choices: [
          'This is a book.',
          'What is this book?',
          'That is homework.',
        ],
        answer: 'This is a book.',
        support: 'ほんです is a plain beginner answer pattern: noun plus です.',
      },
      {
        id: 'reading-check-sore-shukudai-answer-role',
        exampleId: 'ex-sore-shukudai',
        prompt: 'Is this sentence a question or an answer?',
        choices: [
          'It is an answer identifying something.',
          'It is a question asking what that is.',
          'It is a preference question.',
        ],
        answer: 'It is an answer identifying something.',
        support: 'それはしゅくだいです ends as a statement, so treat it as an answer line.',
      },
      {
        id: 'reading-check-nani-suki-general-question',
        exampleId: 'ex-nani-suki',
        prompt: 'What kind of information is this question asking for?',
        choices: [
          'Something the other person likes.',
          'Where something is.',
          'What this object is called.',
        ],
        answer: 'Something the other person likes.',
        support: 'なにがすきですか asks about preference, with なに as the unknown thing.',
      },
      {
        id: 'reading-check-tabemono-nani-suki-category',
        exampleId: 'ex-tabemono-nani-suki',
        prompt: 'What category does this question focus on?',
        choices: [
          'Food',
          'Drinks',
          'Places',
        ],
        answer: 'Food',
        support: 'たべものは sets the topic first, so the question is specifically about food preferences.',
      },
    ],
  },
  {
    id: 'mission-reading-location-questions-and-answers',
    type: 'reading',
    title: 'Read where things and people are',
    targetSkill: 'reading-recognition',
    contentRefs: {
      exampleIds: [
        'ex-kagi-doko',
        'ex-toire-asoko',
        'ex-jimusho-koko',
        'ex-kutsu-genkan-arimasu',
        'ex-sensei-jimusho-imasu',
      ],
    },
    estimatedMinutes: 6,
    unlockRules: {
      requiredMissionIds: ['mission-reading-questions-and-answers'],
    },
    readingChecks: [
      {
        id: 'reading-check-kagi-doko-question-meaning',
        exampleId: 'ex-kagi-doko',
        prompt: 'Which meaning matches this line?',
        choices: [
          'Where is the key?',
          'The key is on the desk.',
          'Where does the key go?',
        ],
        answer: 'Where is the key?',
        support: 'どこですか marks a location question, so read this as asking where the key is.',
      },
      {
        id: 'reading-check-toire-asoko-answer-role',
        exampleId: 'ex-toire-asoko',
        prompt: 'Is this line a question or an answer?',
        choices: [
          'It is an answer giving a location.',
          'It is a question asking for a location.',
          'It is a sentence about going somewhere.',
        ],
        answer: 'It is an answer giving a location.',
        support: 'あそこです ends as a short location answer, not a question.',
      },
      {
        id: 'reading-check-jimusho-koko-place-word',
        exampleId: 'ex-jimusho-koko',
        prompt: 'Which place word appears in this answer?',
        choices: [
          'ここ, meaning "here"',
          'そこ, meaning "there"',
          'あそこ, meaning "over there"',
        ],
        answer: 'ここ, meaning "here"',
        support: 'Read ここです as a direct answer meaning something is here.',
      },
      {
        id: 'reading-check-kutsu-genkan-location-meaning',
        exampleId: 'ex-kutsu-genkan-arimasu',
        prompt: 'What location is being described?',
        choices: [
          'The shoes are at the entrance.',
          'The shoes go to the entrance.',
          'The entrance is under the shoes.',
        ],
        answer: 'The shoes are at the entrance.',
        support: 'にあります shows where an object is located, not where it goes.',
      },
      {
        id: 'reading-check-sensei-jimusho-animate-existence',
        exampleId: 'ex-sensei-jimusho-imasu',
        prompt: 'Why does this line end with います instead of あります?',
        choices: [
          'Because it is talking about a person.',
          'Because it is talking about a key.',
          'Because it is asking a question.',
        ],
        answer: 'Because it is talking about a person.',
        support: 'います is the beginner existence verb for people and animals.',
      },
    ],
  },
  {
    id: 'mission-reading-preferences-and-opinions',
    type: 'reading',
    title: 'Read simple likes and dislikes',
    targetSkill: 'reading-recognition',
    contentRefs: {
      exampleIds: [
        'ex-eiga-suki-ka',
        'ex-anime-suki',
        'ex-cha-suki',
        'ex-nomimono-nani-suki',
        'ex-watashi-koohii-kirai',
      ],
    },
    estimatedMinutes: 6,
    unlockRules: {
      requiredMissionIds: ['mission-reading-location-questions-and-answers'],
    },
    readingChecks: [
      {
        id: 'reading-check-eiga-suki-ka-question-role',
        exampleId: 'ex-eiga-suki-ka',
        prompt: 'What is this line doing?',
        choices: [
          'It asks whether someone likes movies.',
          'It says the speaker likes movies.',
          'It asks what movie someone likes.',
        ],
        answer: 'It asks whether someone likes movies.',
        support: 'The ending か makes this a yes-or-no preference question, not a statement.',
      },
      {
        id: 'reading-check-anime-suki-liked-thing',
        exampleId: 'ex-anime-suki',
        prompt: 'What thing is being liked in this sentence?',
        choices: [
          'Anime',
          'Tea',
          'Coffee',
        ],
        answer: 'Anime',
        support: 'The noun before が is the thing being liked in this simple pattern.',
      },
      {
        id: 'reading-check-cha-suki-answer-meaning',
        exampleId: 'ex-cha-suki',
        prompt: 'Which meaning matches this short answer?',
        choices: [
          'I like tea.',
          'Do you like tea?',
          'I dislike tea.',
        ],
        answer: 'I like tea.',
        support: 'ちゃがすきです is a statement, so read it as liking tea rather than asking a question.',
      },
      {
        id: 'reading-check-nomimono-nani-suki-category',
        exampleId: 'ex-nomimono-nani-suki',
        prompt: 'What category is this question asking about?',
        choices: [
          'Drinks',
          'Food',
          'Places',
        ],
        answer: 'Drinks',
        support: 'のみものは sets the topic first, so the question is specifically about drinks.',
      },
      {
        id: 'reading-check-koohii-kirai-opinion',
        exampleId: 'ex-watashi-koohii-kirai',
        prompt: 'What opinion is the speaker expressing?',
        choices: [
          'They dislike coffee.',
          'They like coffee.',
          'They want coffee.',
        ],
        answer: 'They dislike coffee.',
        support: 'きらいです marks dislike, so this line expresses a negative preference.',
      },
    ],
  },
  {
    id: 'mission-reading-identity-and-daily-routine',
    type: 'reading',
    title: 'Read identity and daily routine lines',
    targetSkill: 'reading-recognition',
    contentRefs: {
      exampleIds: [
        'ex-student-desu',
        'ex-study-home',
        'ex-coffee-cafe',
        'ex-mainichi-gakkou',
        'ex-ima-kyoushitsu',
      ],
    },
    estimatedMinutes: 6,
    unlockRules: {
      requiredMissionIds: ['mission-reading-preferences-and-opinions'],
    },
    readingChecks: [
      {
        id: 'reading-check-student-desu-identity-role',
        exampleId: 'ex-student-desu',
        prompt: 'What kind of sentence is this?',
        choices: [
          'An identity statement about what someone is.',
          'A line about studying at home.',
          'A destination line about going to school.',
        ],
        answer: 'An identity statement about what someone is.',
        support: 'がくせいです identifies the speaker, so read this as saying what they are.',
      },
      {
        id: 'reading-check-study-home-place-meaning',
        exampleId: 'ex-study-home',
        prompt: 'Which meaning matches this line?',
        choices: [
          'I study Japanese at home.',
          'I go home to study Japanese.',
          'I am Japanese at home.',
        ],
        answer: 'I study Japanese at home.',
        support: 'うちで marks the place of action with で before the study verb.',
      },
      {
        id: 'reading-check-coffee-cafe-place',
        exampleId: 'ex-coffee-cafe',
        prompt: 'Which place is being used in this sentence?',
        choices: [
          'A cafe',
          'A school',
          'A library',
        ],
        answer: 'A cafe',
        support: 'カフェで shows where the action happens before the object and verb.',
      },
      {
        id: 'reading-check-mainichi-gakkou-destination',
        exampleId: 'ex-mainichi-gakkou',
        prompt: 'What is the sentence mainly describing?',
        choices: [
          'Going to school every day.',
          'Studying at school today.',
          'Being a student at school.',
        ],
        answer: 'Going to school every day.',
        support: 'がっこうにいきます is a destination pattern, with に marking where someone goes.',
      },
      {
        id: 'reading-check-ima-kyoushitsu-time-destination',
        exampleId: 'ex-ima-kyoushitsu',
        prompt: 'Which reading of the sentence is correct?',
        choices: [
          'I am going to the classroom now.',
          'I study in the classroom now.',
          'The classroom is here now.',
        ],
        answer: 'I am going to the classroom now.',
        support: 'いま adds the time, and きょうしつにいきます still shows movement to a destination.',
      },
    ],
  },
  {
    id: 'mission-grammar-possession-no',
    type: 'grammar',
    title: 'Say whose item something is with の',
    targetSkill: 'particles',
    contentRefs: {
      grammarLessonIds: ['grammar-possession-no'],
      vocabIds: [
        'vocab-no-ownership',
        'vocab-watashi',
        'vocab-hon',
        'vocab-kaban',
        'vocab-ane',
        'vocab-chichi',
        'vocab-kamera',
        'vocab-kazoku',
        'vocab-shashin',
      ],
      exampleIds: [
        'ex-kore-watashi-no-hon',
        'ex-sore-ane-no-kaban',
        'ex-kore-chichi-no-kamera',
        'ex-kore-kazoku-no-shashin',
      ],
    },
    estimatedMinutes: 7,
    unlockRules: {
      requiredMissionIds: ['mission-grammar-where-doko-desu'],
    },
  },
  {
    id: 'mission-listening-family-objects',
    type: 'listening',
    title: 'Hear whose item it is',
    targetSkill: 'listening-comprehension',
    contentRefs: {
      grammarLessonIds: ['grammar-possession-no', 'grammar-family-possession-lines'],
      listeningItemIds: [
        'listening-kore-watashi-no-hon',
        'listening-sore-ane-no-kaban',
        'listening-kore-chichi-no-kamera',
        'listening-kore-kazoku-no-shashin',
        'listening-sore-haha-no-kasa',
      ],
      exampleIds: [
        'ex-kore-watashi-no-hon',
        'ex-sore-ane-no-kaban',
        'ex-kore-chichi-no-kamera',
        'ex-kore-kazoku-no-shashin',
        'ex-sore-haha-no-kasa',
      ],
    },
    estimatedMinutes: 7,
    unlockRules: {
      requiredMissionIds: ['mission-grammar-possession-no'],
    },
  },
  {
    id: 'mission-output-family-objects',
    type: 'output',
    title: 'Write two simple ownership lines',
    targetSkill: 'output-confidence',
    contentRefs: {
      grammarLessonIds: ['grammar-possession-no', 'grammar-family-possession-lines'],
      vocabIds: [
        'vocab-no-ownership',
        'vocab-watashi',
        'vocab-hon',
        'vocab-kaban',
        'vocab-ane',
        'vocab-haha',
        'vocab-kasa',
      ],
      exampleIds: [
        'ex-kore-watashi-no-hon',
        'ex-sore-ane-no-kaban',
        'ex-sore-haha-no-kasa',
      ],
    },
    estimatedMinutes: 8,
    unlockRules: {
      requiredMissionIds: ['mission-grammar-possession-no'],
    },
    outputTasks: [
      {
        id: 'output-kore-watashi-no-hon',
        prompt: 'Type a line that says: "This is my book."',
        acceptableAnswers: ['これはわたしのほんです。', 'これはわたしのほんです'],
        hint: 'Use これは first, then わたしのほん, then です.',
        evaluation: {
          tokenPatterns: [['これ', 'は', 'わたし', 'の', 'ほん', 'です']],
        },
      },
      {
        id: 'output-sore-ane-no-kaban',
        prompt: "Type a line that says: \"That is my older sister's bag.\"",
        acceptableAnswers: ['それはあねのかばんです。', 'それはあねのかばんです'],
        hint: 'Use それは first, then the owner phrase あねの before かばんです.',
        evaluation: {
          tokenPatterns: [['それ', 'は', 'あね', 'の', 'かばん', 'です']],
        },
      },
    ],
  },
  {
    id: 'mission-grammar-verb-forms-routine',
    type: 'grammar',
    title: 'Use ます and ません in daily routines',
    targetSkill: 'verb-forms',
    contentRefs: {
      grammarLessonIds: ['grammar-verb-forms-masu-routine'],
      vocabIds: [
        'vocab-tabemasu',
        'vocab-yomimasu',
        'vocab-mimasu',
        'vocab-kikimasu',
        'vocab-asa',
        'vocab-yoru',
        'vocab-pan',
        'vocab-terebi',
        'vocab-kouen',
      ],
      exampleIds: [
        'ex-asa-pan-tabemasu',
        'ex-yoru-hon-yomimasu',
        'ex-uchi-terebi-mimasu',
        'ex-kouen-ongaku-kikimasu',
        'ex-yoru-nihongo-benkyoushimasu',
      ],
    },
    estimatedMinutes: 7,
    unlockRules: {
      requiredMissionIds: ['mission-grammar-possession-no'],
    },
  },
  {
    id: 'mission-listening-verb-forms-daily-life',
    type: 'listening',
    title: 'Hear everyday ます and ません lines',
    targetSkill: 'listening-comprehension',
    contentRefs: {
      grammarLessonIds: ['grammar-verb-forms-masu-routine', 'grammar-verb-forms-masen'],
      listeningItemIds: [
        'listening-asa-pan-tabemasu',
        'listening-yoru-hon-yomimasu',
        'listening-uchi-terebi-mimasu',
        'listening-kyou-koohii-nomimasen',
        'listening-ashita-toshokan-ikimasen',
      ],
      exampleIds: [
        'ex-asa-pan-tabemasu',
        'ex-yoru-hon-yomimasu',
        'ex-uchi-terebi-mimasu',
        'ex-kyou-koohii-nomimasen',
        'ex-ashita-toshokan-ikimasen',
      ],
    },
    estimatedMinutes: 7,
    unlockRules: {
      requiredMissionIds: ['mission-grammar-verb-forms-routine'],
    },
  },
  {
    id: 'mission-output-verb-forms-daily-life',
    type: 'output',
    title: 'Write one routine line and one negative line',
    targetSkill: 'output-confidence',
    contentRefs: {
      grammarLessonIds: ['grammar-verb-forms-masu-routine', 'grammar-verb-forms-masen'],
      vocabIds: [
        'vocab-yomimasu',
        'vocab-yoru',
        'vocab-hon',
        'vocab-koohii',
        'vocab-kyou',
        'vocab-nomimasu',
      ],
      exampleIds: [
        'ex-yoru-hon-yomimasu',
        'ex-kyou-koohii-nomimasen',
        'ex-asa-pan-tabemasu',
      ],
    },
    estimatedMinutes: 8,
    unlockRules: {
      requiredMissionIds: ['mission-grammar-verb-forms-routine'],
    },
    outputTasks: [
      {
        id: 'output-yoru-hon-yomimasu',
        prompt: 'Type a line that says: "I read a book at night."',
        acceptableAnswers: ['よるほんをよみます。', 'よるほんをよみます'],
        hint: 'Use the time word first, then ほんを, then the polite verb よみます.',
        evaluation: {
          tokenPatterns: [['よる', 'ほん', 'を', 'よみます']],
        },
      },
      {
        id: 'output-kyou-koohii-nomimasen',
        prompt: 'Type a line that says: "I do not drink coffee today."',
        acceptableAnswers: [
          'きょうコーヒーをのみません。',
          'きょうコーヒーをのみません',
        ],
        hint: 'Use the time word first, then the object phrase, then the negative polite ending ません.',
        evaluation: {
          tokenPatterns: [['きょう', 'コーヒー', 'を', 'のみません']],
        },
      },
    ],
  },
] satisfies Mission[];
