import type { VocabItem } from '../lib/content/types';

export const vocabItems = [
  {
    id: 'vocab-watashi',
    kana: 'わたし',
    kanji: '私',
    meaning: 'I; me',
    partOfSpeech: 'pronoun',
    tags: ['self', 'n5'],
    exampleIds: ['ex-colin-desu', 'ex-student-desu'],
  },
  {
    id: 'vocab-gakusei',
    kana: 'がくせい',
    kanji: '学生',
    meaning: 'student',
    partOfSpeech: 'noun',
    tags: ['school', 'identity', 'n5'],
    exampleIds: ['ex-student-desu'],
  },
  {
    id: 'vocab-sensei',
    kana: 'せんせい',
    kanji: '先生',
    meaning: 'teacher',
    partOfSpeech: 'noun',
    tags: ['school', 'role', 'n5'],
    exampleIds: ['ex-teacher-question'],
  },
  {
    id: 'vocab-tomodachi',
    kana: 'ともだち',
    kanji: '友だち',
    meaning: 'friend',
    partOfSpeech: 'noun',
    tags: ['people', 'n5'],
    exampleIds: ['ex-company-worker'],
  },
  {
    id: 'vocab-kaishain',
    kana: 'かいしゃいん',
    kanji: '会社員',
    meaning: 'office worker',
    partOfSpeech: 'noun',
    tags: ['work', 'identity', 'n5'],
    exampleIds: ['ex-company-worker'],
  },
  {
    id: 'vocab-uchi',
    kana: 'うち',
    kanji: null,
    meaning: 'home',
    partOfSpeech: 'noun',
    tags: ['place', 'daily-routine', 'n5'],
    exampleIds: ['ex-study-home'],
  },
  {
    id: 'vocab-nihongo',
    kana: 'にほんご',
    kanji: '日本語',
    meaning: 'Japanese language',
    partOfSpeech: 'noun',
    tags: ['study', 'language', 'n5'],
    exampleIds: ['ex-study-home'],
  },
  {
    id: 'vocab-benkyoushimasu',
    kana: 'べんきょうします',
    kanji: '勉強します',
    meaning: 'to study',
    partOfSpeech: 'verb',
    tags: ['study', 'daily-routine', 'n5'],
    exampleIds: ['ex-study-home', 'ex-classroom-study'],
  },
  {
    id: 'vocab-kafe',
    kana: 'カフェ',
    kanji: null,
    meaning: 'cafe',
    partOfSpeech: 'noun',
    tags: ['place', 'daily-routine', 'n5'],
    exampleIds: ['ex-coffee-cafe'],
  },
  {
    id: 'vocab-koohii',
    kana: 'コーヒー',
    kanji: null,
    meaning: 'coffee',
    partOfSpeech: 'noun',
    tags: ['food', 'daily-routine', 'n5'],
    exampleIds: ['ex-coffee-cafe'],
  },
  {
    id: 'vocab-nomimasu',
    kana: 'のみます',
    kanji: '飲みます',
    meaning: 'to drink',
    partOfSpeech: 'verb',
    tags: ['action', 'daily-routine', 'n5'],
    exampleIds: ['ex-coffee-cafe'],
  },
  {
    id: 'vocab-toshokan',
    kana: 'としょかん',
    kanji: '図書館',
    meaning: 'library',
    partOfSpeech: 'noun',
    tags: ['place', 'study', 'n5'],
    exampleIds: ['ex-read-library'],
  },
  {
    id: 'vocab-kore',
    kana: 'これ',
    kanji: null,
    meaning: 'this',
    partOfSpeech: 'pronoun',
    tags: ['classroom', 'demonstrative', 'n5'],
    exampleIds: ['ex-kore-hon', 'ex-kore-nan', 'ex-kore-eigo-hon'],
  },
  {
    id: 'vocab-sore',
    kana: 'それ',
    kanji: null,
    meaning: 'that',
    partOfSpeech: 'pronoun',
    tags: ['classroom', 'demonstrative', 'n5'],
    exampleIds: ['ex-sore-shukudai'],
  },
  {
    id: 'vocab-nan',
    kana: 'なん',
    kanji: '何',
    meaning: 'what',
    partOfSpeech: 'question',
    tags: ['question', 'classroom', 'n5'],
    exampleIds: ['ex-kore-nan'],
  },
  {
    id: 'vocab-hon',
    kana: 'ほん',
    kanji: '本',
    meaning: 'book',
    partOfSpeech: 'noun',
    tags: ['classroom', 'study', 'n5'],
    exampleIds: ['ex-kore-hon', 'ex-kore-eigo-hon'],
  },
  {
    id: 'vocab-eigo',
    kana: 'えいご',
    kanji: '英語',
    meaning: 'English language',
    partOfSpeech: 'noun',
    tags: ['study', 'language', 'n5'],
    exampleIds: ['ex-kore-eigo-hon'],
  },
  {
    id: 'vocab-shukudai',
    kana: 'しゅくだい',
    kanji: '宿題',
    meaning: 'homework',
    partOfSpeech: 'noun',
    tags: ['study', 'classroom', 'n5'],
    exampleIds: ['ex-sore-shukudai'],
  },
  {
    id: 'vocab-doko',
    kana: 'どこ',
    kanji: null,
    meaning: 'where',
    partOfSpeech: 'question',
    tags: ['question', 'place', 'n5'],
    exampleIds: ['ex-doko-ikimasu', 'ex-sensei-doko'],
  },
  {
    id: 'vocab-gakkou',
    kana: 'がっこう',
    kanji: '学校',
    meaning: 'school',
    partOfSpeech: 'noun',
    tags: ['school', 'place', 'n5'],
    exampleIds: ['ex-mainichi-gakkou', 'ex-tomodachi-gakkou'],
  },
  {
    id: 'vocab-ikimasu',
    kana: 'いきます',
    kanji: '行きます',
    meaning: 'to go',
    partOfSpeech: 'verb',
    tags: ['movement', 'daily-routine', 'n5'],
    exampleIds: [
      'ex-doko-ikimasu',
      'ex-mainichi-gakkou',
      'ex-kyou-toshokan',
      'ex-ima-kyoushitsu',
    ],
  },
  {
    id: 'vocab-mainichi',
    kana: 'まいにち',
    kanji: '毎日',
    meaning: 'every day',
    partOfSpeech: 'expression',
    tags: ['time', 'daily-routine', 'n5'],
    exampleIds: ['ex-mainichi-gakkou'],
  },
  {
    id: 'vocab-kyou',
    kana: 'きょう',
    kanji: '今日',
    meaning: 'today',
    partOfSpeech: 'expression',
    tags: ['time', 'daily-routine', 'n5'],
    exampleIds: ['ex-kyou-toshokan'],
  },
  {
    id: 'vocab-ima',
    kana: 'いま',
    kanji: '今',
    meaning: 'now',
    partOfSpeech: 'expression',
    tags: ['time', 'daily-routine', 'n5'],
    exampleIds: ['ex-ima-kyoushitsu'],
  },
  {
    id: 'vocab-kyoushitsu',
    kana: 'きょうしつ',
    kanji: '教室',
    meaning: 'classroom',
    partOfSpeech: 'noun',
    tags: ['school', 'place', 'n5'],
    exampleIds: ['ex-ima-kyoushitsu'],
  },
  {
    id: 'vocab-heya',
    kana: 'へや',
    kanji: '部屋',
    meaning: 'room',
    partOfSpeech: 'noun',
    tags: ['place', 'home', 'n5'],
    exampleIds: ['ex-neko-heya-imasu'],
  },
  {
    id: 'vocab-tsukue',
    kana: 'つくえ',
    kanji: '机',
    meaning: 'desk',
    partOfSpeech: 'noun',
    tags: ['place', 'classroom', 'n5'],
    exampleIds: ['ex-hon-tsukue-ue', 'ex-neko-tsukue-shita'],
  },
  {
    id: 'vocab-isu',
    kana: 'いす',
    kanji: null,
    meaning: 'chair',
    partOfSpeech: 'noun',
    tags: ['furniture', 'classroom', 'n5'],
    exampleIds: ['ex-kaban-isu-shita'],
  },
  {
    id: 'vocab-kaban',
    kana: 'かばん',
    kanji: null,
    meaning: 'bag',
    partOfSpeech: 'noun',
    tags: ['daily-routine', 'object', 'n5'],
    exampleIds: ['ex-kaban-isu-shita', 'ex-hon-kaban-naka'],
  },
  {
    id: 'vocab-neko',
    kana: 'ねこ',
    kanji: '猫',
    meaning: 'cat',
    partOfSpeech: 'noun',
    tags: ['animal', 'n5'],
    exampleIds: ['ex-neko-heya-imasu', 'ex-neko-tsukue-shita'],
  },
  {
    id: 'vocab-inu',
    kana: 'いぬ',
    kanji: '犬',
    meaning: 'dog',
    partOfSpeech: 'noun',
    tags: ['animal', 'n5'],
    exampleIds: ['ex-inu-uchi-imasu'],
  },
  {
    id: 'vocab-arimasu',
    kana: 'あります',
    kanji: null,
    meaning: 'to exist; there is/are (for things)',
    partOfSpeech: 'verb',
    tags: ['existence', 'n5'],
    exampleIds: ['ex-hon-toshokan-arimasu', 'ex-hon-tsukue-ue', 'ex-hon-kaban-naka'],
  },
  {
    id: 'vocab-imasu',
    kana: 'います',
    kanji: null,
    meaning: 'to exist; there is/are (for people and animals)',
    partOfSpeech: 'verb',
    tags: ['existence', 'n5'],
    exampleIds: ['ex-neko-heya-imasu', 'ex-sensei-kyoushitsu-imasu', 'ex-inu-uchi-imasu'],
  },
  {
    id: 'vocab-ue',
    kana: 'うえ',
    kanji: '上',
    meaning: 'top; above; on',
    partOfSpeech: 'noun',
    tags: ['position', 'n5'],
    exampleIds: ['ex-hon-tsukue-ue'],
  },
  {
    id: 'vocab-shita',
    kana: 'した',
    kanji: '下',
    meaning: 'below; under',
    partOfSpeech: 'noun',
    tags: ['position', 'n5'],
    exampleIds: ['ex-kaban-isu-shita', 'ex-neko-tsukue-shita'],
  },
  {
    id: 'vocab-naka',
    kana: 'なか',
    kanji: '中',
    meaning: 'inside',
    partOfSpeech: 'noun',
    tags: ['position', 'n5'],
    exampleIds: ['ex-hon-kaban-naka'],
  },
] satisfies VocabItem[];
