import type { VocabItem } from '../lib/content/types';

export const vocabItems = [
  {
    id: 'vocab-watashi',
    kana: 'わたし',
    kanji: '私',
    meaning: 'I; me',
    partOfSpeech: 'pronoun',
    tags: ['self', 'n5'],
    exampleIds: ['ex-colin-desu', 'ex-student-desu'],
  },
  {
    id: 'vocab-gakusei',
    kana: 'がくせい',
    kanji: '学生',
    meaning: 'student',
    partOfSpeech: 'noun',
    tags: ['school', 'identity', 'n5'],
    exampleIds: ['ex-student-desu'],
  },
  {
    id: 'vocab-sensei',
    kana: 'せんせい',
    kanji: '先生',
    meaning: 'teacher',
    partOfSpeech: 'noun',
    tags: ['school', 'role', 'n5'],
    exampleIds: ['ex-teacher-question'],
  },
  {
    id: 'vocab-tomodachi',
    kana: 'ともだち',
    kanji: '友だち',
    meaning: 'friend',
    partOfSpeech: 'noun',
    tags: ['people', 'n5'],
    exampleIds: ['ex-company-worker'],
  },
  {
    id: 'vocab-kaishain',
    kana: 'かいしゃいん',
    kanji: '会社員',
    meaning: 'office worker',
    partOfSpeech: 'noun',
    tags: ['work', 'identity', 'n5'],
    exampleIds: ['ex-company-worker'],
  },
  {
    id: 'vocab-uchi',
    kana: 'うち',
    kanji: null,
    meaning: 'home',
    partOfSpeech: 'noun',
    tags: ['place', 'daily-routine', 'n5'],
    exampleIds: ['ex-study-home'],
  },
  {
    id: 'vocab-nihongo',
    kana: 'にほんご',
    kanji: '日本語',
    meaning: 'Japanese language',
    partOfSpeech: 'noun',
    tags: ['study', 'language', 'n5'],
    exampleIds: ['ex-study-home'],
  },
  {
    id: 'vocab-benkyoushimasu',
    kana: 'べんきょうします',
    kanji: '勉強します',
    meaning: 'to study',
    partOfSpeech: 'verb',
    tags: ['study', 'daily-routine', 'n5'],
    exampleIds: ['ex-study-home', 'ex-classroom-study'],
  },
  {
    id: 'vocab-kafe',
    kana: 'カフェ',
    kanji: null,
    meaning: 'cafe',
    partOfSpeech: 'noun',
    tags: ['place', 'daily-routine', 'n5'],
    exampleIds: ['ex-coffee-cafe'],
  },
  {
    id: 'vocab-koohii',
    kana: 'コーヒー',
    kanji: null,
    meaning: 'coffee',
    partOfSpeech: 'noun',
    tags: ['food', 'daily-routine', 'n5'],
    exampleIds: ['ex-coffee-cafe'],
  },
  {
    id: 'vocab-nomimasu',
    kana: 'のみます',
    kanji: '飲みます',
    meaning: 'to drink',
    partOfSpeech: 'verb',
    tags: ['action', 'daily-routine', 'n5'],
    exampleIds: ['ex-coffee-cafe'],
  },
  {
    id: 'vocab-toshokan',
    kana: 'としょかん',
    kanji: '図書館',
    meaning: 'library',
    partOfSpeech: 'noun',
    tags: ['place', 'study', 'n5'],
    exampleIds: ['ex-read-library'],
  },
] satisfies VocabItem[];
