import type { VocabItem } from '../lib/content/types';

export const vocabItems = [
  {
    id: 'vocab-watashi',
    kana: 'わたし',
    kanji: '私',
    meaning: 'I; me',
    partOfSpeech: 'pronoun',
    tags: ['self', 'n5'],
    exampleIds: ['ex-colin-desu', 'ex-student-desu'],
  },
  {
    id: 'vocab-gakusei',
    kana: 'がくせい',
    kanji: '学生',
    meaning: 'student',
    partOfSpeech: 'noun',
    tags: ['school', 'identity', 'n5'],
    exampleIds: ['ex-student-desu'],
  },
  {
    id: 'vocab-sensei',
    kana: 'せんせい',
    kanji: '先生',
    meaning: 'teacher',
    partOfSpeech: 'noun',
    tags: ['school', 'role', 'n5'],
    exampleIds: ['ex-teacher-question'],
  },
  {
    id: 'vocab-tomodachi',
    kana: 'ともだち',
    kanji: '友だち',
    meaning: 'friend',
    partOfSpeech: 'noun',
    tags: ['people', 'n5'],
    exampleIds: ['ex-company-worker'],
  },
  {
    id: 'vocab-kaishain',
    kana: 'かいしゃいん',
    kanji: '会社員',
    meaning: 'office worker',
    partOfSpeech: 'noun',
    tags: ['work', 'identity', 'n5'],
    exampleIds: ['ex-company-worker'],
  },
  {
    id: 'vocab-uchi',
    kana: 'うち',
    kanji: null,
    meaning: 'home',
    partOfSpeech: 'noun',
    tags: ['place', 'daily-routine', 'n5'],
    exampleIds: ['ex-study-home'],
  },
  {
    id: 'vocab-nihongo',
    kana: 'にほんご',
    kanji: '日本語',
    meaning: 'Japanese language',
    partOfSpeech: 'noun',
    tags: ['study', 'language', 'n5'],
    exampleIds: ['ex-study-home'],
  },
  {
    id: 'vocab-benkyoushimasu',
    kana: 'べんきょうします',
    kanji: '勉強します',
    meaning: 'to study',
    partOfSpeech: 'verb',
    tags: ['study', 'daily-routine', 'n5'],
    exampleIds: ['ex-study-home', 'ex-classroom-study'],
  },
  {
    id: 'vocab-kafe',
    kana: 'カフェ',
    kanji: null,
    meaning: 'cafe',
    partOfSpeech: 'noun',
    tags: ['place', 'daily-routine', 'n5'],
    exampleIds: ['ex-coffee-cafe'],
  },
  {
    id: 'vocab-koohii',
    kana: 'コーヒー',
    kanji: null,
    meaning: 'coffee',
    partOfSpeech: 'noun',
    tags: ['food', 'daily-routine', 'n5'],
    exampleIds: ['ex-coffee-cafe'],
  },
  {
    id: 'vocab-nomimasu',
    kana: 'のみます',
    kanji: '飲みます',
    meaning: 'to drink',
    partOfSpeech: 'verb',
    tags: ['action', 'daily-routine', 'n5'],
    exampleIds: ['ex-coffee-cafe'],
  },
  {
    id: 'vocab-toshokan',
    kana: 'としょかん',
    kanji: '図書館',
    meaning: 'library',
    partOfSpeech: 'noun',
    tags: ['place', 'study', 'n5'],
    exampleIds: ['ex-read-library'],
  },
  {
    id: 'vocab-kore',
    kana: 'これ',
    kanji: null,
    meaning: 'this',
    partOfSpeech: 'pronoun',
    tags: ['classroom', 'demonstrative', 'n5'],
    exampleIds: ['ex-kore-hon', 'ex-kore-nan', 'ex-kore-eigo-hon'],
  },
  {
    id: 'vocab-sore',
    kana: 'それ',
    kanji: null,
    meaning: 'that',
    partOfSpeech: 'pronoun',
    tags: ['classroom', 'demonstrative', 'n5'],
    exampleIds: ['ex-sore-shukudai'],
  },
  {
    id: 'vocab-nan',
    kana: 'なん',
    kanji: '何',
    meaning: 'what',
    partOfSpeech: 'question',
    tags: ['question', 'classroom', 'n5'],
    exampleIds: ['ex-kore-nan'],
  },
  {
    id: 'vocab-hon',
    kana: 'ほん',
    kanji: '本',
    meaning: 'book',
    partOfSpeech: 'noun',
    tags: ['classroom', 'study', 'n5'],
    exampleIds: ['ex-kore-hon', 'ex-kore-eigo-hon'],
  },
  {
    id: 'vocab-eigo',
    kana: 'えいご',
    kanji: '英語',
    meaning: 'English language',
    partOfSpeech: 'noun',
    tags: ['study', 'language', 'n5'],
    exampleIds: ['ex-kore-eigo-hon'],
  },
  {
    id: 'vocab-shukudai',
    kana: 'しゅくだい',
    kanji: '宿題',
    meaning: 'homework',
    partOfSpeech: 'noun',
    tags: ['study', 'classroom', 'n5'],
    exampleIds: ['ex-sore-shukudai'],
  },
  {
    id: 'vocab-doko',
    kana: 'どこ',
    kanji: null,
    meaning: 'where',
    partOfSpeech: 'question',
    tags: ['question', 'place', 'n5'],
    exampleIds: ['ex-doko-ikimasu', 'ex-sensei-doko'],
  },
  {
    id: 'vocab-gakkou',
    kana: 'がっこう',
    kanji: '学校',
    meaning: 'school',
    partOfSpeech: 'noun',
    tags: ['school', 'place', 'n5'],
    exampleIds: ['ex-mainichi-gakkou', 'ex-tomodachi-gakkou'],
  },
  {
    id: 'vocab-ikimasu',
    kana: 'いきます',
    kanji: '行きます',
    meaning: 'to go',
    partOfSpeech: 'verb',
    tags: ['movement', 'daily-routine', 'n5'],
    exampleIds: [
      'ex-doko-ikimasu',
      'ex-mainichi-gakkou',
      'ex-kyou-toshokan',
      'ex-ima-kyoushitsu',
    ],
  },
  {
    id: 'vocab-mainichi',
    kana: 'まいにち',
    kanji: '毎日',
    meaning: 'every day',
    partOfSpeech: 'expression',
    tags: ['time', 'daily-routine', 'n5'],
    exampleIds: ['ex-mainichi-gakkou'],
  },
  {
    id: 'vocab-kyou',
    kana: 'きょう',
    kanji: '今日',
    meaning: 'today',
    partOfSpeech: 'expression',
    tags: ['time', 'daily-routine', 'n5'],
    exampleIds: ['ex-kyou-toshokan'],
  },
  {
    id: 'vocab-ima',
    kana: 'いま',
    kanji: '今',
    meaning: 'now',
    partOfSpeech: 'expression',
    tags: ['time', 'daily-routine', 'n5'],
    exampleIds: ['ex-ima-kyoushitsu'],
  },
  {
    id: 'vocab-kyoushitsu',
    kana: 'きょうしつ',
    kanji: '教室',
    meaning: 'classroom',
    partOfSpeech: 'noun',
    tags: ['school', 'place', 'n5'],
    exampleIds: ['ex-ima-kyoushitsu'],
  },
  {
    id: 'vocab-heya',
    kana: 'へや',
    kanji: '部屋',
    meaning: 'room',
    partOfSpeech: 'noun',
    tags: ['place', 'home', 'n5'],
    exampleIds: ['ex-neko-heya-imasu'],
  },
  {
    id: 'vocab-tsukue',
    kana: 'つくえ',
    kanji: '机',
    meaning: 'desk',
    partOfSpeech: 'noun',
    tags: ['place', 'classroom', 'n5'],
    exampleIds: ['ex-hon-tsukue-ue', 'ex-neko-tsukue-shita'],
  },
  {
    id: 'vocab-isu',
    kana: 'いす',
    kanji: null,
    meaning: 'chair',
    partOfSpeech: 'noun',
    tags: ['furniture', 'classroom', 'n5'],
    exampleIds: ['ex-kaban-isu-shita'],
  },
  {
    id: 'vocab-kaban',
    kana: 'かばん',
    kanji: null,
    meaning: 'bag',
    partOfSpeech: 'noun',
    tags: ['daily-routine', 'object', 'n5'],
    exampleIds: ['ex-kaban-isu-shita', 'ex-hon-kaban-naka'],
  },
  {
    id: 'vocab-neko',
    kana: 'ねこ',
    kanji: '猫',
    meaning: 'cat',
    partOfSpeech: 'noun',
    tags: ['animal', 'n5'],
    exampleIds: ['ex-neko-heya-imasu', 'ex-neko-tsukue-shita'],
  },
  {
    id: 'vocab-inu',
    kana: 'いぬ',
    kanji: '犬',
    meaning: 'dog',
    partOfSpeech: 'noun',
    tags: ['animal', 'n5'],
    exampleIds: ['ex-inu-uchi-imasu'],
  },
  {
    id: 'vocab-arimasu',
    kana: 'あります',
    kanji: null,
    meaning: 'to exist; there is/are (for things)',
    partOfSpeech: 'verb',
    tags: ['existence', 'n5'],
    exampleIds: ['ex-hon-toshokan-arimasu', 'ex-hon-tsukue-ue', 'ex-hon-kaban-naka'],
  },
  {
    id: 'vocab-imasu',
    kana: 'います',
    kanji: null,
    meaning: 'to exist; there is/are (for people and animals)',
    partOfSpeech: 'verb',
    tags: ['existence', 'n5'],
    exampleIds: ['ex-neko-heya-imasu', 'ex-sensei-kyoushitsu-imasu', 'ex-inu-uchi-imasu'],
  },
  {
    id: 'vocab-ue',
    kana: 'うえ',
    kanji: '上',
    meaning: 'top; above; on',
    partOfSpeech: 'noun',
    tags: ['position', 'n5'],
    exampleIds: ['ex-hon-tsukue-ue'],
  },
  {
    id: 'vocab-shita',
    kana: 'した',
    kanji: '下',
    meaning: 'below; under',
    partOfSpeech: 'noun',
    tags: ['position', 'n5'],
    exampleIds: ['ex-kaban-isu-shita', 'ex-neko-tsukue-shita'],
  },
  {
    id: 'vocab-naka',
    kana: 'なか',
    kanji: '中',
    meaning: 'inside',
    partOfSpeech: 'noun',
    tags: ['position', 'n5'],
    exampleIds: ['ex-hon-kaban-naka'],
  },
  {
    id: 'vocab-suki',
    kana: 'すき',
    kanji: '好き',
    meaning: 'liked; to like',
    partOfSpeech: 'expression',
    tags: ['preference', 'n5'],
    exampleIds: ['ex-watashi-sushi-suki', 'ex-ongaku-suki', 'ex-anime-suki'],
  },
  {
    id: 'vocab-kirai',
    kana: 'きらい',
    kanji: '嫌い',
    meaning: 'disliked; to dislike',
    partOfSpeech: 'expression',
    tags: ['preference', 'n5'],
    exampleIds: ['ex-watashi-koohii-kirai', 'ex-sakkaa-kirai'],
  },
  {
    id: 'vocab-sushi',
    kana: 'すし',
    kanji: '寿司',
    meaning: 'sushi',
    partOfSpeech: 'noun',
    tags: ['food', 'daily-conversation', 'n5'],
    exampleIds: ['ex-watashi-sushi-suki'],
  },
  {
    id: 'vocab-raamen',
    kana: 'ラーメン',
    kanji: null,
    meaning: 'ramen',
    partOfSpeech: 'noun',
    tags: ['food', 'daily-conversation', 'n5'],
    exampleIds: ['ex-tomodachi-raamen-suki'],
  },
  {
    id: 'vocab-ongaku',
    kana: 'おんがく',
    kanji: '音楽',
    meaning: 'music',
    partOfSpeech: 'noun',
    tags: ['hobby', 'daily-conversation', 'n5'],
    exampleIds: ['ex-ongaku-suki'],
  },
  {
    id: 'vocab-anime',
    kana: 'アニメ',
    kanji: null,
    meaning: 'anime',
    partOfSpeech: 'noun',
    tags: ['hobby', 'daily-conversation', 'n5'],
    exampleIds: ['ex-anime-suki'],
  },
  {
    id: 'vocab-sakkaa',
    kana: 'サッカー',
    kanji: null,
    meaning: 'soccer',
    partOfSpeech: 'noun',
    tags: ['sport', 'daily-conversation', 'n5'],
    exampleIds: ['ex-sakkaa-kirai'],
  },
  {
    id: 'vocab-eiga',
    kana: 'えいが',
    kanji: '映画',
    meaning: 'movie; film',
    partOfSpeech: 'noun',
    tags: ['hobby', 'daily-conversation', 'n5'],
    exampleIds: ['ex-eiga-suki-ka'],
  },
  {
    id: 'vocab-tabemono',
    kana: 'たべもの',
    kanji: '食べ物',
    meaning: 'food',
    partOfSpeech: 'noun',
    tags: ['food', 'daily-conversation', 'n5'],
    exampleIds: ['ex-tabemono-nani-suki'],
  },
  {
    id: 'vocab-cha',
    kana: 'ちゃ',
    kanji: '茶',
    meaning: 'tea',
    partOfSpeech: 'noun',
    tags: ['drink', 'daily-conversation', 'n5'],
    exampleIds: ['ex-cha-suki'],
  },
  {
    id: 'vocab-nomimono',
    kana: 'のみもの',
    kanji: '飲み物',
    meaning: 'drink; beverage',
    partOfSpeech: 'noun',
    tags: ['drink', 'daily-conversation', 'n5'],
    exampleIds: ['ex-nomimono-nani-suki'],
  },
  {
    id: 'vocab-koko',
    kana: 'ここ',
    kanji: null,
    meaning: 'here',
    partOfSpeech: 'noun',
    tags: ['location', 'daily-conversation', 'n5'],
    exampleIds: ['ex-jimusho-koko'],
  },
  {
    id: 'vocab-soko',
    kana: 'そこ',
    kanji: null,
    meaning: 'there',
    partOfSpeech: 'noun',
    tags: ['location', 'daily-conversation', 'n5'],
    exampleIds: ['ex-genkan-soko'],
  },
  {
    id: 'vocab-asoko',
    kana: 'あそこ',
    kanji: null,
    meaning: 'over there',
    partOfSpeech: 'noun',
    tags: ['location', 'daily-conversation', 'n5'],
    exampleIds: ['ex-toire-asoko'],
  },
  {
    id: 'vocab-toire',
    kana: 'トイレ',
    kanji: null,
    meaning: 'bathroom; restroom',
    partOfSpeech: 'noun',
    tags: ['place', 'daily-conversation', 'n5'],
    exampleIds: ['ex-toire-doko', 'ex-toire-asoko'],
  },
  {
    id: 'vocab-kagi',
    kana: 'かぎ',
    kanji: '鍵',
    meaning: 'key',
    partOfSpeech: 'noun',
    tags: ['object', 'daily-conversation', 'n5'],
    exampleIds: ['ex-kagi-doko', 'ex-kagi-tsukue-ue-arimasu'],
  },
  {
    id: 'vocab-kutsu',
    kana: 'くつ',
    kanji: '靴',
    meaning: 'shoes',
    partOfSpeech: 'noun',
    tags: ['daily-routine', 'object', 'n5'],
    exampleIds: ['ex-kutsu-genkan-arimasu'],
  },
  {
    id: 'vocab-jitensha',
    kana: 'じてんしゃ',
    kanji: '自転車',
    meaning: 'bicycle',
    partOfSpeech: 'noun',
    tags: ['daily-routine', 'transport', 'n5'],
    exampleIds: ['ex-jitensha-doko'],
  },
  {
    id: 'vocab-genkan',
    kana: 'げんかん',
    kanji: '玄関',
    meaning: 'entrance; entryway',
    partOfSpeech: 'noun',
    tags: ['place', 'home', 'n5'],
    exampleIds: ['ex-genkan-soko', 'ex-kutsu-genkan-arimasu'],
  },
  {
    id: 'vocab-jimusho',
    kana: 'じむしょ',
    kanji: '事務所',
    meaning: 'office',
    partOfSpeech: 'noun',
    tags: ['place', 'school', 'n5'],
    exampleIds: ['ex-jimusho-koko', 'ex-sensei-jimusho-imasu'],
  },
  {
    id: 'vocab-doko-desu',
    kana: 'どこですか',
    kanji: null,
    meaning: 'where is it?; where is ...?',
    partOfSpeech: 'expression',
    tags: ['question', 'location', 'n5'],
    exampleIds: ['ex-toire-doko', 'ex-kagi-doko', 'ex-sensei-doko-desu'],
  },
  {
    id: 'vocab-no-ownership',
    kana: 'の',
    kanji: null,
    meaning: 'of; belonging to',
    partOfSpeech: 'particle',
    tags: ['possession', 'n5'],
    exampleIds: [
      'ex-kore-watashi-no-hon',
      'ex-sore-ane-no-kaban',
      'ex-kore-chichi-no-kamera',
    ],
  },
  {
    id: 'vocab-ane',
    kana: 'あね',
    kanji: '姉',
    meaning: 'older sister',
    partOfSpeech: 'noun',
    tags: ['family', 'n5'],
    exampleIds: ['ex-sore-ane-no-kaban', 'ex-ane-no-shashin'],
  },
  {
    id: 'vocab-ani',
    kana: 'あに',
    kanji: '兄',
    meaning: 'older brother',
    partOfSpeech: 'noun',
    tags: ['family', 'n5'],
    exampleIds: ['ex-ani-no-kasa'],
  },
  {
    id: 'vocab-imouto',
    kana: 'いもうと',
    kanji: '妹',
    meaning: 'younger sister',
    partOfSpeech: 'noun',
    tags: ['family', 'n5'],
    exampleIds: ['ex-sore-imouto-no-keitai'],
  },
  {
    id: 'vocab-otouto',
    kana: 'おとうと',
    kanji: '弟',
    meaning: 'younger brother',
    partOfSpeech: 'noun',
    tags: ['family', 'n5'],
    exampleIds: ['ex-kore-otouto-no-hon'],
  },
  {
    id: 'vocab-haha',
    kana: 'はは',
    kanji: '母',
    meaning: 'mother',
    partOfSpeech: 'noun',
    tags: ['family', 'n5'],
    exampleIds: ['ex-sore-haha-no-kasa'],
  },
  {
    id: 'vocab-chichi',
    kana: 'ちち',
    kanji: '父',
    meaning: 'father',
    partOfSpeech: 'noun',
    tags: ['family', 'n5'],
    exampleIds: ['ex-kore-chichi-no-kamera'],
  },
  {
    id: 'vocab-kazoku',
    kana: 'かぞく',
    kanji: '家族',
    meaning: 'family',
    partOfSpeech: 'noun',
    tags: ['family', 'n5'],
    exampleIds: ['ex-kore-kazoku-no-shashin'],
  },
  {
    id: 'vocab-shashin',
    kana: 'しゃしん',
    kanji: '写真',
    meaning: 'photo; photograph',
    partOfSpeech: 'noun',
    tags: ['object', 'daily-conversation', 'n5'],
    exampleIds: ['ex-kore-kazoku-no-shashin', 'ex-ane-no-shashin'],
  },
  {
    id: 'vocab-kasa',
    kana: 'かさ',
    kanji: '傘',
    meaning: 'umbrella',
    partOfSpeech: 'noun',
    tags: ['object', 'daily-conversation', 'n5'],
    exampleIds: ['ex-sore-haha-no-kasa', 'ex-ani-no-kasa'],
  },
  {
    id: 'vocab-keitai',
    kana: 'けいたい',
    kanji: '携帯',
    meaning: 'mobile phone',
    partOfSpeech: 'noun',
    tags: ['object', 'daily-conversation', 'n5'],
    exampleIds: ['ex-sore-imouto-no-keitai'],
  },
  {
    id: 'vocab-kamera',
    kana: 'カメラ',
    kanji: null,
    meaning: 'camera',
    partOfSpeech: 'noun',
    tags: ['object', 'daily-conversation', 'n5'],
    exampleIds: ['ex-kore-chichi-no-kamera', 'ex-watashi-no-kamera'],
  },
  {
    id: 'vocab-tabemasu',
    kana: 'たべます',
    kanji: '食べます',
    meaning: 'to eat',
    partOfSpeech: 'verb',
    tags: ['daily-routine', 'verb-forms', 'n5'],
    exampleIds: ['ex-asa-pan-tabemasu', 'ex-asa-pan-tabemasen'],
  },
  {
    id: 'vocab-yomimasu',
    kana: 'よみます',
    kanji: '読みます',
    meaning: 'to read',
    partOfSpeech: 'verb',
    tags: ['daily-routine', 'verb-forms', 'n5'],
    exampleIds: ['ex-yoru-hon-yomimasu'],
  },
  {
    id: 'vocab-mimasu',
    kana: 'みます',
    kanji: '見ます',
    meaning: 'to watch; to see',
    partOfSpeech: 'verb',
    tags: ['daily-routine', 'verb-forms', 'n5'],
    exampleIds: ['ex-uchi-terebi-mimasu', 'ex-uchi-terebi-mimasen'],
  },
  {
    id: 'vocab-kikimasu',
    kana: 'ききます',
    kanji: '聞きます',
    meaning: 'to listen',
    partOfSpeech: 'verb',
    tags: ['daily-routine', 'verb-forms', 'n5'],
    exampleIds: ['ex-kouen-ongaku-kikimasu'],
  },
  {
    id: 'vocab-ashita',
    kana: 'あした',
    kanji: '明日',
    meaning: 'tomorrow',
    partOfSpeech: 'expression',
    tags: ['time', 'daily-routine', 'n5'],
    exampleIds: ['ex-ashita-toshokan-ikimasen'],
  },
  {
    id: 'vocab-asa',
    kana: 'あさ',
    kanji: '朝',
    meaning: 'morning',
    partOfSpeech: 'expression',
    tags: ['time', 'daily-routine', 'n5'],
    exampleIds: ['ex-asa-pan-tabemasu', 'ex-asa-pan-tabemasen'],
  },
  {
    id: 'vocab-yoru',
    kana: 'よる',
    kanji: '夜',
    meaning: 'night; evening',
    partOfSpeech: 'expression',
    tags: ['time', 'daily-routine', 'n5'],
    exampleIds: ['ex-yoru-hon-yomimasu', 'ex-yoru-nihongo-benkyoushimasu'],
  },
  {
    id: 'vocab-mizu',
    kana: 'みず',
    kanji: '水',
    meaning: 'water',
    partOfSpeech: 'noun',
    tags: ['drink', 'daily-routine', 'n5'],
    exampleIds: ['ex-kyou-mizu-nomimasu'],
  },
  {
    id: 'vocab-pan',
    kana: 'パン',
    kanji: null,
    meaning: 'bread',
    partOfSpeech: 'noun',
    tags: ['food', 'daily-routine', 'n5'],
    exampleIds: ['ex-asa-pan-tabemasu', 'ex-asa-pan-tabemasen'],
  },
  {
    id: 'vocab-terebi',
    kana: 'テレビ',
    kanji: null,
    meaning: 'TV; television',
    partOfSpeech: 'noun',
    tags: ['object', 'daily-routine', 'n5'],
    exampleIds: ['ex-uchi-terebi-mimasu', 'ex-uchi-terebi-mimasen'],
  },
  {
    id: 'vocab-kouen',
    kana: 'こうえん',
    kanji: '公園',
    meaning: 'park',
    partOfSpeech: 'noun',
    tags: ['place', 'daily-routine', 'n5'],
    exampleIds: ['ex-kouen-ongaku-kikimasu'],
  },
  {
    id: 'vocab-omoshiroi',
    kana: 'おもしろい',
    kanji: null,
    meaning: 'interesting',
    partOfSpeech: 'expression',
    tags: ['adjectives', 'daily-conversation', 'n5'],
    exampleIds: ['ex-hon-omoshiroi'],
  },
  {
    id: 'vocab-ookii',
    kana: 'おおきい',
    kanji: '大きい',
    meaning: 'big',
    partOfSpeech: 'expression',
    tags: ['adjectives', 'daily-conversation', 'n5'],
    exampleIds: ['ex-kaban-ookii'],
  },
  {
    id: 'vocab-chiisai',
    kana: 'ちいさい',
    kanji: '小さい',
    meaning: 'small',
    partOfSpeech: 'expression',
    tags: ['adjectives', 'daily-conversation', 'n5'],
    exampleIds: ['ex-chiisai-kaban-desu'],
  },
  {
    id: 'vocab-shizuka',
    kana: 'しずか',
    kanji: '静か',
    meaning: 'quiet',
    partOfSpeech: 'expression',
    tags: ['adjectives', 'daily-conversation', 'n5'],
    exampleIds: ['ex-heya-shizuka', 'ex-shizuka-heya-desu'],
  },
  {
    id: 'vocab-atarashii',
    kana: 'あたらしい',
    kanji: '新しい',
    meaning: 'new',
    partOfSpeech: 'expression',
    tags: ['adjectives', 'daily-conversation', 'n5'],
    exampleIds: ['ex-kamera-atarashii', 'ex-atarashii-kamera-desu'],
  },
  {
    id: 'vocab-furui',
    kana: 'ふるい',
    kanji: '古い',
    meaning: 'old',
    partOfSpeech: 'expression',
    tags: ['adjectives', 'daily-conversation', 'n5'],
    exampleIds: ['ex-hon-furui'],
  },
  {
    id: 'vocab-kirei',
    kana: 'きれい',
    kanji: null,
    meaning: 'pretty; clean',
    partOfSpeech: 'expression',
    tags: ['adjectives', 'daily-conversation', 'n5'],
    exampleIds: ['ex-kirei-mise-desu'],
  },
  {
    id: 'vocab-yasashii',
    kana: 'やさしい',
    kanji: '優しい',
    meaning: 'kind; gentle',
    partOfSpeech: 'expression',
    tags: ['adjectives', 'daily-conversation', 'n5'],
    exampleIds: ['ex-yasashii-sensei-desu'],
  },
  {
    id: 'vocab-hiroi',
    kana: 'ひろい',
    kanji: '広い',
    meaning: 'wide; spacious',
    partOfSpeech: 'expression',
    tags: ['adjectives', 'daily-conversation', 'n5'],
    exampleIds: ['ex-hiroi-heya-desu'],
  },
  {
    id: 'vocab-mise',
    kana: 'みせ',
    kanji: '店',
    meaning: 'shop; store',
    partOfSpeech: 'noun',
    tags: ['place', 'daily-conversation', 'n5'],
    exampleIds: ['ex-kirei-mise-desu'],
  },
  {
    id: 'vocab-hito',
    kana: 'ひと',
    kanji: '人',
    meaning: 'person',
    partOfSpeech: 'noun',
    tags: ['people', 'daily-conversation', 'n5'],
    exampleIds: ['ex-hito-yasashii'],
  },
  {
    id: 'vocab-kinou',
    kana: 'きのう',
    kanji: '昨日',
    meaning: 'yesterday',
    partOfSpeech: 'expression',
    tags: ['time', 'daily-routine', 'n5'],
    exampleIds: [
      'ex-kinou-hon-yomimashita',
      'ex-kinou-uchi-nihongo-benkyoushimashita',
      'ex-kinou-koohii-nomimasendeshita',
      'ex-kinou-gakkou-ikimasendeshita',
    ],
  },
  {
    id: 'vocab-yomimashita',
    kana: 'よみました',
    kanji: '読みました',
    meaning: 'read (polite past)',
    partOfSpeech: 'expression',
    tags: ['verb-forms', 'past-tense', 'n5'],
    exampleIds: ['ex-kinou-hon-yomimashita'],
  },
  {
    id: 'vocab-tabemashita',
    kana: 'たべました',
    kanji: '食べました',
    meaning: 'ate (polite past)',
    partOfSpeech: 'expression',
    tags: ['verb-forms', 'past-tense', 'n5'],
    exampleIds: ['ex-asa-pan-tabemashita'],
  },
  {
    id: 'vocab-nomimashita',
    kana: 'のみました',
    kanji: '飲みました',
    meaning: 'drank (polite past)',
    partOfSpeech: 'expression',
    tags: ['verb-forms', 'past-tense', 'n5'],
    exampleIds: ['ex-kafe-koohii-nomimashita', 'ex-asa-mizu-nomimashita'],
  },
  {
    id: 'vocab-ikimashita',
    kana: 'いきました',
    kanji: '行きました',
    meaning: 'went (polite past)',
    partOfSpeech: 'expression',
    tags: ['verb-forms', 'past-tense', 'n5'],
    exampleIds: ['ex-kyou-toshokan-ikimashita'],
  },
  {
    id: 'vocab-benkyoushimashita',
    kana: 'べんきょうしました',
    kanji: '勉強しました',
    meaning: 'studied (polite past)',
    partOfSpeech: 'expression',
    tags: ['verb-forms', 'past-tense', 'n5'],
    exampleIds: ['ex-kinou-uchi-nihongo-benkyoushimashita'],
  },
  {
    id: 'vocab-mimashita',
    kana: 'みました',
    kanji: '見ました',
    meaning: 'watched; saw (polite past)',
    partOfSpeech: 'expression',
    tags: ['verb-forms', 'past-tense', 'n5'],
    exampleIds: ['ex-senshuu-eiga-mimashita', 'ex-kinou-eiga-mimasendeshita'],
  },
  {
    id: 'vocab-kikimashita',
    kana: 'ききました',
    kanji: '聞きました',
    meaning: 'listened (polite past)',
    partOfSpeech: 'expression',
    tags: ['verb-forms', 'past-tense', 'n5'],
    exampleIds: ['ex-kinou-kouen-ongaku-kikimashita'],
  },
  {
    id: 'vocab-senshuu',
    kana: 'せんしゅう',
    kanji: '先週',
    meaning: 'last week',
    partOfSpeech: 'expression',
    tags: ['time', 'daily-routine', 'n5'],
    exampleIds: ['ex-senshuu-eiga-mimashita'],
  },
  {
    id: 'vocab-nomimasendeshita',
    kana: 'のみませんでした',
    kanji: '飲みませんでした',
    meaning: 'did not drink (polite past)',
    partOfSpeech: 'expression',
    tags: ['verb-forms', 'negative', 'past-tense', 'n5'],
    exampleIds: ['ex-kinou-koohii-nomimasendeshita'],
  },
  {
    id: 'vocab-ikimasendeshita',
    kana: 'いきませんでした',
    kanji: '行きませんでした',
    meaning: 'did not go (polite past)',
    partOfSpeech: 'expression',
    tags: ['verb-forms', 'negative', 'past-tense', 'n5'],
    exampleIds: ['ex-kinou-gakkou-ikimasendeshita'],
  },
  {
    id: 'vocab-temo-ii-desu-ka',
    kana: 'てもいいですか',
    kanji: null,
    meaning: 'may I ...?; is it okay if ...?',
    partOfSpeech: 'expression',
    tags: ['permission', 'daily-conversation', 'n5'],
    exampleIds: ['ex-mizu-nonde-mo-ii', 'ex-toire-itte-mo-ii'],
  },
  {
    id: 'vocab-kudasai',
    kana: 'ください',
    kanji: null,
    meaning: 'please',
    partOfSpeech: 'expression',
    tags: ['request', 'daily-conversation', 'n5'],
    exampleIds: ['ex-chotto-matte-kudasai', 'ex-kore-mite-kudasai'],
  },
  {
    id: 'vocab-chotto',
    kana: 'ちょっと',
    kanji: null,
    meaning: 'a little; a moment',
    partOfSpeech: 'expression',
    tags: ['daily-conversation', 'request', 'n5'],
    exampleIds: ['ex-chotto-matte-kudasai'],
  },
  {
    id: 'vocab-mou-ichido',
    kana: 'もういちど',
    kanji: 'もう一度',
    meaning: 'one more time; again',
    partOfSpeech: 'expression',
    tags: ['daily-conversation', 'request', 'n5'],
    exampleIds: ['ex-mou-ichido-yonde-kudasai'],
  },
  {
    id: 'vocab-yukkuri',
    kana: 'ゆっくり',
    kanji: null,
    meaning: 'slowly',
    partOfSpeech: 'expression',
    tags: ['daily-conversation', 'request', 'n5'],
    exampleIds: ['ex-yukkuri-yonde-kudasai'],
  },
  {
    id: 'vocab-matte',
    kana: 'まって',
    kanji: '待って',
    meaning: 'wait (te-form)',
    partOfSpeech: 'expression',
    tags: ['verb-forms', 'request', 'n5'],
    exampleIds: ['ex-chotto-matte-kudasai'],
  },
  {
    id: 'vocab-mite',
    kana: 'みて',
    kanji: '見て',
    meaning: 'look; watch (te-form)',
    partOfSpeech: 'expression',
    tags: ['verb-forms', 'request', 'n5'],
    exampleIds: ['ex-kore-mite-kudasai'],
  },
  {
    id: 'vocab-yonde',
    kana: 'よんで',
    kanji: '読んで',
    meaning: 'read (te-form)',
    partOfSpeech: 'expression',
    tags: ['verb-forms', 'request', 'n5'],
    exampleIds: ['ex-hon-yonde-mo-ii', 'ex-yukkuri-yonde-kudasai'],
  },
  {
    id: 'vocab-nonde',
    kana: 'のんで',
    kanji: '飲んで',
    meaning: 'drink (te-form)',
    partOfSpeech: 'expression',
    tags: ['verb-forms', 'permission', 'n5'],
    exampleIds: ['ex-mizu-nonde-mo-ii'],
  },
  {
    id: 'vocab-itte',
    kana: 'いって',
    kanji: '行って',
    meaning: 'go (te-form)',
    partOfSpeech: 'expression',
    tags: ['verb-forms', 'permission', 'n5'],
    exampleIds: ['ex-toire-itte-mo-ii'],
  },
  {
    id: 'vocab-suwatte',
    kana: 'すわって',
    kanji: '座って',
    meaning: 'sit (te-form)',
    partOfSpeech: 'expression',
    tags: ['verb-forms', 'daily-conversation', 'n5'],
    exampleIds: ['ex-koko-suwatte-mo-ii', 'ex-koko-suwatte-kudasai'],
  },
  {
    id: 'vocab-mado',
    kana: 'まど',
    kanji: '窓',
    meaning: 'window',
    partOfSpeech: 'noun',
    tags: ['place', 'daily-conversation', 'n5'],
    exampleIds: ['ex-mado-akete-mo-ii'],
  },
  {
    id: 'vocab-akete',
    kana: 'あけて',
    kanji: '開けて',
    meaning: 'open (te-form)',
    partOfSpeech: 'expression',
    tags: ['verb-forms', 'daily-conversation', 'n5'],
    exampleIds: ['ex-mado-akete-mo-ii', 'ex-mado-akete-kudasai'],
  },
  {
    id: 'vocab-kaimasu',
    kana: 'かいます',
    kanji: '買います',
    meaning: 'to buy',
    partOfSpeech: 'verb',
    tags: ['shopping', 'daily-conversation', 'n5'],
    exampleIds: [
      'ex-mizu-o-kaimasu',
      'ex-ringo-o-kaimasu',
      'ex-juusu-o-kaimasu',
      'ex-kudamono-o-kaimasu',
      'ex-sakana-o-kaimasu',
      'ex-niku-o-kaimasu',
      'ex-konbini-de-okashi-o-kaimasu',
    ],
  },
  {
    id: 'vocab-kono',
    kana: 'この',
    kanji: null,
    meaning: 'this (before a noun)',
    partOfSpeech: 'expression',
    tags: ['shopping', 'demonstrative', 'n5'],
    exampleIds: ['ex-kono-hon-o-kudasai'],
  },
  {
    id: 'vocab-dore',
    kana: 'どれ',
    kanji: null,
    meaning: 'which one',
    partOfSpeech: 'question',
    tags: ['shopping', 'question', 'n5'],
    exampleIds: ['ex-dore-o-kaimasu'],
  },
  {
    id: 'vocab-konbini',
    kana: 'コンビニ',
    kanji: null,
    meaning: 'convenience store',
    partOfSpeech: 'noun',
    tags: ['shopping', 'place', 'n5'],
    exampleIds: ['ex-konbini-de-okashi-o-kaimasu'],
  },
  {
    id: 'vocab-ringo',
    kana: 'りんご',
    kanji: null,
    meaning: 'apple',
    partOfSpeech: 'noun',
    tags: ['shopping', 'food', 'n5'],
    exampleIds: ['ex-ringo-o-kaimasu'],
  },
  {
    id: 'vocab-juusu',
    kana: 'ジュース',
    kanji: null,
    meaning: 'juice',
    partOfSpeech: 'noun',
    tags: ['shopping', 'drink', 'n5'],
    exampleIds: ['ex-juusu-o-kaimasu'],
  },
  {
    id: 'vocab-okashi',
    kana: 'おかし',
    kanji: 'お菓子',
    meaning: 'snacks; sweets',
    partOfSpeech: 'noun',
    tags: ['shopping', 'food', 'n5'],
    exampleIds: ['ex-konbini-de-okashi-o-kaimasu'],
  },
  {
    id: 'vocab-kudamono',
    kana: 'くだもの',
    kanji: '果物',
    meaning: 'fruit',
    partOfSpeech: 'noun',
    tags: ['shopping', 'food', 'n5'],
    exampleIds: ['ex-kudamono-o-kaimasu'],
  },
  {
    id: 'vocab-sakana',
    kana: 'さかな',
    kanji: '魚',
    meaning: 'fish',
    partOfSpeech: 'noun',
    tags: ['shopping', 'food', 'n5'],
    exampleIds: ['ex-sakana-o-kaimasu'],
  },
  {
    id: 'vocab-niku',
    kana: 'にく',
    kanji: '肉',
    meaning: 'meat',
    partOfSpeech: 'noun',
    tags: ['shopping', 'food', 'n5'],
    exampleIds: ['ex-niku-o-kaimasu'],
  },
] satisfies VocabItem[];
