import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { listeningItems } from '../../src/content/listeningItems';

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(SCRIPT_DIR, '..', '..');
const PUBLIC_LISTENING_ROOT = path.join(REPO_ROOT, 'public', 'audio', 'listening');
const MANIFEST_FILE_PATH = path.join(
  REPO_ROOT,
  'src',
  'lib',
  'audio',
  'listeningAudioAssets.ts',
);

export async function syncListeningAudioManifest() {
  const generatedAudioRefs = await collectGeneratedListeningAudioRefs();
  const nextFileContents = buildListeningAudioManifestSource(generatedAudioRefs);

  await fs.writeFile(MANIFEST_FILE_PATH, nextFileContents);

  return {
    manifestPath: MANIFEST_FILE_PATH,
    generatedAudioRefs,
  };
}

async function collectGeneratedListeningAudioRefs() {
  const existingFileNames = new Set(await readListeningAudioFileNames());

  return listeningItems
    .map((item) => item.audioRef)
    .filter((audioRef): audioRef is string => typeof audioRef === 'string')
    .filter((audioRef) => existingFileNames.has(path.basename(audioRef)));
}

async function readListeningAudioFileNames() {
  const entries = await fs.readdir(PUBLIC_LISTENING_ROOT, { withFileTypes: true });

  return entries
    .filter((entry) => entry.isFile())
    .map((entry) => entry.name)
    .filter((fileName) => fileName !== 'README.md')
    .sort((left, right) => left.localeCompare(right));
}

function buildListeningAudioManifestSource(generatedAudioRefs: string[]) {
  const refsSource = generatedAudioRefs
    .map((audioRef) => `  '${audioRef}',`)
    .join('\n');

  return `import { listeningItems } from '../../content/listeningItems';

// This file is generated by \`npm run sync:listening-audio-manifest\`.
// It records which listening audio assets currently exist in \`public/audio/listening\`.
export const GENERATED_LISTENING_AUDIO_REFS = [
${refsSource}
] as const;

export function getListeningAudioStatus() {
  const assetSet = new Set<string>(GENERATED_LISTENING_AUDIO_REFS);
  const itemsWithAudioRef = listeningItems.filter((item) => Boolean(item.audioRef));
  const availableItems = itemsWithAudioRef.filter((item) =>
    item.audioRef ? assetSet.has(item.audioRef) : false,
  );
  const missingItems = itemsWithAudioRef.filter((item) =>
    item.audioRef ? !assetSet.has(item.audioRef) : false,
  );

  return {
    listeningItemCount: listeningItems.length,
    itemsWithAudioRefCount: itemsWithAudioRef.length,
    generatedAssetCount: GENERATED_LISTENING_AUDIO_REFS.length,
    matchedAssetCount: availableItems.length,
    missingItemCount: missingItems.length,
    missingItems,
  };
}
`;
}
