import { listeningItems } from '../../content/listeningItems';

// This file is generated by `npm run sync:listening-audio-manifest`.
// It records which listening audio assets currently exist in `public/audio/listening`.
export const GENERATED_LISTENING_AUDIO_REFS = [
  '/audio/listening/listening-self-intro.mp3',
  '/audio/listening/listening-teacher-question.mp3',
  '/audio/listening/listening-home-study.mp3',
  '/audio/listening/listening-cafe-coffee.mp3',
  '/audio/listening/listening-kore-nan.mp3',
  '/audio/listening/listening-kore-hon.mp3',
  '/audio/listening/listening-sore-shukudai.mp3',
  '/audio/listening/listening-kore-eigo-hon.mp3',
  '/audio/listening/listening-sore-nan.mp3',
  '/audio/listening/listening-neko-heya.mp3',
  '/audio/listening/listening-sensei-kyoushitsu.mp3',
  '/audio/listening/listening-hon-tsukue-ue.mp3',
  '/audio/listening/listening-kaban-isu-shita.mp3',
  '/audio/listening/listening-hon-kaban-naka.mp3',
  '/audio/listening/listening-watashi-sushi-suki.mp3',
  '/audio/listening/listening-koohii-kirai.mp3',
  '/audio/listening/listening-ongaku-suki.mp3',
  '/audio/listening/listening-nani-suki.mp3',
  '/audio/listening/listening-tabemono-nani-suki.mp3',
  '/audio/listening/listening-toire-doko.mp3',
  '/audio/listening/listening-toire-asoko.mp3',
  '/audio/listening/listening-kagi-doko.mp3',
  '/audio/listening/listening-kagi-tsukue-ue.mp3',
  '/audio/listening/listening-sensei-jimusho.mp3',
  '/audio/listening/listening-kore-watashi-no-hon.mp3',
  '/audio/listening/listening-sore-ane-no-kaban.mp3',
  '/audio/listening/listening-kore-chichi-no-kamera.mp3',
  '/audio/listening/listening-kore-kazoku-no-shashin.mp3',
  '/audio/listening/listening-sore-haha-no-kasa.mp3',
  '/audio/listening/listening-asa-pan-tabemasu.mp3',
  '/audio/listening/listening-yoru-hon-yomimasu.mp3',
  '/audio/listening/listening-uchi-terebi-mimasu.mp3',
  '/audio/listening/listening-kyou-koohii-nomimasen.mp3',
  '/audio/listening/listening-ashita-toshokan-ikimasen.mp3',
  '/audio/listening/listening-hon-omoshiroi.mp3',
  '/audio/listening/listening-kaban-ookii.mp3',
  '/audio/listening/listening-heya-shizuka.mp3',
  '/audio/listening/listening-kamera-atarashii.mp3',
  '/audio/listening/listening-kirei-mise.mp3',
] as const;

export function getListeningAudioStatus() {
  const assetSet = new Set<string>(GENERATED_LISTENING_AUDIO_REFS);
  const itemsWithAudioRef = listeningItems.filter((item) => Boolean(item.audioRef));
  const availableItems = itemsWithAudioRef.filter((item) =>
    item.audioRef ? assetSet.has(item.audioRef) : false,
  );
  const missingItems = itemsWithAudioRef.filter((item) =>
    item.audioRef ? !assetSet.has(item.audioRef) : false,
  );

  return {
    listeningItemCount: listeningItems.length,
    itemsWithAudioRefCount: itemsWithAudioRef.length,
    generatedAssetCount: GENERATED_LISTENING_AUDIO_REFS.length,
    matchedAssetCount: availableItems.length,
    missingItemCount: missingItems.length,
    missingItems,
  };
}
